Repository CZERTAINLY/CZERTAINLY-Core, pull requests merged in 2022-06, with the labels that each got.

#78 Add CRL Timeout and handle timeout exception
  src/main/java/com/czertainly/core/service/impl/CertValidationServiceImpl.java
  src/main/java/com/czertainly/core/util/CrlUtil.java
Labels: bug

#83 Entity provider
  pom.xml
  src/main/java/com/czertainly/core/api/ExceptionHandlingAdvice.java
  src/main/java/com/czertainly/core/api/acme/AcmeControllerImpl.java
  src/main/java/com/czertainly/core/api/acme/AcmeRaProfileControllerImpl.java
  src/main/java/com/czertainly/core/api/v2/client/ClientOperationControllerImpl.java
  src/main/java/com/czertainly/core/api/web/CertificateControllerImpl.java
  src/main/java/com/czertainly/core/api/web/EntityControllerImpl.java
  src/main/java/com/czertainly/core/api/web/EntityInstanceControllerImpl.java
  src/main/java/com/czertainly/core/api/web/LocationManagementControllerImpl.java
  src/main/java/com/czertainly/core/config/ApplicationConfig.java
  src/main/java/com/czertainly/core/dao/entity/Certificate.java
  src/main/java/com/czertainly/core/dao/entity/CertificateEntity.java
  src/main/java/com/czertainly/core/dao/entity/CertificateLocation.java
  src/main/java/com/czertainly/core/dao/entity/CertificateLocationId.java
  src/main/java/com/czertainly/core/dao/entity/Connector.java
  src/main/java/com/czertainly/core/dao/entity/EntityInstanceReference.java
  src/main/java/com/czertainly/core/dao/entity/Location.java
  src/main/java/com/czertainly/core/dao/repository/CertificateLocationRepository.java
  src/main/java/com/czertainly/core/dao/repository/CertificateRepository.java
  src/main/java/com/czertainly/core/dao/repository/EntityInstanceReferenceRepository.java
  src/main/java/com/czertainly/core/dao/repository/EntityRepository.java
  src/main/java/com/czertainly/core/dao/repository/LocationRepository.java
  src/main/java/com/czertainly/core/service/CertificateEventHistoryService.java
  src/main/java/com/czertainly/core/service/CertificateService.java
  src/main/java/com/czertainly/core/service/EntityInstanceService.java
  src/main/java/com/czertainly/core/service/EntityService.java
  src/main/java/com/czertainly/core/service/LocationService.java
  src/main/java/com/czertainly/core/service/impl/CertificateEventHistoryServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/CertificateServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/ConnectorServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/EntityInstanceServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/EntityServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/GroupServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/LocationServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/SearchServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/StatisticsServiceImpl.java
  src/main/java/com/czertainly/core/service/v2/ClientOperationService.java
  src/main/java/com/czertainly/core/service/v2/impl/ClientOperationServiceImpl.java
  src/main/java/com/czertainly/core/util/CsrUtil.java
  src/main/resources/banner.txt
  src/main/resources/db/migration/V202205180945__entity_provider.sql
  src/test/java/com/czertainly/core/service/CertificateEntityServiceTest.java
  src/test/java/com/czertainly/core/service/CertificateServiceTest.java
  src/test/java/com/czertainly/core/service/ClientOperationServiceV2Test.java
  src/test/java/com/czertainly/core/service/EntityInstanceServiceTest.java
  src/test/java/com/czertainly/core/service/LocationServiceTest.java
  src/test/java/com/czertainly/core/service/StatisticsServiceTest.java
Labels: enhancement

#90 Fix the checksum calculation of the database migration class
  src/main/java/com/czertainly/core/util/DatabaseMigration.java
  src/main/java/db/migration/V202206151000__AttributeChanges.java
  src/test/java/com/czertainly/core/util/DatabaseMigrationTest.java
Labels: bug

#96 Update calculation of checksum and enum
  src/main/java/com/czertainly/core/util/DatabaseMigration.java
Labels: bug, enhancement

#95 Fix credential callback
  src/main/java/com/czertainly/core/service/CoreCallbackService.java
  src/main/java/com/czertainly/core/service/impl/CoreCallbackServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/CredentialServiceImpl.java
  src/test/java/com/czertainly/core/service/CoreCallbackServiceTest.java
  src/test/java/com/czertainly/core/service/CredentialServiceTest.java
Labels: bug

#100 Fix revocation attributes for RA Profile ACME
  .gitignore
  src/main/java/com/czertainly/core/service/impl/RaProfileServiceImpl.java
Labels: bug
