Repository CZERTAINLY/CZERTAINLY-Core, pull requests merged in 2022-09, with the labels that each got.

#134 Add support for purging audit logs
  src/main/java/com/czertainly/core/api/web/AuditLogControllerImpl.java
  src/main/java/com/czertainly/core/service/AuditLogService.java
  src/main/java/com/czertainly/core/service/impl/AuditLogServiceImpl.java
  src/test/java/com/czertainly/core/service/AuditLogServiceTest.java
Labels: enhancement

#135 Update exception messages from entity providers
  src/main/java/com/czertainly/core/dao/entity/CertificateLocation.java
  src/main/java/com/czertainly/core/service/impl/LocationServiceImpl.java
Labels: bug

#136 Add description to compliance profile list dto
  src/main/java/com/czertainly/core/dao/entity/ComplianceProfile.java
Labels: bug

#138 Fail certificate renewal when the certificate does not have RA Profile
  src/main/java/com/czertainly/core/service/impl/LocationServiceImpl.java
Labels: bug

#139 Add attributes of the rule to the compliance result
  src/main/java/com/czertainly/core/dao/repository/ComplianceProfileRuleRepository.java
  src/main/java/com/czertainly/core/service/ComplianceService.java
  src/main/java/com/czertainly/core/service/impl/CertificateServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/ComplianceServiceImpl.java
Labels: enhancement

#140 Add separate API for certificate validation
  src/main/java/com/czertainly/core/api/web/CertificateControllerImpl.java
  src/main/java/com/czertainly/core/dao/entity/Certificate.java
  src/main/java/com/czertainly/core/service/CertificateService.java
  src/main/java/com/czertainly/core/service/impl/CertificateServiceImpl.java
Labels: enhancement

#141 Create User if the existing certificate is uploaded
  src/main/java/com/czertainly/core/service/impl/AdminServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/ClientServiceImpl.java
Labels: bug

#142 Update audit log listing and purging operation
  src/main/java/com/czertainly/core/service/impl/AuditLogServiceImpl.java
  src/test/java/com/czertainly/core/service/AuditLogServiceTest.java
Labels: bug

#146 Update versions to release
  pom.xml
Labels: ignore-for-release

#152 Access Control Updates and Permission DTOs
  src/main/java/com/czertainly/core/api/web/AuthControllerImpl.java
  src/main/java/com/czertainly/core/api/web/RoleManagementControllerImpl.java
  src/main/java/com/czertainly/core/api/web/UserManagementControllerImpl.java
  src/main/java/com/czertainly/core/auth/AuthEndpointSynchronizer.java
  src/main/java/com/czertainly/core/config/ApplicationConfig.java
  src/main/java/com/czertainly/core/security/authn/client/CzertainlyBaseAuthenticationClient.java
  src/main/java/com/czertainly/core/security/authn/client/ResourceApiClient.java
  src/main/java/com/czertainly/core/security/authn/client/RoleManagementApiClient.java
  src/main/java/com/czertainly/core/security/authn/client/UserManagementApiClient.java
  src/main/java/com/czertainly/core/service/AuthService.java
  src/main/java/com/czertainly/core/service/RoleManagementService.java
  src/main/java/com/czertainly/core/service/UserManagementService.java
  src/main/java/com/czertainly/core/service/impl/AuthServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/RoleManagementServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/UserManagementServiceImpl.java
  src/test/java/com/czertainly/core/service/AuthServiceTest.java
Labels: enhancement

#155 User management flow updates and fixes
  src/main/java/com/czertainly/core/api/web/AuthControllerImpl.java
  src/main/java/com/czertainly/core/api/web/UserManagementControllerImpl.java
  src/main/java/com/czertainly/core/service/AuthService.java
  src/main/java/com/czertainly/core/service/UserManagementService.java
  src/main/java/com/czertainly/core/service/impl/AuthServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/UserManagementServiceImpl.java
Labels: enhancement, ignore-for-release

#157 Change authentication of user with Auth Service
  src/main/java/com/czertainly/core/model/auth/AuthenticationRequestDto.java
  src/main/java/com/czertainly/core/security/authn/client/CzertainlyAuthenticationClient.java
  src/main/java/com/czertainly/core/security/authn/client/UserManagementApiClient.java
  src/main/resources/application.properties
  src/test/java/com/czertainly/core/security/authn/client/CzertainlyAuthenticationClientTest.java
  src/test/resources/application.properties
Labels: enhancement

#158 Fix header name for the token authentication
  src/main/java/com/czertainly/core/security/authn/client/CzertainlyAuthenticationClient.java
  src/main/resources/application.properties
  src/test/resources/application.properties
Labels: bug
