Repository CZERTAINLY/CZERTAINLY-Core, pull requests merged in 2022-08, with the labels that each got.

#126 Add automatic configuration of proxy based on ENV
  README.md
  entry.sh
  src/main/java/com/czertainly/core/config/proxy/MultiServerAuthenticator.java
  src/main/java/com/czertainly/core/config/proxy/ProxyConfiguration.java
  src/main/java/com/czertainly/core/config/proxy/ProxySettings.java
Labels: enhancement

#127 Improve trusted certificates handling in docker
  Dockerfile
  docker/opt/czertainly/entry.sh
  docker/opt/czertainly/prepare-truststore.sh
  docker/opt/czertainly/static-functions
  docker/opt/czertainly/update-cacerts.sh
  entry.sh
  prepare-truststore.sh
  src/main/resources/application.properties
Labels: enhancement

#128 Remove debug log when checking self signed certificate
  src/main/java/com/czertainly/core/service/impl/CertificateServiceImpl.java
Labels: bug, ignore-for-release

#130 Compliance Enhancements
  src/main/java/com/czertainly/core/dao/entity/ComplianceProfile.java
  src/main/java/com/czertainly/core/dao/entity/ComplianceProfileRule.java
  src/main/java/com/czertainly/core/dao/entity/RaProfile.java
  src/main/java/com/czertainly/core/dao/repository/CertificateRepository.java
  src/main/java/com/czertainly/core/service/impl/CertificateServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/SearchServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/StatisticsServiceImpl.java
Labels: enhancement

#132 Add configuration option to enable audit log
  src/main/java/com/czertainly/core/aop/AuditLogAspect.java
  src/main/java/com/czertainly/core/service/impl/AuditLogServiceImpl.java
  src/main/resources/application.properties
Labels: enhancement

#133 Update UUID generation method
  src/main/java/com/czertainly/core/dao/entity/UniquelyIdentified.java
Labels: bug
