Repository CZERTAINLY/CZERTAINLY-Core, pull requests merged in 2022-11, with the labels that each got.

#203 Mask secrets in credential attributes responses
  pom.xml
  src/main/java/com/czertainly/core/api/web/RAProfileManagementControllerImpl.java
  src/main/java/com/czertainly/core/dao/entity/DiscoveryHistory.java
  src/main/java/com/czertainly/core/dao/entity/Location.java
  src/main/java/com/czertainly/core/service/impl/AuthorityInstanceServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/EntityInstanceServiceImpl.java
  src/main/java/com/czertainly/core/util/SecretMaskingUtil.java
Labels: bug

#205 Mask secrets in credential attributes responses
  README.md
  pom.xml
  src/main/java/com/czertainly/core/api/web/RAProfileManagementControllerImpl.java
  src/main/java/com/czertainly/core/dao/entity/DiscoveryHistory.java
  src/main/java/com/czertainly/core/dao/entity/Location.java
  src/main/java/com/czertainly/core/service/impl/AuthorityInstanceServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/EntityInstanceServiceImpl.java
  src/main/java/com/czertainly/core/util/SecretMaskingUtil.java
Labels: bug, ignore-for-release

#201 Attribute V2 Migration
  pom.xml
  src/main/java/com/czertainly/core/api/v2/client/ClientOperationControllerImpl.java
  src/main/java/com/czertainly/core/api/web/AuthorityInstanceControllerImpl.java
  src/main/java/com/czertainly/core/api/web/CallbackControllerImpl.java
  src/main/java/com/czertainly/core/api/web/ConnectorAuthControllerImpl.java
  src/main/java/com/czertainly/core/api/web/ConnectorControllerImpl.java
  src/main/java/com/czertainly/core/api/web/EntityInstanceControllerImpl.java
  src/main/java/com/czertainly/core/api/web/LocationManagementControllerImpl.java
  src/main/java/com/czertainly/core/api/web/RAProfileManagementControllerImpl.java
  src/main/java/com/czertainly/core/dao/entity/CertificateLocation.java
  src/main/java/com/czertainly/core/dao/entity/ComplianceProfileRule.java
  src/main/java/com/czertainly/core/dao/entity/ComplianceRule.java
  src/main/java/com/czertainly/core/dao/entity/Connector.java
  src/main/java/com/czertainly/core/dao/entity/Credential.java
  src/main/java/com/czertainly/core/dao/entity/DiscoveryHistory.java
  src/main/java/com/czertainly/core/dao/entity/Location.java
  src/main/java/com/czertainly/core/dao/entity/RaProfile.java
  src/main/java/com/czertainly/core/dao/entity/acme/AcmeProfile.java
  src/main/java/com/czertainly/core/service/AuthorityInstanceService.java
  src/main/java/com/czertainly/core/service/CallbackService.java
  src/main/java/com/czertainly/core/service/ConnectorAuthService.java
  src/main/java/com/czertainly/core/service/ConnectorService.java
  src/main/java/com/czertainly/core/service/CoreCallbackService.java
  src/main/java/com/czertainly/core/service/CredentialService.java
  src/main/java/com/czertainly/core/service/EntityInstanceService.java
  src/main/java/com/czertainly/core/service/LocationService.java
  src/main/java/com/czertainly/core/service/RaProfileService.java
  src/main/java/com/czertainly/core/service/impl/AuthorityInstanceServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/CallbackServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/ClientOperationServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/ComplianceProfileServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/ConnectorAuthServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/ConnectorServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/CoreCallbackServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/CredentialServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/DiscoveryServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/EntityInstanceServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/LocationServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/RaProfileServiceImpl.java
  src/main/java/com/czertainly/core/service/v2/ClientOperationService.java
  src/main/java/com/czertainly/core/service/v2/ExtendedAttributeService.java
  src/main/java/com/czertainly/core/service/v2/impl/ClientOperationServiceImpl.java
  src/main/java/com/czertainly/core/service/v2/impl/ExtendedAttributeServiceImpl.java
  src/main/java/com/czertainly/core/util/DatabaseMigration.java
  src/main/java/com/czertainly/core/util/SecretMaskingUtil.java
  src/main/java/db/migration/V202211031400__AttributeV2Changes.java
  src/test/java/com/czertainly/core/service/ClientOperationServiceV1Test.java
  src/test/java/com/czertainly/core/service/ClientOperationServiceV2Test.java
  src/test/java/com/czertainly/core/service/ConnectorAuthServiceTest.java
  src/test/java/com/czertainly/core/service/ConnectorServiceTest.java
  src/test/java/com/czertainly/core/service/CoreCallbackServiceTest.java
  src/test/java/com/czertainly/core/service/CredentialServiceTest.java
  src/test/java/com/czertainly/core/service/LocationServiceTest.java
  src/test/java/com/czertainly/core/util/DatabaseMigrationTest.java
  src/test/java/com/czertainly/core/util/JsonSerializationTest.java
Labels: enhancement

#208 Fix converting to enum from enum code when it is send as path or query parameter
  src/main/java/com/czertainly/core/api/web/ConnectorControllerImpl.java
  src/main/java/com/czertainly/core/service/ComplianceService.java
  src/main/java/com/czertainly/core/util/converter/ConnectorStatusConverter.java
  src/main/java/com/czertainly/core/util/converter/FunctionGroupCodeConverter.java
  src/main/java/com/czertainly/core/util/converter/OptionalEnumConverter.java
Labels: bug

#214 Fix CertificateInLocationDto attribute properties type
  src/main/java/com/czertainly/core/dao/entity/Location.java
Labels: bug

#215 Custom Attribute Implementation
  src/main/java/com/czertainly/core/api/web/AcmeProfileControllerImpl.java
  src/main/java/com/czertainly/core/api/web/AuthorityInstanceControllerImpl.java
  src/main/java/com/czertainly/core/api/web/ComplianceProfileControllerImpl.java
  src/main/java/com/czertainly/core/api/web/ConnectorControllerImpl.java
  src/main/java/com/czertainly/core/api/web/CredentialControllerImpl.java
  src/main/java/com/czertainly/core/api/web/CustomAttributeControllerImpl.java
  src/main/java/com/czertainly/core/api/web/EntityInstanceControllerImpl.java
  src/main/java/com/czertainly/core/api/web/GroupControllerImpl.java
  src/main/java/com/czertainly/core/api/web/LocationManagementControllerImpl.java
  src/main/java/com/czertainly/core/api/web/RAProfileManagementControllerImpl.java
  src/main/java/com/czertainly/core/auth/AuthEndpoint.java
  src/main/java/com/czertainly/core/auth/ResourceListener.java
  src/main/java/com/czertainly/core/dao/entity/AttributeContent2Object.java
  src/main/java/com/czertainly/core/dao/entity/AttributeDefinition.java
  src/main/java/com/czertainly/core/dao/entity/AttributeRelation.java
  src/main/java/com/czertainly/core/dao/entity/CertificateLocation.java
  src/main/java/com/czertainly/core/dao/entity/DiscoveryHistory.java
  src/main/java/com/czertainly/core/dao/entity/Location.java
  src/main/java/com/czertainly/core/dao/repository/AttributeContent2ObjectRepository.java
  src/main/java/com/czertainly/core/dao/repository/AttributeDefinitionRepository.java
  src/main/java/com/czertainly/core/dao/repository/AttributeRelationRepository.java
  src/main/java/com/czertainly/core/dao/repository/SecurityFilterRepository.java
  src/main/java/com/czertainly/core/dao/repository/SecurityFilterRepositoryImpl.java
  src/main/java/com/czertainly/core/model/auth/Resource.java
  src/main/java/com/czertainly/core/model/auth/SyncRequestDto.java
  src/main/java/com/czertainly/core/security/authz/ExternalAuthorization.java
  src/main/java/com/czertainly/core/security/authz/ExternalMethodAuthorizationVoter.java
  src/main/java/com/czertainly/core/security/authz/ObjectFilterAspect.java
  src/main/java/com/czertainly/core/service/AttributeService.java
  src/main/java/com/czertainly/core/service/MetadataService.java
  src/main/java/com/czertainly/core/service/impl/AcmeAccountServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/AcmeProfileServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/AttributeServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/AuditLogServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/AuthorityInstanceServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/CertificateServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/ClientOperationServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/ComplianceProfileServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/ComplianceServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/ConnectorServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/CredentialServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/DiscoveryServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/EntityInstanceServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/GroupServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/LocationServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/MetadataServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/RaProfileServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/RoleManagementServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/UserManagementServiceImpl.java
  src/main/java/com/czertainly/core/service/v2/impl/ClientOperationServiceImpl.java
  src/main/java/com/czertainly/core/util/DatabaseMigration.java
  src/main/java/com/czertainly/core/util/converter/FunctionGroupCodeConverter.java
  src/main/java/com/czertainly/core/util/converter/ResourceCodeConverter.java
  src/main/java/db/migration/V202211141030__AttributeV2TablesAndMigration.java
  src/test/java/com/czertainly/core/config/OpaSecuredAnnotationMetadataExtractorTest.java
  src/test/java/com/czertainly/core/service/CustomAttributeServiceTest.java
  src/test/java/com/czertainly/core/util/DatabaseMigrationTest.java
Labels: enhancement
