Repository CZERTAINLY/CZERTAINLY-Core, pull requests merged in 2022-07, with the labels that each got.

#103 Add kind and Name to the DTO for update authority instance
  src/main/java/com/czertainly/core/service/impl/AuthorityInstanceServiceImpl.java
Labels: bug

#106 Fix attribute handling for ACME Profile Update
  src/main/java/com/czertainly/core/service/impl/AcmeProfileServiceImpl.java
Labels: bug

#115 Add support for configuration of proxy
  README.md
  entry.sh
Labels: enhancement

#116 Throw validation exception when the connector to the authority is not available
  src/main/java/com/czertainly/core/service/v2/impl/ExtendedAttributeServiceImpl.java
Labels: bug

#118 Update discovery service implementation log messages
  src/main/java/com/czertainly/core/service/impl/DiscoveryServiceImpl.java
Labels: enhancement, ignore-for-release

#119 fix detected SonarQube bugs
  src/main/java/com/czertainly/core/api/acme/AcmeControllerImpl.java
  src/main/java/com/czertainly/core/api/acme/AcmeRaProfileControllerImpl.java
  src/main/java/com/czertainly/core/service/impl/ComplianceProfileServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/CredentialServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/LocationServiceImpl.java
  src/main/java/com/czertainly/core/util/DatabaseMigration.java
Labels: bug, ignore-for-release

#120 Update maven version and release.yml
  .github/release.yml
  README.md
  pom.xml
Labels: ignore-for-release

#123 Fix inconsistency bugs in core
  src/main/java/com/czertainly/core/api/web/CertificateControllerImpl.java
  src/main/java/com/czertainly/core/service/impl/ConnectorServiceImpl.java
  src/main/java/com/czertainly/core/service/v2/impl/ClientOperationServiceImpl.java
Labels: bug, ignore-for-release

#125 Update Core to return consistent response for bulk operations
  pom.xml
  src/main/java/com/czertainly/core/api/web/AcmeProfileControllerImpl.java
  src/main/java/com/czertainly/core/api/web/AuthorityInstanceControllerImpl.java
  src/main/java/com/czertainly/core/api/web/ClientManagementControllerImpl.java
  src/main/java/com/czertainly/core/api/web/ComplianceProfileControllerImpl.java
  src/main/java/com/czertainly/core/api/web/ConnectorControllerImpl.java
  src/main/java/com/czertainly/core/api/web/CredentialControllerImpl.java
  src/main/java/com/czertainly/core/dao/entity/Certificate.java
  src/main/java/com/czertainly/core/service/AcmeProfileService.java
  src/main/java/com/czertainly/core/service/AuthorityInstanceService.java
  src/main/java/com/czertainly/core/service/CertificateService.java
  src/main/java/com/czertainly/core/service/ClientService.java
  src/main/java/com/czertainly/core/service/ComplianceProfileService.java
  src/main/java/com/czertainly/core/service/ConnectorService.java
  src/main/java/com/czertainly/core/service/CoreCallbackService.java
  src/main/java/com/czertainly/core/service/CredentialService.java
  src/main/java/com/czertainly/core/service/acme/impl/AcmeRaProfileServiceImpl.java
  src/main/java/com/czertainly/core/service/acme/impl/AcmeServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/AcmeAccountServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/AcmeProfileServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/AdminServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/AuthorityInstanceServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/CertificateServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/ClientServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/ComplianceProfileServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/ConnectorServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/CredentialServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/DiscoveryServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/GroupServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/RaProfileServiceImpl.java
  src/main/java/com/czertainly/core/util/AcmeRandomGeneratorAndValidator.java
  src/test/java/com/czertainly/core/service/ComplianceServiceTest.java
  src/test/java/com/czertainly/core/service/CoreCallbackServiceTest.java
Labels: enhancement
