Repository CZERTAINLY/CZERTAINLY-Core, pull requests merged in 2022-10, with the labels that each got.

#160 Access Control Users Migration
  src/main/java/com/czertainly/core/api/acme/AcmeControllerImpl.java
  src/main/java/com/czertainly/core/api/acme/AcmeRaProfileControllerImpl.java
  src/main/java/com/czertainly/core/api/local/LocalControllerImpl.java
  src/main/java/com/czertainly/core/api/v2/client/ClientOperationControllerImpl.java
  src/main/java/com/czertainly/core/api/web/AdminManagementControllerImpl.java
  src/main/java/com/czertainly/core/api/web/ClientManagementControllerImpl.java
  src/main/java/com/czertainly/core/api/web/RAProfileManagementControllerImpl.java
  src/main/java/com/czertainly/core/api/web/RoleManagementControllerImpl.java
  src/main/java/com/czertainly/core/api/web/UserManagementControllerImpl.java
  src/main/java/com/czertainly/core/dao/entity/Admin.java
  src/main/java/com/czertainly/core/dao/entity/Certificate.java
  src/main/java/com/czertainly/core/dao/entity/Client.java
  src/main/java/com/czertainly/core/dao/entity/RaProfile.java
  src/main/java/com/czertainly/core/dao/repository/AdminRepository.java
  src/main/java/com/czertainly/core/dao/repository/CertificateRepository.java
  src/main/java/com/czertainly/core/dao/repository/ClientRepository.java
  src/main/java/com/czertainly/core/security/authn/client/ResourceApiClient.java
  src/main/java/com/czertainly/core/security/authn/client/UserManagementApiClient.java
  src/main/java/com/czertainly/core/service/AdminService.java
  src/main/java/com/czertainly/core/service/CertificateService.java
  src/main/java/com/czertainly/core/service/ClientService.java
  src/main/java/com/czertainly/core/service/LocalAdminService.java
  src/main/java/com/czertainly/core/service/RaProfileService.java
  src/main/java/com/czertainly/core/service/RoleManagementService.java
  src/main/java/com/czertainly/core/service/UserManagementService.java
  src/main/java/com/czertainly/core/service/impl/AdminServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/CertificateServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/ClientServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/LocalAdminServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/RaProfileServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/RoleManagementServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/SearchServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/StatisticsServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/UserManagementServiceImpl.java
  src/main/java/com/czertainly/core/util/DatabaseMigration.java
  src/main/java/db/migration/V202209211100__Access_Control.java
  src/test/java/com/czertainly/core/aop/AuditLogAspectTest.java
  src/test/java/com/czertainly/core/service/AcmeAccountServiceTest.java
  src/test/java/com/czertainly/core/service/AcmeRaProfileServiceTest.java
  src/test/java/com/czertainly/core/service/AcmeServiceTest.java
  src/test/java/com/czertainly/core/service/AdminServiceTest.java
  src/test/java/com/czertainly/core/service/ClientOperationServiceV1Test.java
  src/test/java/com/czertainly/core/service/ClientOperationServiceV2Test.java
  src/test/java/com/czertainly/core/service/ClientServiceTest.java
  src/test/java/com/czertainly/core/service/LocalAdminServiceTest.java
  src/test/java/com/czertainly/core/service/RaProfileServiceTest.java
  src/test/java/com/czertainly/core/util/DatabaseMigrationTest.java
Labels: enhancement

#161 Fix migration seeding of Acme Account
  src/main/java/com/czertainly/core/util/DatabaseMigration.java
  src/main/java/db/migration/V202209211100__Access_Control.java
Labels: bug, ignore-for-release

#163 Improve handling of error responses from Auth Service
  src/main/java/com/czertainly/core/api/ExceptionHandlingAdvice.java
  src/main/java/com/czertainly/core/config/SecurityConfig.java
  src/main/java/com/czertainly/core/security/authn/client/CzertainlyBaseAuthenticationClient.java
  src/main/java/com/czertainly/core/security/exception/AuthenticationServiceException.java
  src/main/java/com/czertainly/core/service/impl/CertificateServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/UserManagementServiceImpl.java
  src/test/java/com/czertainly/core/security/authn/client/CzertainlyAuthenticationClientTest.java
Labels: enhancement

#167 Access Denied Exception Custom Message
  src/main/java/com/czertainly/core/api/ExceptionHandlingAdvice.java
  src/main/java/com/czertainly/core/security/authz/ExternalMethodAuthorizationVoter.java
  src/main/java/com/czertainly/core/security/authz/SecuredUUID.java
  src/main/java/com/czertainly/core/util/BeautificationUtil.java
Labels: enhancement

#171 Type Reference fix for update user roles
  src/main/java/com/czertainly/core/api/ExceptionHandlingAdvice.java
  src/main/java/com/czertainly/core/security/authn/client/UserManagementApiClient.java
Labels: bug

#172 Authorization annotations of services methods for Access Control
  src/main/java/com/czertainly/core/api/web/AcmeAccountControllerImpl.java
  src/main/java/com/czertainly/core/api/web/ComplianceProfileControllerImpl.java
  src/main/java/com/czertainly/core/api/web/LocationManagementControllerImpl.java
  src/main/java/com/czertainly/core/api/web/RAProfileManagementControllerImpl.java
  src/main/java/com/czertainly/core/api/web/RoleManagementControllerImpl.java
  src/main/java/com/czertainly/core/api/web/UserManagementControllerImpl.java
  src/main/java/com/czertainly/core/dao/entity/UniquelyIdentifiedAndAudited.java
  src/main/java/com/czertainly/core/service/AcmeAccountService.java
  src/main/java/com/czertainly/core/service/ComplianceProfileService.java
  src/main/java/com/czertainly/core/service/ConnectorService.java
  src/main/java/com/czertainly/core/service/LocationService.java
  src/main/java/com/czertainly/core/service/RaProfileService.java
  src/main/java/com/czertainly/core/service/impl/AcmeAccountServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/AcmeProfileServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/AuditLogServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/AuthorityInstanceServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/CallbackServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/CertValidationServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/CertificateServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/ComplianceProfileServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/ComplianceServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/ConnectorRegistrationServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/ConnectorServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/CoreCallbackServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/CredentialServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/DiscoveryServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/EntityInstanceServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/LocationServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/RaProfileServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/RoleManagementServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/UserManagementServiceImpl.java
  src/main/java/com/czertainly/core/service/v2/impl/ClientOperationServiceImpl.java
  src/test/java/com/czertainly/core/service/AcmeAccountServiceTest.java
  src/test/java/com/czertainly/core/service/ComplianceProfileServiceTest.java
  src/test/java/com/czertainly/core/service/LocationServiceTest.java
  src/test/java/com/czertainly/core/service/RaProfileServiceTest.java
Labels: enhancement

#177 Secure listing methods of resources with parent resource check
  src/main/java/com/czertainly/core/api/v2/client/ClientOperationControllerImpl.java
  src/main/java/com/czertainly/core/api/web/CertificateControllerImpl.java
  src/main/java/com/czertainly/core/api/web/RoleManagementControllerImpl.java
  src/main/java/com/czertainly/core/api/web/UserManagementControllerImpl.java
  src/main/java/com/czertainly/core/config/AcmeValidationFilter.java
  src/main/java/com/czertainly/core/dao/repository/SecurityFilterRepository.java
  src/main/java/com/czertainly/core/dao/repository/SecurityFilterRepositoryImpl.java
  src/main/java/com/czertainly/core/model/auth/Resource.java
  src/main/java/com/czertainly/core/model/auth/ResourceAction.java
  src/main/java/com/czertainly/core/service/CertificateService.java
  src/main/java/com/czertainly/core/service/ConnectorService.java
  src/main/java/com/czertainly/core/service/SearchService.java
  src/main/java/com/czertainly/core/service/impl/AcmeAccountServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/CertificateServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/ConnectorRegistrationServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/LocationServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/RaProfileServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/SearchServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/UserManagementServiceImpl.java
  src/test/java/com/czertainly/core/service/CertificateServiceTest.java
Labels: enhancement

#178 Statistics API Updates to reflect access control changes for user
  src/main/java/com/czertainly/core/dao/repository/CertificateRepository.java
  src/main/java/com/czertainly/core/service/CertificateService.java
  src/main/java/com/czertainly/core/service/DiscoveryService.java
  src/main/java/com/czertainly/core/service/GroupService.java
  src/main/java/com/czertainly/core/service/RaProfileService.java
  src/main/java/com/czertainly/core/service/impl/CertificateServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/DiscoveryServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/GroupServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/RaProfileServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/StatisticsServiceImpl.java
  src/test/java/com/czertainly/core/service/CertValidationServiceTest.java
  src/test/java/com/czertainly/core/service/ComplianceProfileServiceTest.java
  src/test/java/com/czertainly/core/service/ConnectorAuthServiceTest.java
  src/test/java/com/czertainly/core/service/CoreCallbackServiceTest.java
  src/test/java/com/czertainly/core/service/StatisticsServiceTest.java
Labels: enhancement

#179 Fix Access control migration and user profile to reflect changes in Auth service
  src/main/java/com/czertainly/core/api/web/AcmeAccountControllerImpl.java
  src/main/java/com/czertainly/core/security/authn/client/CzertainlyAuthenticationClient.java
  src/main/java/com/czertainly/core/service/impl/AuthServiceImpl.java
  src/main/java/com/czertainly/core/util/DatabaseMigration.java
  src/main/java/db/migration/V202209211100__Access_Control.java
Labels: bug

#180 Fix bugs in implementation of Access Control and change of API routes
  src/main/java/com/czertainly/core/api/web/AuthControllerImpl.java
  src/main/java/com/czertainly/core/api/web/RAProfileManagementControllerImpl.java
  src/main/java/com/czertainly/core/api/web/RoleManagementControllerImpl.java
  src/main/java/com/czertainly/core/dao/repository/SecurityFilterRepositoryImpl.java
  src/main/java/com/czertainly/core/security/authn/client/RoleManagementApiClient.java
  src/main/java/com/czertainly/core/service/AuthService.java
  src/main/java/com/czertainly/core/service/RoleManagementService.java
  src/main/java/com/czertainly/core/service/UserManagementService.java
  src/main/java/com/czertainly/core/service/impl/AuthServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/LocationServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/RoleManagementServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/UserManagementServiceImpl.java
Labels: enhancement

#181 Access Control Fixes - User description, exceptions handling and foreign keys handling
  src/main/java/com/czertainly/core/api/ExceptionHandlingAdvice.java
  src/main/java/com/czertainly/core/dao/entity/AuthorityInstanceReference.java
  src/main/java/com/czertainly/core/dao/entity/Certificate.java
  src/main/java/com/czertainly/core/dao/entity/ComplianceProfileRule.java
  src/main/java/com/czertainly/core/dao/entity/ComplianceRule.java
  src/main/java/com/czertainly/core/dao/entity/EntityInstanceReference.java
  src/main/java/com/czertainly/core/dao/entity/Location.java
  src/main/java/com/czertainly/core/dao/entity/RaProfile.java
  src/main/java/com/czertainly/core/dao/entity/acme/AcmeProfile.java
  src/main/java/com/czertainly/core/service/impl/AuthorityInstanceServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/LocalAdminServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/UserManagementServiceImpl.java
Labels: bug, ignore-for-release

#183 Add Compliance Rule as response for add and remove rule
  src/main/java/com/czertainly/core/api/web/ComplianceProfileControllerImpl.java
  src/main/java/com/czertainly/core/dao/entity/ComplianceProfile.java
  src/main/java/com/czertainly/core/dao/entity/ComplianceProfileRule.java
  src/main/java/com/czertainly/core/service/ComplianceProfileService.java
  src/main/java/com/czertainly/core/service/impl/ComplianceProfileServiceImpl.java
  src/test/java/com/czertainly/core/service/ComplianceProfileServiceTest.java
Labels: enhancement

#184 Update compliance to check for rule in profile and common
  src/main/java/com/czertainly/core/service/impl/CertificateServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/ComplianceServiceImpl.java
Labels: bug

#185 Update renewal and issue certificate to location logic
  src/main/java/com/czertainly/core/api/web/LocationManagementControllerImpl.java
  src/main/java/com/czertainly/core/service/LocationService.java
  src/main/java/com/czertainly/core/service/impl/LocationServiceImpl.java
Labels: enhancement

#187 Add orderBy to Criteria Builder for Certificate listing
  src/main/java/com/czertainly/core/dao/repository/SecurityFilterRepository.java
  src/main/java/com/czertainly/core/dao/repository/SecurityFilterRepositoryImpl.java
  src/main/java/com/czertainly/core/service/impl/CertificateServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/SearchServiceImpl.java
Labels: enhancement

#188 Fix Access Control Migration to reflect changes in design and Auth service
  src/main/java/com/czertainly/core/util/DatabaseMigration.java
  src/main/java/db/migration/V202209211100__Access_Control.java
Labels: bug, enhancement

#190 Minor Fixes regarding certificates
  src/main/java/com/czertainly/core/api/web/LocationManagementControllerImpl.java
  src/main/java/com/czertainly/core/service/CertificateService.java
  src/main/java/com/czertainly/core/service/ClientOperationService.java
  src/main/java/com/czertainly/core/service/LocationService.java
  src/main/java/com/czertainly/core/service/impl/CertificateServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/ClientOperationServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/LocationServiceImpl.java
  src/main/java/com/czertainly/core/service/v2/impl/ClientOperationServiceImpl.java
Labels: bug, ignore-for-release

#191 Add Private Key Flag when pushing the certificate to a location
  src/main/java/com/czertainly/core/service/impl/LocationServiceImpl.java
Labels: enhancement, ignore-for-release

#192 Fix update entity payload to entity provider
  src/main/java/com/czertainly/core/service/impl/EntityInstanceServiceImpl.java
Labels: bug

#193 Remove old certificate reference after renewal in location
  src/main/java/com/czertainly/core/api/web/LocationManagementControllerImpl.java
  src/main/java/com/czertainly/core/service/LocationService.java
  src/main/java/com/czertainly/core/service/impl/LocationServiceImpl.java
Labels: bug

#195 Release/2.5.0
  LICENSE.md
  README.md
  pom.xml
Labels: ignore-for-release

#197 Fix creation of local administrator users
  pom.xml
  src/main/java/com/czertainly/core/service/impl/LocalAdminServiceImpl.java
Labels: bug

#199 Include JAVA_OPTS in entrypoint for docker container
  README.md
  docker/opt/czertainly/entry.sh
Labels: enhancement
