Repository CZERTAINLY/CZERTAINLY-Core, pull requests merged in 2023-04, with the labels that each got.

#358 Replace DB engine in test environment for one that supports JSONB columns
  Dockerfile
  Dockerfile-pre
  build_image_locally
  hooks/build
  pom.xml
  src/test/java/com/czertainly/core/repository/ConnectorRepositoryTest.java
  src/test/resources/application.properties
Labels: enhancement, ignore-for-release

#361 Add search filters for discoveries inventory with support for pagination
  src/main/java/com/czertainly/core/api/web/DiscoveryControllerImpl.java
  src/main/java/com/czertainly/core/enums/SearchFieldNameEnum.java
  src/main/java/com/czertainly/core/enums/SearchFieldTypeEnum.java
  src/main/java/com/czertainly/core/service/DiscoveryService.java
  src/main/java/com/czertainly/core/service/impl/DiscoveryServiceImpl.java
  src/main/java/com/czertainly/core/util/converter/Sql2PredicateConverter.java
  src/test/java/com/czertainly/core/search/DiscoveryHistorySearchTest.java
  src/test/java/com/czertainly/core/search/SearchFilterRequestDtoDummy.java
  src/test/java/com/czertainly/core/service/DiscoveryServiceTest.java
  src/test/java/com/czertainly/core/util/converter/Sql2PredicateConverterTest.java
Labels: enhancement

#364 Add search filters for entities and locations inventory with support for pagination
  pom.xml
  src/main/java/com/czertainly/core/api/web/EntityInstanceControllerImpl.java
  src/main/java/com/czertainly/core/api/web/LocationManagementControllerImpl.java
  src/main/java/com/czertainly/core/dao/repository/EntityInstanceReferenceRepository.java
  src/main/java/com/czertainly/core/dao/repository/LocationRepository.java
  src/main/java/com/czertainly/core/enums/SearchFieldNameEnum.java
  src/main/java/com/czertainly/core/model/SearchFieldObject.java
  src/main/java/com/czertainly/core/service/EntityInstanceService.java
  src/main/java/com/czertainly/core/service/LocationService.java
  src/main/java/com/czertainly/core/service/impl/CertificateServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/EntityInstanceServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/LocationServiceImpl.java
  src/main/java/com/czertainly/core/util/converter/Sql2PredicateConverter.java
  src/test/java/com/czertainly/core/search/EntityInstanceSearchTest.java
  src/test/java/com/czertainly/core/search/LocationsSearchTest.java
  src/test/java/com/czertainly/core/service/EntityInstanceServiceTest.java
  src/test/java/com/czertainly/core/service/LocationServiceTest.java
Labels: enhancement

#366 Small fixes in discoveries and entities search
  src/main/java/com/czertainly/core/dao/repository/DiscoveryRepository.java
  src/main/java/com/czertainly/core/enums/SearchFieldNameEnum.java
  src/main/java/com/czertainly/core/service/impl/DiscoveryServiceImpl.java
Labels: bug, ignore-for-release

#368 Fix Docker building process
  Dockerfile
  hooks/build
Labels: bug, ignore-for-release

#370 Fix no audit logs listing response
  src/main/java/com/czertainly/core/service/impl/AuditLogServiceImpl.java
Labels: bug, ignore-for-release

#372 Update release version to 2.7.1
  pom.xml
Labels: ignore-for-release

#373 Configure Rabbit MQ and use it to propagate certificate status events
  pom.xml
  src/main/java/com/czertainly/core/messaging/configuration/RabbitMQConfiguration.java
  src/main/java/com/czertainly/core/messaging/configuration/RabbitMQConstants.java
  src/main/java/com/czertainly/core/messaging/listeners/EventListener.java
  src/main/java/com/czertainly/core/messaging/listeners/NotificationListener.java
  src/main/java/com/czertainly/core/messaging/model/EventMessage.java
  src/main/java/com/czertainly/core/messaging/model/NotificationMessage.java
  src/main/java/com/czertainly/core/messaging/model/enums/EventTypeEnum.java
  src/main/java/com/czertainly/core/messaging/model/enums/ResourceTypeEnum.java
  src/main/java/com/czertainly/core/messaging/model/enums/ServiceEnum.java
  src/main/java/com/czertainly/core/messaging/producers/EventProducer.java
  src/main/java/com/czertainly/core/messaging/producers/NotificationProducer.java
  src/main/java/com/czertainly/core/service/impl/CertificateServiceImpl.java
  src/main/resources/application.properties
Labels: ignore-for-release

#375 Refactor and unite structure of platform enums
  src/main/java/com/czertainly/core/api/web/CertificateControllerImpl.java
  src/main/java/com/czertainly/core/api/web/EnumControllerImpl.java
  src/main/java/com/czertainly/core/api/web/SettingControllerImpl.java
  src/main/java/com/czertainly/core/dao/entity/CryptographicKeyItem.java
  src/main/java/com/czertainly/core/dao/entity/Setting.java
  src/main/java/com/czertainly/core/dao/entity/TokenProfile.java
  src/main/java/com/czertainly/core/dao/repository/SettingRepository.java
  src/main/java/com/czertainly/core/service/CertificateService.java
  src/main/java/com/czertainly/core/service/EnumService.java
  src/main/java/com/czertainly/core/service/impl/CertificateServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/CryptographicKeyServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/CryptographicOperationServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/DiscoveryServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/EntityInstanceServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/EnumServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/LocationServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/SettingServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/UserManagementServiceImpl.java
  src/main/java/com/czertainly/core/util/CertificateUtil.java
  src/main/java/com/czertainly/core/util/SearchHelper.java
  src/main/java/com/czertainly/core/util/converter/SectionCodeConverter.java
  src/main/java/com/czertainly/core/util/converter/SettingsSectionCodeConverter.java
  src/main/java/com/czertainly/core/util/converter/Sql2PredicateConverter.java
  src/test/java/com/czertainly/core/search/DiscoveryHistorySearchTest.java
  src/test/java/com/czertainly/core/search/EntityInstanceSearchTest.java
  src/test/java/com/czertainly/core/search/LocationsSearchTest.java
  src/test/java/com/czertainly/core/search/SearchFilterRequestDtoDummy.java
  src/test/java/com/czertainly/core/service/CertificateServiceTest.java
  src/test/java/com/czertainly/core/service/CryptographicKeyServiceTest.java
  src/test/java/com/czertainly/core/util/converter/Sql2PredicateConverterTest.java
Labels: enhancement

#376 Reset class variable before CA Certificate chain
  src/main/java/com/czertainly/core/service/scep/impl/ExtendedScepHelperServiceImpl.java
Labels: ignore-for-release
