Repository CZERTAINLY/CZERTAINLY-Core, pull requests merged in 2023-02, with the labels that each got.

#275 Update cryptography key related operation with key items management
  src/main/java/com/czertainly/core/api/web/CryptographicKeyControllerImpl.java
  src/main/java/com/czertainly/core/dao/entity/Certificate.java
  src/main/java/com/czertainly/core/dao/entity/CryptographicKey.java
  src/main/java/com/czertainly/core/dao/entity/CryptographicKeyItem.java
  src/main/java/com/czertainly/core/dao/repository/CertificateRepository.java
  src/main/java/com/czertainly/core/dao/repository/CryptographicKeyItemRepository.java
  src/main/java/com/czertainly/core/dao/repository/SecurityFilterRepositoryImpl.java
  src/main/java/com/czertainly/core/service/CertificateService.java
  src/main/java/com/czertainly/core/service/CryptographicKeyService.java
  src/main/java/com/czertainly/core/service/impl/CertificateServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/CryptographicKeyServiceImpl.java
  src/main/java/com/czertainly/core/util/CertificateUtil.java
  src/main/java/com/czertainly/core/util/DatabaseMigration.java
  src/main/java/db/migration/V202301311500__PublicKeyMigration.java
  src/main/resources/db/migration/V202228121130__cryptoraphic_provider.sql
  src/test/java/com/czertainly/core/service/CryptographicKeyServiceTest.java
  src/test/java/com/czertainly/core/util/DatabaseMigrationTest.java
Labels: enhancement

#277 Renewal and Rekey Implementation
  src/main/java/com/czertainly/core/api/v2/client/ClientOperationControllerImpl.java
  src/main/java/com/czertainly/core/dao/entity/Certificate.java
  src/main/java/com/czertainly/core/service/impl/CryptographicKeyServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/MetadataServiceImpl.java
  src/main/java/com/czertainly/core/service/v2/ClientOperationService.java
  src/main/java/com/czertainly/core/service/v2/impl/ClientOperationServiceImpl.java
  src/test/java/com/czertainly/core/service/ClientOperationServiceV2Test.java
Labels: enhancement

#279 Load trusted certificates at runtime
  docker/opt/czertainly/entry.sh
  src/main/java/com/czertainly/core/config/TrustedCertificatesConfig.java
Labels: enhancement

#280 Fix custom attribute validation for ACME
  src/main/java/com/czertainly/core/api/web/CryptographicKeyControllerImpl.java
  src/main/java/com/czertainly/core/dao/entity/AttributeDefinition.java
  src/main/java/com/czertainly/core/dao/entity/Connector.java
  src/main/java/com/czertainly/core/dao/repository/AttributeContent2ObjectRepository.java
  src/main/java/com/czertainly/core/service/AttributeService.java
  src/main/java/com/czertainly/core/service/CryptographicKeyService.java
  src/main/java/com/czertainly/core/service/impl/AttributeServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/ConnectorServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/CryptographicKeyServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/CryptographicOperationServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/MetadataServiceImpl.java
  src/main/java/com/czertainly/core/service/v2/impl/ClientOperationServiceImpl.java
Labels: bug, enhancement

#281 Implement search on cryptographic keys
  src/main/java/com/czertainly/core/api/web/CryptographicKeyControllerImpl.java
  src/main/java/com/czertainly/core/dao/entity/CryptographicKeyItem.java
  src/main/java/com/czertainly/core/dao/repository/SecurityFilterRepository.java
  src/main/java/com/czertainly/core/dao/repository/SecurityFilterRepositoryImpl.java
  src/main/java/com/czertainly/core/service/CryptographicKeyService.java
  src/main/java/com/czertainly/core/service/impl/CryptographicKeyServiceImpl.java
  src/main/java/com/czertainly/core/util/RequestValidatorHelper.java
  src/main/java/com/czertainly/core/util/converter/Sql2PredicateConverter.java
  src/test/java/com/czertainly/core/service/CryptographicKeyServiceTest.java
Labels: enhancement

#283 Fix certificate search when Not Contains filter is used in combination with other filter
  src/main/java/com/czertainly/core/service/impl/SearchServiceImpl.java
Labels: bug

#284 Remove audit log from internal method
  src/main/java/com/czertainly/core/service/impl/CertificateServiceImpl.java
Labels: bug

#285 Support read-only file systems
  Dockerfile
  src/main/java/com/czertainly/core/config/EmbeddedServletContainerConfig.java
  src/main/resources/logback-spring.xml
Labels: enhancement

#286 Scheduled update of certificates status
  src/main/java/com/czertainly/core/aop/AuditLogAspect.java
  src/main/java/com/czertainly/core/dao/entity/Certificate.java
  src/main/java/com/czertainly/core/dao/repository/CertificateRepository.java
  src/main/java/com/czertainly/core/service/CertificateService.java
  src/main/java/com/czertainly/core/service/impl/CertValidationServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/CertificateServiceImpl.java
  src/main/java/com/czertainly/core/tasks/ScheduledLoggingFilter.java
  src/main/java/com/czertainly/core/tasks/ScheduledTasks.java
  src/main/java/com/czertainly/core/tasks/UpdateCertificateStatusTask.java
  src/main/resources/application.properties
  src/main/resources/logback-spring.xml
Labels: enhancement

#288 Fix Core issues and update key operations
  src/main/java/com/czertainly/core/Application.java
  src/main/java/com/czertainly/core/api/web/CryptographicKeyControllerImpl.java
  src/main/java/com/czertainly/core/dao/entity/CertificateContent.java
  src/main/java/com/czertainly/core/dao/entity/CryptographicKey.java
  src/main/java/com/czertainly/core/dao/entity/CryptographicKeyItem.java
  src/main/java/com/czertainly/core/dao/entity/TokenProfile.java
  src/main/java/com/czertainly/core/service/impl/CryptographicKeyServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/CryptographicOperationServiceImpl.java
  src/test/java/com/czertainly/core/service/CryptographicKeyServiceTest.java
Labels: bug, enhancement, ignore-for-release

#291 Update exception handling and logging advice
  src/main/java/com/czertainly/core/api/LoggingAdvice.java
  src/main/java/com/czertainly/core/dao/repository/SecurityFilterRepositoryImpl.java
  src/main/java/com/czertainly/core/service/impl/ComplianceProfileServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/ConnectorServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/CredentialServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/CryptographicKeyServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/CryptographicOperationServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/GroupServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/LocationServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/RaProfileServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/TokenProfileServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/UserManagementServiceImpl.java
Labels: enhancement

#290 Add more filter conditions to cryptography keys search and fix non functioning filters
  src/main/java/com/czertainly/core/service/impl/CryptographicKeyServiceImpl.java
  src/main/java/com/czertainly/core/util/converter/Sql2PredicateConverter.java
Labels: enhancement

#292 Fix core issues regarding certificates and keys
  src/main/java/com/czertainly/core/service/PermissionEvaluator.java
  src/main/java/com/czertainly/core/service/impl/AuthPermissionEvaluationServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/CertificateServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/CryptographicKeyServiceImpl.java
  src/test/java/com/czertainly/core/service/CryptographicKeyServiceTest.java
Labels: bug, ignore-for-release

#293 Fix registration of provider and comparison of public keys
  src/main/java/com/czertainly/core/config/ApplicationConfig.java
  src/main/java/com/czertainly/core/config/SecurityProviderConfig.java
  src/main/java/com/czertainly/core/service/v2/impl/ClientOperationServiceImpl.java
Labels: bug

#296 Fix key inventory filter when selected filter is not Key item property
  src/main/java/com/czertainly/core/util/converter/Sql2PredicateConverter.java
Labels: bug

#297 Split the DTOs of certificate list and details
  src/main/java/com/czertainly/core/api/web/CertificateControllerImpl.java
  src/main/java/com/czertainly/core/dao/entity/Certificate.java
  src/main/java/com/czertainly/core/service/CertificateService.java
  src/main/java/com/czertainly/core/service/MetadataService.java
  src/main/java/com/czertainly/core/service/impl/CertificateServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/MetadataServiceImpl.java
  src/main/java/com/czertainly/core/service/v2/impl/ClientOperationServiceImpl.java
  src/test/java/com/czertainly/core/service/CertificateServiceTest.java
Labels: enhancement

#298 Consolidate values for certificate Public Key and Signature Algorithm
  src/main/java/com/czertainly/core/dao/entity/Certificate.java
  src/main/java/com/czertainly/core/service/impl/CertificateServiceImpl.java
  src/main/java/com/czertainly/core/util/CertificateUtil.java
  src/main/resources/db/migration/V202302071415__rename_cert_algorithms.sql
Labels: enhancement, ignore-for-release

#300 Fix bugs detected by SonarQube
  src/main/java/com/czertainly/core/config/TrustedCertificatesConfig.java
  src/main/java/com/czertainly/core/service/impl/AttributeServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/CertificateServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/CryptographicKeyServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/DiscoveryServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/TokenProfileServiceImpl.java
  src/main/java/com/czertainly/core/util/converter/Sql2PredicateConverter.java
Labels: bug

#301 Add new endpoint for the certificate content download
  src/main/java/com/czertainly/core/api/web/CertificateControllerImpl.java
  src/main/java/com/czertainly/core/dao/entity/Certificate.java
  src/main/java/com/czertainly/core/service/CertificateService.java
  src/main/java/com/czertainly/core/service/impl/CertificateServiceImpl.java
  src/main/java/com/czertainly/core/service/v2/impl/ClientOperationServiceImpl.java
Labels: enhancement

#303 Load the key lazily for the certificate
  src/main/java/com/czertainly/core/dao/entity/Certificate.java
  src/main/java/com/czertainly/core/service/v2/impl/ClientOperationServiceImpl.java
Labels: bug

#304 Merge the compliance rule before generating response attributes
  src/main/java/com/czertainly/core/service/impl/CertificateServiceImpl.java
Labels: bug

#305 Fix sonar qube issues
  src/main/java/com/czertainly/core/config/TrustedCertificatesConfig.java
Labels: bug, ignore-for-release

#312 Fix ACME revoke certificate reason code handling
  src/main/java/com/czertainly/core/service/acme/impl/ExtendedAcmeHelperService.java
  src/test/java/com/czertainly/core/service/acme/impl/ExtendedAcmeHelperServiceTest.java
Labels: bug

#309 Update compliance check status on certificates when compliance profile updates
  src/main/java/com/czertainly/core/dao/repository/CertificateRepository.java
  src/main/java/com/czertainly/core/service/CertificateService.java
  src/main/java/com/czertainly/core/service/ComplianceService.java
  src/main/java/com/czertainly/core/service/impl/CertificateServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/ComplianceProfileServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/ComplianceServiceImpl.java
Labels: enhancement

#313 Rewrite certificates filtering with predicates based on cryptographic keys filtering
  pom.xml
  src/main/java/com/czertainly/core/service/impl/CertificateServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/SearchServiceImpl.java
  src/main/java/com/czertainly/core/util/converter/Sql2PredicateConverter.java
  src/test/java/com/czertainly/core/util/converter/Sql2PredicateConverterTest.java
Labels: enhancement

#314 Implement platform settings management service
  src/main/java/com/czertainly/core/api/web/SettingControllerImpl.java
  src/main/java/com/czertainly/core/dao/entity/Setting.java
  src/main/java/com/czertainly/core/dao/repository/SettingRepository.java
  src/main/java/com/czertainly/core/model/auth/Resource.java
  src/main/java/com/czertainly/core/service/SettingService.java
  src/main/java/com/czertainly/core/service/impl/CertValidationServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/SettingServiceImpl.java
  src/main/java/com/czertainly/core/util/SerializationUtil.java
  src/main/java/com/czertainly/core/util/converter/SectionCodeConverter.java
  src/main/resources/db/migration/V202302172125__settings.sql
  src/test/java/com/czertainly/core/service/SettingServiceTest.java
Labels: enhancement

#318 Implement support for delta view of discovery
  src/main/java/com/czertainly/core/api/web/DiscoveryControllerImpl.java
  src/main/java/com/czertainly/core/dao/entity/DiscoveryCertificate.java
  src/main/java/com/czertainly/core/dao/entity/DiscoveryHistory.java
  src/main/java/com/czertainly/core/dao/repository/CertificateRepository.java
  src/main/java/com/czertainly/core/dao/repository/DiscoveryCertificateRepository.java
  src/main/java/com/czertainly/core/service/DiscoveryService.java
  src/main/java/com/czertainly/core/service/impl/DiscoveryServiceImpl.java
  src/main/resources/db/migration/V202302231825__discovery_certificate_entry.sql
Labels: enhancement

#320 Enable springboot actuator for health monitoring
  pom.xml
  src/main/java/com/czertainly/core/auth/ResourceListener.java
  src/main/resources/application.properties
Labels: enhancement

#321 Add missing object access control for tokens and token profiles
  src/main/java/com/czertainly/core/api/web/TokenInstanceControllerImpl.java
  src/main/java/com/czertainly/core/api/web/TokenProfileControllerImpl.java
Labels: bug

#323 Fix global metadata uuid in the DTO
  src/main/java/com/czertainly/core/dao/entity/AttributeDefinition.java
  src/main/java/com/czertainly/core/service/impl/AttributeServiceImpl.java
  src/test/java/com/czertainly/core/service/GlobalMetadataServiceTest.java
Labels: bug, ignore-for-release

#324 Authenticate anonymous user by CzertainlyAuthenticationProvider
  src/main/java/com/czertainly/core/security/authn/CzertainlyAuthenticationProvider.java
  src/main/java/com/czertainly/core/security/authn/client/AuthenticationInfo.java
  src/main/java/com/czertainly/core/security/authn/client/CzertainlyAuthenticationClient.java
Labels: enhancement

#325 Simplify settings management
  src/main/java/com/czertainly/core/api/web/SettingControllerImpl.java
  src/main/java/com/czertainly/core/service/SettingService.java
  src/main/java/com/czertainly/core/service/impl/SettingServiceImpl.java
  src/test/java/com/czertainly/core/service/SettingServiceTest.java
Labels: enhancement, ignore-for-release
