Repository CZERTAINLY/CZERTAINLY-Core, pull requests merged in 2023-01, with the labels that each got.

#237 Set the certificate data as empty list
  src/main/java/com/czertainly/core/dao/entity/Location.java
Labels: bug

#240 Add Certificate UUID to the Discovery UUID
  src/main/java/com/czertainly/core/dao/entity/CertificateContent.java
  src/main/java/com/czertainly/core/dao/entity/DiscoveryCertificate.java
  src/main/java/com/czertainly/core/dao/entity/RaProfile.java
Labels: enhancement

#241 Save location entity before creating the metadata
  src/main/java/com/czertainly/core/service/impl/LocationServiceImpl.java
Labels: bug

#242 Add Additional Information to Certificate History Event and Improve Validation
  src/main/java/com/czertainly/core/api/web/CertificateControllerImpl.java
  src/main/java/com/czertainly/core/service/CertificateService.java
  src/main/java/com/czertainly/core/service/impl/CertValidationServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/CertificateServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/ClientOperationServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/DiscoveryServiceImpl.java
  src/main/java/com/czertainly/core/service/v2/impl/ClientOperationServiceImpl.java
  src/test/java/com/czertainly/core/service/CertificateServiceTest.java
Labels: enhancement

#249 Update path param name for the callback interface
  src/main/java/com/czertainly/core/api/web/CallbackControllerImpl.java
Labels: bug, ignore-for-release

#254 Integrate Certificate and Key Operations
  pom.xml
  src/main/java/com/czertainly/core/api/web/CertificateControllerImpl.java
  src/main/java/com/czertainly/core/attribute/CsrAttributes.java
  src/main/java/com/czertainly/core/attribute/EcdsaSignatureAttributes.java
  src/main/java/com/czertainly/core/attribute/RsaSignatureAttributes.java
  src/main/java/com/czertainly/core/config/ApplicationConfig.java
  src/main/java/com/czertainly/core/config/TokenContentSigner.java
  src/main/java/com/czertainly/core/config/logging/RequestResponseInterceptor.java
  src/main/java/com/czertainly/core/dao/entity/Certificate.java
  src/main/java/com/czertainly/core/dao/repository/CertificateRepository.java
  src/main/java/com/czertainly/core/model/auth/Resource.java
  src/main/java/com/czertainly/core/model/auth/ResourceAction.java
  src/main/java/com/czertainly/core/model/auth/ResourceSyncRequestDto.java
  src/main/java/com/czertainly/core/model/auth/SyncRequestDto.java
  src/main/java/com/czertainly/core/service/CertificateService.java
  src/main/java/com/czertainly/core/service/CryptographicOperationService.java
  src/main/java/com/czertainly/core/service/MetadataService.java
  src/main/java/com/czertainly/core/service/impl/CertificateServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/ConnectorServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/CryptographicKeyServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/CryptographicOperationServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/MetadataServiceImpl.java
  src/main/java/com/czertainly/core/service/v2/impl/ClientOperationServiceImpl.java
  src/main/java/com/czertainly/core/util/CryptographyUtil.java
  src/main/java/com/czertainly/core/util/CsrUtil.java
  src/main/java/com/czertainly/core/util/OcspUtil.java
  src/main/resources/db/migration/V202228121130__cryptoraphic_provider.sql
  src/test/java/com/czertainly/core/service/CryptographicOperationServiceTest.java
  src/test/java/com/czertainly/core/util/UriParamsBuilderTest.java
Labels: enhancement

#255 Add Cryptography mandatory end points to the endpoint table
  src/main/resources/db/migration/V202228121130__cryptoraphic_provider.sql
Labels: enhancement

#257 Add support for management of custom attribute individually per object
  src/main/java/com/czertainly/core/api/ExceptionHandlingAdvice.java
  src/main/java/com/czertainly/core/api/web/CustomAttributeControllerImpl.java
  src/main/java/com/czertainly/core/dao/repository/AttributeContent2ObjectRepository.java
  src/main/java/com/czertainly/core/dao/repository/AttributeContentRepository.java
  src/main/java/com/czertainly/core/service/AccessControlExtensionService.java
  src/main/java/com/czertainly/core/service/AcmeProfileService.java
  src/main/java/com/czertainly/core/service/AttributeService.java
  src/main/java/com/czertainly/core/service/AuthorityInstanceService.java
  src/main/java/com/czertainly/core/service/CertificateService.java
  src/main/java/com/czertainly/core/service/ComplianceProfileService.java
  src/main/java/com/czertainly/core/service/ConnectorService.java
  src/main/java/com/czertainly/core/service/CredentialService.java
  src/main/java/com/czertainly/core/service/CryptographicKeyService.java
  src/main/java/com/czertainly/core/service/EntityInstanceService.java
  src/main/java/com/czertainly/core/service/GroupService.java
  src/main/java/com/czertainly/core/service/LocationService.java
  src/main/java/com/czertainly/core/service/PermissionEvaluator.java
  src/main/java/com/czertainly/core/service/RaProfileService.java
  src/main/java/com/czertainly/core/service/ResourceExtensionService.java
  src/main/java/com/czertainly/core/service/ResourceService.java
  src/main/java/com/czertainly/core/service/RoleManagementService.java
  src/main/java/com/czertainly/core/service/TokenInstanceService.java
  src/main/java/com/czertainly/core/service/TokenProfileService.java
  src/main/java/com/czertainly/core/service/UserManagementService.java
  src/main/java/com/czertainly/core/service/impl/AcmeProfileServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/AttributeServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/AuthPermissionEvaluationServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/AuthorityInstanceServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/CertificateServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/ComplianceProfileServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/ConnectorServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/CredentialServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/CryptographicKeyServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/EntityInstanceServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/GroupServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/LocationServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/RaProfileServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/ResourceServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/RoleManagementServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/TokenInstanceServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/TokenProfileServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/UserManagementServiceImpl.java
  src/test/java/com/czertainly/core/service/CustomAttributeServiceTest.java
Labels: enhancement

#258 PQC Support and Certificate Details Fixes
  src/main/java/com/czertainly/core/dao/entity/Certificate.java
  src/main/java/com/czertainly/core/service/impl/CertValidationServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/CertificateServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/DiscoveryServiceImpl.java
  src/main/java/com/czertainly/core/util/CertificateUtil.java
  src/main/java/com/czertainly/core/util/KeySizeUtil.java
Labels: enhancement

#259 Fix custom attribute deletion of old content before updating
  src/main/java/com/czertainly/core/service/impl/AttributeServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/CertValidationServiceImpl.java
Labels: bug

#260 Fix PQC Key Sizes and Dilithium Certificate Management
  src/main/java/com/czertainly/core/dao/entity/Certificate.java
  src/main/java/com/czertainly/core/util/CertificateUtil.java
  src/main/java/com/czertainly/core/util/KeySizeUtil.java
  src/test/java/com/czertainly/core/service/CryptographicKeyServiceTest.java
Labels: bug

#262 Add Kind to Token and Token Details DTO
  src/main/java/com/czertainly/core/dao/entity/TokenInstanceReference.java
  src/main/java/com/czertainly/core/service/impl/TokenInstanceServiceImpl.java
Labels: enhancement

#263 Add JsonBackReference to the Cryptographic Key
  src/main/java/com/czertainly/core/dao/entity/CryptographicKey.java
Labels: bug

#265 Optimize dashboard statistics queries #251
  src/main/java/com/czertainly/core/dao/entity/Certificate.java
  src/main/resources/db/migration/V202301252000__indexes.sql
Labels: enhancement

#268 Update cryptographic operation response and fix key details response
  src/main/java/com/czertainly/core/api/web/CryptographicOperationControllerImpl.java
  src/main/java/com/czertainly/core/dao/entity/Certificate.java
  src/main/java/com/czertainly/core/dao/entity/CryptographicKey.java
  src/main/java/com/czertainly/core/dao/entity/CryptographicKeyItem.java
  src/main/java/com/czertainly/core/service/CryptographicOperationService.java
  src/main/java/com/czertainly/core/service/impl/AuthorityInstanceServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/CertificateServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/CryptographicKeyServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/CryptographicOperationServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/TokenProfileServiceImpl.java
  src/test/java/com/czertainly/core/service/CryptographicOperationServiceTest.java
Labels: enhancement

#269 Fix certificate push and delete from location
  src/main/java/com/czertainly/core/service/AttributeService.java
  src/main/java/com/czertainly/core/service/impl/AttributeServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/LocationServiceImpl.java
Labels: bug

#270 Fix updating and deleting custom atttributes content for objects
  src/main/java/com/czertainly/core/dao/entity/CryptographicKeyItem.java
  src/main/java/com/czertainly/core/dao/repository/AttributeContent2ObjectRepository.java
  src/main/java/com/czertainly/core/dao/repository/AttributeContentRepository.java
  src/main/java/com/czertainly/core/service/DiscoveryService.java
  src/main/java/com/czertainly/core/service/impl/AttributeServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/CryptographicKeyServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/DiscoveryServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/ResourceServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/StatisticsServiceImpl.java
  src/test/java/com/czertainly/core/service/CustomAttributeServiceTest.java
Labels: bug, ignore-for-release

#272 Prevent updating content of read-only custom attribute
  src/main/java/com/czertainly/core/dao/repository/AttributeContent2ObjectRepository.java
  src/main/java/com/czertainly/core/service/impl/AttributeServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/CertificateServiceImpl.java
Labels: bug

#273 Fix of listing certificates with applied filters
  src/main/java/com/czertainly/core/service/impl/SearchServiceImpl.java
Labels: bug
