Repository CZERTAINLY/CZERTAINLY-Core, pull requests merged in 2023-11, with the labels that each got.

#593 Fix recursion when downloading certificate from URL specified in AIA extension
  src/main/java/com/czertainly/core/service/impl/CertificateServiceImpl.java
  src/test/java/com/czertainly/core/service/CertificateValidationTest.java
Labels: bug, ignore-for-release

#595 Change switching RA profile to be allowed only when certificate is identified by new authority
  src/main/java/com/czertainly/core/api/web/CertificateControllerImpl.java
  src/main/java/com/czertainly/core/dao/repository/AttributeContent2ObjectRepository.java
  src/main/java/com/czertainly/core/service/CertificateService.java
  src/main/java/com/czertainly/core/service/MetadataService.java
  src/main/java/com/czertainly/core/service/impl/CertificateServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/ClientOperationServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/MetadataServiceImpl.java
  src/test/java/com/czertainly/core/service/CertificateServiceTest.java
Labels: new-feature

#598 Fix parsing of uploaded certificate and handle unsupported format
  src/main/java/com/czertainly/core/service/impl/CertificateServiceImpl.java
  src/main/java/com/czertainly/core/util/CertificateUtil.java
Labels: bug

#601 Fix parsing certificate and certificate request SANs
  src/main/java/com/czertainly/core/util/CertificateUtil.java
Labels: bug

#606 Add missing listing of SCEP profiles for object level access control
  src/main/java/com/czertainly/core/service/impl/ResourceServiceImpl.java
Labels: bug

#605 Fix Issuer and Subject DN migration to handle erroneously serialized request content as BASE64 encoded PEM
  src/main/java/com/czertainly/core/util/DatabaseMigration.java
  src/main/java/db/migration/V202311071500__IssuerAndSubjectDnMigration.java
Labels: bug

#608 Fix migration to change certifiacate status to state to cover UNKNOWN state
  src/main/resources/db/migration/V202310131425__split_certificate_status.sql
Labels: bug, ignore-for-release

#607 Change owner of key to user reference
  src/main/java/com/czertainly/core/dao/entity/CryptographicKey.java
  src/main/java/com/czertainly/core/dao/entity/CryptographicKeyItem.java
  src/main/java/com/czertainly/core/dao/entity/acme/AcmeAccount.java
  src/main/java/com/czertainly/core/dao/entity/acme/AcmeProfile.java
  src/main/java/com/czertainly/core/dao/entity/scep/ScepProfile.java
  src/main/java/com/czertainly/core/service/impl/CryptographicKeyServiceImpl.java
  src/main/resources/db/migration/V202311221425__cryptographic_key_owner_uuid.sql
  src/test/java/com/czertainly/core/service/CryptographicKeyServiceTest.java
Labels: enhancement

#609 Fix ACME finalize order to reflect async issuance process
  src/main/java/com/czertainly/core/dao/entity/acme/AcmeOrder.java
  src/main/java/com/czertainly/core/service/acme/impl/AcmeRaProfileServiceImpl.java
  src/main/java/com/czertainly/core/service/acme/impl/AcmeServiceImpl.java
  src/main/java/com/czertainly/core/service/acme/impl/ExtendedAcmeHelperService.java
  src/test/java/com/czertainly/core/service/AcmeRaProfileServiceTest.java
  src/test/java/com/czertainly/core/service/AcmeServiceTest.java
Labels: bug

#611 Update release version to 2.10.0
  pom.xml
Labels: ignore-for-release

#600 Add an option to mark CA certificate as trusted
  pom.xml
  src/main/java/com/czertainly/core/dao/entity/Certificate.java
  src/main/java/com/czertainly/core/enums/SearchFieldNameEnum.java
  src/main/java/com/czertainly/core/service/impl/CertificateServiceImpl.java
  src/main/java/com/czertainly/core/util/CertificateUtil.java
  src/main/java/com/czertainly/core/validation/certificate/X509CertificateValidator.java
  src/main/resources/db/migration/V202311131230__trusted_ca_mark.sql
Labels: new-feature

#616 Remove duplicate event and notification producing when validating certificates by scheduled job
  src/main/java/com/czertainly/core/service/impl/CertificateServiceImpl.java
Labels: bug

#613 Format timestamp suffix of created scheduled discovery name
  src/main/java/com/czertainly/core/tasks/DiscoveryCertificateTask.java
Labels: enhancement
