Repository CZERTAINLY/CZERTAINLY-Core, pull requests merged in 2023-06, with the labels that each got.

#444 Fix Scep Role permissions migration
  src/main/java/com/czertainly/core/security/authn/client/ResourceApiClient.java
  src/main/java/com/czertainly/core/util/DatabaseMigration.java
  src/main/java/db/migration/V202303211718__Scep_Roles.java
Labels: bug, ignore-for-release

#442 Resolve SonarQube issues
  src/main/java/com/czertainly/core/security/authn/client/CzertainlyAuthenticationClient.java
  src/main/java/com/czertainly/core/service/impl/CryptographicKeyServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/MetadataServiceImpl.java
  src/main/java/com/czertainly/core/service/scep/impl/ScepServiceImpl.java
  src/main/java/com/czertainly/core/util/converter/Sql2PredicateConverter.java
Labels: bug, ignore-for-release

#448 Resolve SonarQube issues
  pom.xml
  src/main/java/com/czertainly/core/util/DatabaseMigration.java
  src/main/java/com/czertainly/core/util/converter/Sql2PredicateConverter.java
  src/main/java/db/migration/V202303211718__Scep_Roles.java
Labels: bug

#447 Fix Audit logs pagination to return total items count
  src/main/java/com/czertainly/core/dao/repository/AuditLogRepository.java
  src/main/java/com/czertainly/core/service/impl/AuditLogServiceImpl.java
  src/test/java/com/czertainly/core/service/AuditLogExportTest.java
Labels: bug

#454 Add configuration for scheduler service and RabbitMQ
  src/main/resources/application.properties
Labels: ignore-for-release

#455 Add email to group and implement assigning users to group
  src/main/java/com/czertainly/core/dao/entity/Group.java
  src/main/java/com/czertainly/core/service/impl/GroupServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/UserManagementServiceImpl.java
  src/main/resources/db/migration/V202306051111__rename_group.sql
Labels: enhancement

#457 Allow actuator health endpoint requests without authentication
  src/main/java/com/czertainly/core/config/SecurityConfig.java
  src/main/java/com/czertainly/core/security/authn/CzertainlyAuthenticationFilter.java
Labels: enhancement

#463 Add resource callback for locations
  src/main/java/com/czertainly/core/service/impl/CallbackServiceImpl.java
Labels: ignore-for-release

#470 Fix enable/disable operation to reflect result of operation in Scheduler service
  src/main/java/com/czertainly/core/api/web/DiscoveryControllerImpl.java
  src/main/java/com/czertainly/core/api/web/SchedulerControllerImpl.java
  src/main/java/com/czertainly/core/messaging/listeners/SchedulerListener.java
  src/main/java/com/czertainly/core/service/SchedulerService.java
  src/main/java/com/czertainly/core/service/impl/SchedulerServiceImpl.java
  src/main/java/com/czertainly/core/tasks/ScheduledTasks.java
  src/main/java/com/czertainly/core/tasks/SchedulerJobProcessor.java
Labels: bug, ignore-for-release

#472 Add primary keys to scheduled job tables and failed reason to job history
  src/main/java/com/czertainly/core/dao/entity/ScheduledJobHistory.java
  src/main/java/com/czertainly/core/messaging/listeners/SchedulerListener.java
  src/main/java/com/czertainly/core/model/ScheduledTaskResult.java
  src/main/java/com/czertainly/core/tasks/DiscoveryCertificateTask.java
  src/main/java/com/czertainly/core/tasks/SchedulerJobProcessor.java
  src/main/java/com/czertainly/core/tasks/UpdateCertificateStatusTask.java
  src/main/java/com/czertainly/core/tasks/UpdateIntuneRevocationRequestsTask.java
  src/main/resources/db/migration/V202306121100__scheduler_indexes.sql
Labels: enhancement, ignore-for-release

#473 Add error message and last execution status to scheduled job and its history
  pom.xml
  src/main/java/com/czertainly/core/api/web/SchedulerControllerImpl.java
  src/main/java/com/czertainly/core/dao/entity/ScheduledJob.java
  src/main/java/com/czertainly/core/dao/entity/ScheduledJobHistory.java
  src/main/java/com/czertainly/core/dao/repository/ScheduledJobHistoryRepository.java
  src/main/java/com/czertainly/core/service/SchedulerService.java
  src/main/java/com/czertainly/core/service/impl/SchedulerServiceImpl.java
  src/main/java/com/czertainly/core/tasks/SchedulerJobProcessor.java
  src/main/java/com/czertainly/core/util/converter/Sql2PredicateConverter.java
Labels: enhancement, ignore-for-release

#479 New user is created even when uploaded certificate is not valid
  src/main/java/com/czertainly/core/service/impl/LocalAdminServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/UserManagementServiceImpl.java
Labels: bug, ignore-for-release

#483 Add certificate property filter to search for certificates that have associated private key
  src/main/java/com/czertainly/core/enums/SearchFieldNameEnum.java
  src/main/java/com/czertainly/core/service/impl/CertificateServiceImpl.java
  src/main/java/com/czertainly/core/util/converter/Sql2PredicateConverter.java
  src/test/java/com/czertainly/core/util/converter/Sql2PredicateConverterTest.java
Labels: enhancement

#484 Link renewed/rekeyed certificate to its predecessor
  src/main/java/com/czertainly/core/dao/entity/Certificate.java
  src/main/java/com/czertainly/core/service/CertificateService.java
  src/main/java/com/czertainly/core/service/impl/CertificateServiceImpl.java
  src/main/java/com/czertainly/core/service/v2/impl/ClientOperationServiceImpl.java
  src/main/resources/db/migration/V202306231210__certificate_source_uuid.sql
Labels: enhancement

#486 Add issue and revoke attributes to certificate
  src/main/java/com/czertainly/core/dao/entity/Certificate.java
  src/main/java/com/czertainly/core/service/CertificateService.java
  src/main/java/com/czertainly/core/service/impl/CertificateServiceImpl.java
  src/main/java/com/czertainly/core/service/v2/impl/ClientOperationServiceImpl.java
  src/main/resources/db/migration/V202306261430__certificate_attributes.sql
  src/test/java/com/czertainly/core/service/ClientOperationServiceV2Test.java
Labels: enhancement

#487 Small changes in linking certificates produced by renew/rekey
  src/main/java/com/czertainly/core/dao/repository/CertificateRepository.java
  src/main/java/com/czertainly/core/service/impl/CertificateServiceImpl.java
  src/main/java/com/czertainly/core/service/v2/impl/ClientOperationServiceImpl.java
  src/main/resources/db/migration/V202306271140__certificate_source_uuid_fk.sql
Labels: enhancement, ignore-for-release

#493 Fix pagination of discovered certificates
  pom.xml
  src/main/java/com/czertainly/core/service/impl/DiscoveryServiceImpl.java
Labels: bug

#492 Fix discovery certificate pagination
  pom.xml
  src/main/java/com/czertainly/core/service/impl/DiscoveryServiceImpl.java
Labels: bug
