Repository CZERTAINLY/CZERTAINLY-Core, pull requests merged in 2023-03, with the labels that each got.

#332 Update properties names of search fields DTOs
  src/main/java/com/czertainly/core/service/impl/SearchServiceImpl.java
  src/main/java/com/czertainly/core/util/SearchHelper.java
Labels: ignore-for-release

#334 Change delete of global metadata to demote
  src/main/java/com/czertainly/core/api/web/GlobalMetadataControllerImpl.java
  src/main/java/com/czertainly/core/service/AttributeService.java
  src/main/java/com/czertainly/core/service/impl/AttributeServiceImpl.java
Labels: bug, ignore-for-release

#335 Change settings implementation to not use attributes
  src/main/java/com/czertainly/core/api/web/SettingControllerImpl.java
  src/main/java/com/czertainly/core/dao/entity/Setting.java
  src/main/java/com/czertainly/core/dao/repository/SettingRepository.java
  src/main/java/com/czertainly/core/service/SettingService.java
  src/main/java/com/czertainly/core/service/impl/SettingServiceImpl.java
  src/main/java/com/czertainly/core/util/converter/SectionCodeConverter.java
  src/main/resources/db/migration/V202302172125__settings.sql
  src/test/java/com/czertainly/core/service/SettingServiceTest.java
Labels: ignore-for-release

#338 Create CSR without issuing the certificate and support certificate with New status
  src/main/java/com/czertainly/core/api/web/CertificateControllerImpl.java
  src/main/java/com/czertainly/core/dao/entity/Certificate.java
  src/main/java/com/czertainly/core/dao/repository/CertificateRepository.java
  src/main/java/com/czertainly/core/service/CertificateService.java
  src/main/java/com/czertainly/core/service/impl/CertificateServiceImpl.java
  src/main/java/com/czertainly/core/service/v2/ClientOperationService.java
  src/main/java/com/czertainly/core/service/v2/impl/ClientOperationServiceImpl.java
  src/main/java/com/czertainly/core/util/CertificateUtil.java
  src/main/resources/db/migration/V202303200000__certificate_new_status.sql
  src/test/java/com/czertainly/core/service/CertValidationServiceTest.java
  src/test/java/com/czertainly/core/service/CertificateServiceTest.java
  src/test/java/com/czertainly/core/service/ClientOperationServiceV2Test.java
Labels: new-feature

#339 Fix validation of custom attribute when issuing certificate through ACME
  src/main/java/com/czertainly/core/service/impl/UserManagementServiceImpl.java
  src/main/java/com/czertainly/core/service/v2/impl/ClientOperationServiceImpl.java
Labels: bug, ignore-for-release

#340 Add access control to settings
  src/main/java/com/czertainly/core/service/impl/SettingServiceImpl.java
Labels: bug, ignore-for-release

#341 Searching and filtering on metadata and custom attributes
  README.md
  pom.xml
  src/main/java/com/czertainly/core/comparator/SearchFieldDataComparator.java
  src/main/java/com/czertainly/core/dao/entity/AttributeContent.java
  src/main/java/com/czertainly/core/dao/entity/AttributeContentItem.java
  src/main/java/com/czertainly/core/dao/repository/AttributeContent2ObjectRepository.java
  src/main/java/com/czertainly/core/dao/repository/AttributeContentRepository.java
  src/main/java/com/czertainly/core/dao/repository/SecurityFilterRepository.java
  src/main/java/com/czertainly/core/dao/repository/SecurityFilterRepositoryImpl.java
  src/main/java/com/czertainly/core/enums/SearchFieldTypeEnum.java
  src/main/java/com/czertainly/core/model/SearchFieldObject.java
  src/main/java/com/czertainly/core/service/impl/AttributeServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/CertificateServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/CryptographicKeyServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/MetadataServiceImpl.java
  src/main/java/com/czertainly/core/util/DatabaseMigration.java
  src/main/java/com/czertainly/core/util/SearchHelper.java
  src/main/java/com/czertainly/core/util/converter/Sql2PredicateConverter.java
  src/main/java/db/migration/V202303160830__AttributeContentJsonMigration.java
  src/main/resources/db/migration/V202303081420__attribute_content_jsonb.sql
  src/test/java/com/czertainly/core/service/CertificateServiceTest.java
  src/test/java/com/czertainly/core/util/converter/Sql2PredicateConverterTest.java
Labels: new-feature

#344 Fix key item reference in the metadata
  src/main/java/com/czertainly/core/service/impl/CryptographicKeyServiceImpl.java
  src/main/resources/db/migration/V202303241800__cryptographic_key_reference.sql
Labels: bug, ignore-for-release

#347 Rename legacy client operation DTOs
  src/main/java/com/czertainly/core/api/client/ClientOperationControllerImpl.java
  src/main/java/com/czertainly/core/service/ClientOperationService.java
  src/main/java/com/czertainly/core/service/impl/ClientOperationServiceImpl.java
  src/test/java/com/czertainly/core/service/ClientOperationServiceV1Test.java
Labels: ignore-for-release

#348 Fix filtering on properties when not filtering on attributes
  src/main/java/com/czertainly/core/util/converter/Sql2PredicateConverter.java
Labels: bug, ignore-for-release

#353 SCEP Protocol Implementation
  pom.xml
  src/main/java/com/czertainly/core/api/scep/ScepControllerImpl.java
  src/main/java/com/czertainly/core/api/scep/ScepRaProfileControllerImpl.java
  src/main/java/com/czertainly/core/api/web/RAProfileManagementControllerImpl.java
  src/main/java/com/czertainly/core/api/web/ScepProfileControllerImpl.java
  src/main/java/com/czertainly/core/attribute/EncryptionAttributes.java
  src/main/java/com/czertainly/core/attribute/RsaSignatureAttributes.java
  src/main/java/com/czertainly/core/config/CustomAuditAware.java
  src/main/java/com/czertainly/core/config/ProtocolValidationFilter.java
  src/main/java/com/czertainly/core/config/ScepHttpMessageConverter.java
  src/main/java/com/czertainly/core/config/ScepVerifierProvider.java
  src/main/java/com/czertainly/core/config/SecurityConfig.java
  src/main/java/com/czertainly/core/config/WebAppConfig.java
  src/main/java/com/czertainly/core/dao/entity/RaProfile.java
  src/main/java/com/czertainly/core/dao/entity/RaProfileProtocolAttribute.java
  src/main/java/com/czertainly/core/dao/entity/scep/ScepProfile.java
  src/main/java/com/czertainly/core/dao/entity/scep/ScepTransaction.java
  src/main/java/com/czertainly/core/dao/repository/RaProfileProtocolAttributeRepository.java
  src/main/java/com/czertainly/core/dao/repository/RaProfileRepository.java
  src/main/java/com/czertainly/core/dao/repository/scep/ScepProfileRepository.java
  src/main/java/com/czertainly/core/dao/repository/scep/ScepTransactionRepository.java
  src/main/java/com/czertainly/core/model/auth/Resource.java
  src/main/java/com/czertainly/core/security/authn/client/CzertainlyAuthenticationClient.java
  src/main/java/com/czertainly/core/service/RaProfileService.java
  src/main/java/com/czertainly/core/service/ScepProfileService.java
  src/main/java/com/czertainly/core/service/acme/impl/ExtendedAcmeHelperService.java
  src/main/java/com/czertainly/core/service/impl/CryptographicOperationServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/RaProfileServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/ScepProfileServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/UserManagementServiceImpl.java
  src/main/java/com/czertainly/core/service/scep/ExtendedScepHelperService.java
  src/main/java/com/czertainly/core/service/scep/ScepService.java
  src/main/java/com/czertainly/core/service/scep/impl/ExtendedScepHelperServiceImpl.java
  src/main/java/com/czertainly/core/service/scep/impl/ScepServiceImpl.java
  src/main/java/com/czertainly/core/service/v2/impl/ClientOperationServiceImpl.java
  src/main/java/com/czertainly/core/util/DatabaseMigration.java
  src/main/java/com/czertainly/core/util/ScepCommonHelper.java
  src/main/java/com/czertainly/core/util/SecretEncodingVersion.java
  src/main/java/com/czertainly/core/util/SecretsUtil.java
  src/main/java/db/migration/V202303211718__Scep_Roles.java
  src/main/resources/application.properties
  src/main/resources/db/migration/V202303211150__scep.sql
  src/test/java/com/czertainly/core/service/CryptographicOperationServiceTest.java
  src/test/java/com/czertainly/core/service/ScepProfileServiceTest.java
  src/test/java/com/czertainly/core/util/DatabaseMigrationTest.java
  src/test/resources/application.properties
Labels: new-feature

#354 Add SCEP to enabled protocols to RA Profile list response
  src/main/java/com/czertainly/core/dao/entity/RaProfile.java
Labels: bug, ignore-for-release

#355 Remove SCEP revoke attributes from the DTO
  src/main/java/com/czertainly/core/dao/entity/scep/ScepProfile.java
  src/main/java/com/czertainly/core/service/impl/ScepProfileServiceImpl.java
Labels: bug, ignore-for-release

#356 Updated tests for searching and filtering on metadata and custom attributes
  src/main/java/com/czertainly/core/util/converter/Sql2PredicateConverter.java
  src/test/java/com/czertainly/core/util/converter/Sql2PredicateConverterTest.java
Labels: enhancement, ignore-for-release

#359 Implement listing of certificates eligible as CA certificate for SCEP
  src/main/java/com/czertainly/core/api/web/ScepProfileControllerImpl.java
  src/main/java/com/czertainly/core/service/CertificateService.java
  src/main/java/com/czertainly/core/service/ScepProfileService.java
  src/main/java/com/czertainly/core/service/impl/CertificateServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/ScepProfileServiceImpl.java
Labels: enhancement, ignore-for-release
