Repository CZERTAINLY/CZERTAINLY-Core, pull requests merged in 2023-09, with the labels that each got.

#554 Fix search when user has object access restricted permissions
  src/main/java/com/czertainly/core/dao/repository/SecurityFilterRepositoryImpl.java
  src/main/java/com/czertainly/core/service/impl/DiscoveryServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/EntityInstanceServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/LocationServiceImpl.java
  src/main/java/com/czertainly/core/util/converter/Sql2PredicateConverter.java
  src/test/java/com/czertainly/core/search/DiscoveryHistorySearchTest.java
Labels: bug

#559 Update release version to 2.9.0
  pom.xml
Labels: ignore-for-release

#565 Refactor updating certificate issuer and get certificate chain
  pom.xml
  src/main/java/com/czertainly/core/api/web/CertificateControllerImpl.java
  src/main/java/com/czertainly/core/dao/entity/Certificate.java
  src/main/java/com/czertainly/core/service/CertificateService.java
  src/main/java/com/czertainly/core/service/impl/CertificateServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/ClientOperationServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/DiscoveryServiceImpl.java
  src/main/java/com/czertainly/core/util/CertificateUtil.java
  src/main/java/com/czertainly/core/util/OcspUtil.java
  src/main/resources/db/migration/V202309051425__issuer_certificate_uuid.sql
Labels: enhancement

#570 Resolve exception handling
  src/main/java/com/czertainly/core/api/web/CertificateControllerImpl.java
  src/main/java/com/czertainly/core/service/CertificateService.java
  src/main/java/com/czertainly/core/service/impl/CertificateServiceImpl.java
Labels: ignore-for-release

#569 Update implementation of getting the certificate chain
  src/main/java/com/czertainly/core/api/ExceptionHandlingAdvice.java
  src/main/java/com/czertainly/core/service/CertificateService.java
  src/main/java/com/czertainly/core/service/impl/CertificateServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/DiscoveryServiceImpl.java
Labels: ignore-for-release
