Repository CZERTAINLY/CZERTAINLY-Core, pull requests merged in 2023-05, with the labels that each got.

#362 Refactor SCEP protocol implementation and add support for integration with MS Intune
  pom.xml
  src/main/java/com/czertainly/core/api/ExceptionHandlingAdvice.java
  src/main/java/com/czertainly/core/api/scep/ScepControllerImpl.java
  src/main/java/com/czertainly/core/api/scep/ScepRaProfileControllerImpl.java
  src/main/java/com/czertainly/core/attribute/EncryptionAttributes.java
  src/main/java/com/czertainly/core/attribute/RsaEncryptionAttributes.java
  src/main/java/com/czertainly/core/dao/entity/RaProfile.java
  src/main/java/com/czertainly/core/dao/entity/scep/ScepProfile.java
  src/main/java/com/czertainly/core/dao/entity/scep/ScepTransaction.java
  src/main/java/com/czertainly/core/intune/carequest/CARequestErrorCodes.java
  src/main/java/com/czertainly/core/intune/carequest/CARevocationRequest.java
  src/main/java/com/czertainly/core/intune/carequest/CARevocationResult.java
  src/main/java/com/czertainly/core/intune/scepvalidation/ADALClientWrapper.java
  src/main/java/com/czertainly/core/intune/scepvalidation/IntuneClient.java
  src/main/java/com/czertainly/core/intune/scepvalidation/IntuneClientException.java
  src/main/java/com/czertainly/core/intune/scepvalidation/IntuneClientHttpErrorException.java
  src/main/java/com/czertainly/core/intune/scepvalidation/IntuneRevocationClient.java
  src/main/java/com/czertainly/core/intune/scepvalidation/IntuneScepServiceClient.java
  src/main/java/com/czertainly/core/intune/scepvalidation/IntuneScepServiceException.java
  src/main/java/com/czertainly/core/intune/scepvalidation/IntuneServiceNotFoundException.java
  src/main/java/com/czertainly/core/intune/scepvalidation/MSALClientWrapper.java
  src/main/java/com/czertainly/core/provider/CzertainlyCipherService.java
  src/main/java/com/czertainly/core/provider/CzertainlyProvider.java
  src/main/java/com/czertainly/core/provider/CzertainlySignatureService.java
  src/main/java/com/czertainly/core/provider/key/CzertainlyPrivateKey.java
  src/main/java/com/czertainly/core/provider/key/CzertainlyPublicKey.java
  src/main/java/com/czertainly/core/provider/spi/CzertainlyCipherSpi.java
  src/main/java/com/czertainly/core/provider/spi/CzertainlySignatureSpi.java
  src/main/java/com/czertainly/core/service/CryptographicKeyService.java
  src/main/java/com/czertainly/core/service/impl/CertificateServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/CryptographicKeyServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/CryptographicOperationServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/ScepProfileServiceImpl.java
  src/main/java/com/czertainly/core/service/scep/ExtendedScepHelperService.java
  src/main/java/com/czertainly/core/service/scep/ScepService.java
  src/main/java/com/czertainly/core/service/scep/impl/ExtendedScepHelperServiceImpl.java
  src/main/java/com/czertainly/core/service/scep/impl/ScepServiceImpl.java
  src/main/java/com/czertainly/core/service/scep/message/ScepConstants.java
  src/main/java/com/czertainly/core/service/scep/message/ScepRequest.java
  src/main/java/com/czertainly/core/service/scep/message/ScepResponse.java
  src/main/java/com/czertainly/core/service/scep/message/ScepVerifierProvider.java
  src/main/java/com/czertainly/core/util/AlgorithmUtil.java
  src/main/java/com/czertainly/core/util/CertificateUtil.java
  src/main/java/com/czertainly/core/util/RandomUtil.java
  src/main/java/com/czertainly/core/util/RawJsonDeserializer.java
  src/main/java/com/czertainly/core/util/ScepCommonHelper.java
  src/main/resources/application.properties
  src/main/resources/db/migration/V202304262150__scep_intune.sql
  src/test/java/com/czertainly/core/intune/Helper.java
  src/test/java/com/czertainly/core/intune/RevocationTests.java
  src/test/java/com/czertainly/core/intune/Test.java
  src/test/java/com/czertainly/core/service/TokenInstanceServiceTest.java
  src/test/java/com/czertainly/core/service/TokenProfileServiceTest.java
  src/test/java/com/czertainly/core/service/scep/CmsMessageTest.java
  src/test/java/com/czertainly/core/service/scep/CryptographicProviderTest.java
  src/test/java/com/czertainly/core/service/scep/EcdsaCmsMessageTest.java
  src/test/java/com/czertainly/core/util/AlgorithmUtilTest.java
  src/test/resources/application.properties
Labels: new-feature

#380 Add list of resources to custom attributes
  src/main/java/com/czertainly/core/api/web/CustomAttributeControllerImpl.java
  src/main/java/com/czertainly/core/api/web/GlobalMetadataControllerImpl.java
  src/main/java/com/czertainly/core/dao/entity/AttributeDefinition.java
  src/main/java/com/czertainly/core/service/AttributeService.java
  src/main/java/com/czertainly/core/service/impl/AttributeServiceImpl.java
  src/test/java/com/czertainly/core/service/CustomAttributeServiceTest.java
  src/test/java/com/czertainly/core/service/GlobalMetadataServiceTest.java
Labels: enhancement

#381 Update listing of eligible SCEP Profile CA certificates with regard to Intune integration
  src/main/java/com/czertainly/core/api/web/ScepProfileControllerImpl.java
  src/main/java/com/czertainly/core/service/CertificateService.java
  src/main/java/com/czertainly/core/service/ScepProfileService.java
  src/main/java/com/czertainly/core/service/impl/CertificateServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/ScepProfileServiceImpl.java
Labels: enhancement

#382 Fix key check in the CZERTAINLY provider implementation
  src/main/java/com/czertainly/core/api/web/CryptographicOperationControllerImpl.java
  src/main/java/com/czertainly/core/attribute/EcdsaSignatureAttributes.java
  src/main/java/com/czertainly/core/attribute/RsaEncryptionAttributes.java
  src/main/java/com/czertainly/core/attribute/RsaSignatureAttributes.java
  src/main/java/com/czertainly/core/config/TokenContentSigner.java
  src/main/java/com/czertainly/core/dao/entity/Certificate.java
  src/main/java/com/czertainly/core/dao/entity/CryptographicKeyItem.java
  src/main/java/com/czertainly/core/provider/CzertainlyCipherService.java
  src/main/java/com/czertainly/core/provider/CzertainlySignatureService.java
  src/main/java/com/czertainly/core/provider/spi/CzertainlyCipherSpi.java
  src/main/java/com/czertainly/core/service/CryptographicKeyService.java
  src/main/java/com/czertainly/core/service/CryptographicOperationService.java
  src/main/java/com/czertainly/core/service/impl/CertificateServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/CryptographicKeyServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/CryptographicOperationServiceImpl.java
  src/main/java/com/czertainly/core/service/scep/impl/ScepServiceImpl.java
  src/main/java/com/czertainly/core/service/scep/message/ScepRequest.java
  src/main/java/com/czertainly/core/util/AlgorithmUtil.java
  src/main/java/com/czertainly/core/util/CertificateUtil.java
  src/main/java/com/czertainly/core/util/CryptographyUtil.java
  src/test/java/com/czertainly/core/service/CryptographicKeyServiceTest.java
  src/test/java/com/czertainly/core/service/CryptographicOperationServiceTest.java
  src/test/java/com/czertainly/core/service/ScepProfileServiceTest.java
  src/test/java/com/czertainly/core/service/scep/CmsMessageTest.java
  src/test/java/com/czertainly/core/service/scep/CryptographicProviderTest.java
  src/test/java/com/czertainly/core/service/scep/EcdsaCmsMessageTest.java
Labels: bug

#386 Fix length of the Intune failure message
  src/main/java/com/czertainly/core/service/scep/impl/ScepServiceImpl.java
Labels: bug

#388 Fix check if Intune is enabled
  src/main/java/com/czertainly/core/service/scep/impl/ScepServiceImpl.java
Labels: bug, ignore-for-release

#389 Fix search filter of certificate inventory with EMPTY condition for Group and RA Profile
  src/main/java/com/czertainly/core/util/converter/Sql2PredicateConverter.java
Labels: bug, ignore-for-release

#387 Add SCEP URL to listing DTO
  src/main/java/com/czertainly/core/dao/entity/scep/ScepProfile.java
Labels: bug, ignore-for-release

#394 Fix delete certificate without content
  src/main/java/com/czertainly/core/service/impl/CertificateServiceImpl.java
Labels: bug

#396 Fix metadata of issued certificate stating connector Unknown
  src/main/java/com/czertainly/core/service/CertificateService.java
  src/main/java/com/czertainly/core/service/impl/CertificateServiceImpl.java
  src/main/java/com/czertainly/core/service/v2/impl/ClientOperationServiceImpl.java
Labels: bug

#397 Filter invalid key usages for key based on key algorithm
  src/main/java/com/czertainly/core/service/impl/CryptographicKeyServiceImpl.java
  src/test/java/com/czertainly/core/service/CryptographicKeyServiceTest.java
Labels: bug

#400 Add KeyAlgorithm enum converter
  src/main/java/com/czertainly/core/api/web/CryptographicOperationControllerImpl.java
  src/main/java/com/czertainly/core/config/WebAppConfig.java
  src/main/java/com/czertainly/core/service/impl/CertificateServiceImpl.java
Labels: bug

#392 Implement task for Intune revocation requests
  src/main/java/com/czertainly/core/dao/repository/CertificateRepository.java
  src/main/java/com/czertainly/core/dao/repository/scep/ScepProfileRepository.java
  src/main/java/com/czertainly/core/intune/scepvalidation/IntuneRevocationClient.java
  src/main/java/com/czertainly/core/service/CertificateService.java
  src/main/java/com/czertainly/core/service/impl/CertificateServiceImpl.java
  src/main/java/com/czertainly/core/tasks/ScheduledTasks.java
  src/main/java/com/czertainly/core/tasks/UpdateIntuneRevocationRequestsTask.java
  src/main/java/com/czertainly/core/util/CryptographyUtil.java
Labels: enhancement, ignore-for-release

#391 Allow SCEP to be used only with valid certificate
  src/main/java/com/czertainly/core/service/impl/CertificateServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/ScepProfileServiceImpl.java
  src/main/java/com/czertainly/core/service/scep/impl/ScepServiceImpl.java
  src/main/java/com/czertainly/core/util/CertificateUtil.java
  src/test/java/com/czertainly/core/service/ScepProfileServiceTest.java
Labels: bug, ignore-for-release

#401 Implement issuing existing certificate in status New
  src/main/java/com/czertainly/core/api/v2/client/ClientOperationControllerImpl.java
  src/main/java/com/czertainly/core/service/v2/ClientOperationService.java
  src/main/java/com/czertainly/core/service/v2/impl/ClientOperationServiceImpl.java
  src/test/java/com/czertainly/core/service/ClientOperationServiceV2Test.java
Labels: enhancement, ignore-for-release

#402 Add missing issue attributes to issue certificate by SCEP protocol
  src/main/java/com/czertainly/core/service/scep/impl/ScepServiceImpl.java
Labels: bug, ignore-for-release

#416 Add authorization for Intune revocation requests processing
  src/main/java/com/czertainly/core/config/ProtocolValidationFilter.java
  src/main/java/com/czertainly/core/model/auth/AuthenticationRequestDto.java
  src/main/java/com/czertainly/core/security/authn/client/CzertainlyAuthenticationClient.java
  src/main/java/com/czertainly/core/tasks/UpdateIntuneRevocationRequestsTask.java
  src/main/java/com/czertainly/core/util/AuthHelper.java
  src/main/java/com/czertainly/core/util/DatabaseMigration.java
  src/main/java/db/migration/V202303211718__Scep_Roles.java
Labels: ignore-for-release

#418 Update RA profile for existing SCEP profile does not send selected RA profile
  src/main/java/com/czertainly/core/service/impl/AcmeProfileServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/ScepProfileServiceImpl.java
Labels: enhancement, ignore-for-release

#419 Fix activation of SCEP protocol for RA profile
  src/main/java/com/czertainly/core/dao/entity/RaProfile.java
Labels: bug, ignore-for-release

#422 Deleting key deletes key also from cryptography provider
  src/main/java/com/czertainly/core/service/CryptographicKeyService.java
  src/main/java/com/czertainly/core/service/impl/CryptographicKeyServiceImpl.java
Labels: bug

#429 Add multidomain validation support to ACME
  src/main/java/com/czertainly/core/service/acme/impl/ExtendedAcmeHelperService.java
Labels: bug

#428 Fix changing state of keys and key items to respect key state model
  src/main/java/com/czertainly/core/service/impl/CryptographicKeyServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/CryptographicOperationServiceImpl.java
  src/test/java/com/czertainly/core/service/CryptographicKeyServiceTest.java
Labels: enhancement

#424 Include issued certificate chain to SCEP response based on profile configuration
  build_image_locally
  src/main/java/com/czertainly/core/service/impl/CertValidationServiceImpl.java
  src/main/java/com/czertainly/core/service/scep/impl/ScepServiceImpl.java
  src/main/java/com/czertainly/core/service/scep/message/ScepResponse.java
  src/main/java/com/czertainly/core/tasks/UpdateIntuneRevocationRequestsTask.java
Labels: enhancement, ignore-for-release

#433 Implement scheduling of discoveries
  src/main/java/com/czertainly/core/api/web/DiscoveryControllerImpl.java
  src/main/java/com/czertainly/core/dao/entity/RaProfile.java
  src/main/java/com/czertainly/core/security/authn/CzertainlyUserDetails.java
  src/main/java/com/czertainly/core/security/authn/client/AuthenticationInfo.java
  src/main/java/com/czertainly/core/security/authn/client/CzertainlyAuthenticationClient.java
  src/main/java/com/czertainly/core/security/authn/client/dto/UserDto.java
  src/main/java/com/czertainly/core/service/CryptographicKeyService.java
  src/main/java/com/czertainly/core/service/DiscoveryService.java
  src/main/java/com/czertainly/core/service/acme/impl/ExtendedAcmeHelperService.java
  src/main/java/com/czertainly/core/service/impl/AcmeProfileServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/CertValidationServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/CryptographicKeyServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/CryptographicOperationServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/DiscoveryServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/ScepProfileServiceImpl.java
  src/main/java/com/czertainly/core/tasks/DiscoveryCertificateTask.java
  src/test/java/com/czertainly/core/security/authz/AbstractExternalAuthorizationVoterTest.java
  src/test/java/com/czertainly/core/security/authz/ExternalFilterAuthorizationVoterTest.java
  src/test/java/com/czertainly/core/security/authz/ExternalMethodAuthorizationVoterTest.java
  src/test/java/com/czertainly/core/service/CryptographicKeyServiceTest.java
  src/test/java/com/czertainly/core/service/DiscoveryServiceTest.java
  src/test/java/com/czertainly/core/util/BaseSpringBootTest.java
Labels: enhancement

#437 Add validation for ACME and SCEP profile name to contain only URL safe characters
  src/main/java/com/czertainly/core/service/impl/AcmeProfileServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/ScepProfileServiceImpl.java
  src/main/java/com/czertainly/core/util/ValidatorUtil.java
  src/test/java/com/czertainly/core/util/ValidatorUtilTest.java
Labels: enhancement, ignore-for-release

#438 Add validation for ACME and SCEP profile name to contain only URL safe characters
  src/main/java/com/czertainly/core/service/impl/AcmeProfileServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/ScepProfileServiceImpl.java
  src/main/java/com/czertainly/core/util/ValidatorUtil.java
  src/test/java/com/czertainly/core/util/ValidatorUtilTest.java
Labels: enhancement

#435 When syncing certificates of location metadata are returned from unknown connector
  src/main/java/com/czertainly/core/dao/entity/AttributeContent2Object.java
  src/main/java/com/czertainly/core/dao/repository/AttributeContent2ObjectRepository.java
  src/main/java/com/czertainly/core/service/LocationService.java
  src/main/java/com/czertainly/core/service/impl/CryptographicKeyServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/LocationServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/MetadataServiceImpl.java
Labels: bug, ignore-for-release

#439 Fix syncing certificates of location metadata returned from unknown connector
  src/main/java/com/czertainly/core/dao/entity/AttributeContent2Object.java
  src/main/java/com/czertainly/core/dao/repository/AttributeContent2ObjectRepository.java
  src/main/java/com/czertainly/core/service/LocationService.java
  src/main/java/com/czertainly/core/service/impl/LocationServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/MetadataServiceImpl.java
Labels: bug
