Repository CZERTAINLY/CZERTAINLY-Core, pull requests merged in 2023-07, with the labels that each got.

#491 Implement management of approval profiles
  src/main/java/com/czertainly/core/api/web/ApprovalProfileControllerImpl.java
  src/main/java/com/czertainly/core/dao/entity/Approval.java
  src/main/java/com/czertainly/core/dao/entity/ApprovalProfile.java
  src/main/java/com/czertainly/core/dao/entity/ApprovalProfileVersion.java
  src/main/java/com/czertainly/core/dao/entity/ApprovalRecipient.java
  src/main/java/com/czertainly/core/dao/entity/ApprovalStep.java
  src/main/java/com/czertainly/core/dao/repository/ApprovalProfileRepository.java
  src/main/java/com/czertainly/core/dao/repository/ApprovalProfileVersionRepository.java
  src/main/java/com/czertainly/core/dao/repository/ApprovalRecipientRepository.java
  src/main/java/com/czertainly/core/dao/repository/ApprovalRepository.java
  src/main/java/com/czertainly/core/dao/repository/ApprovalStepRepository.java
  src/main/java/com/czertainly/core/enums/ApprovalStatusEnum.java
  src/main/java/com/czertainly/core/service/ApprovalProfileService.java
  src/main/java/com/czertainly/core/service/impl/ApprovalProfileServiceImpl.java
  src/main/resources/db/migration/V202306261155__approval_profiles.sql
  src/test/java/com/czertainly/core/service/ApprovalProfileServiceTest.java
Labels: new-feature

#494 Implement internal notifications in Core
  src/main/java/com/czertainly/core/api/web/NotificationControllerImpl.java
  src/main/java/com/czertainly/core/dao/entity/Notification.java
  src/main/java/com/czertainly/core/dao/entity/NotificationRecipient.java
  src/main/java/com/czertainly/core/dao/repository/NotificationRepository.java
  src/main/java/com/czertainly/core/service/NotificationService.java
  src/main/java/com/czertainly/core/service/impl/NotificationServiceImpl.java
  src/main/resources/db/migration/V202307031140__internal_notifications.sql
Labels: new-feature

#497 Add sending timestamp and target object identification to notification
  src/main/java/com/czertainly/core/dao/entity/Notification.java
  src/main/java/com/czertainly/core/dao/repository/NotificationRepository.java
  src/main/java/com/czertainly/core/service/NotificationService.java
  src/main/java/com/czertainly/core/service/impl/NotificationServiceImpl.java
  src/main/resources/db/migration/V202307121340__internal_notifications_add_columns.sql
Labels: enhancement, ignore-for-release

#501 Add email to role requests
  src/main/java/com/czertainly/core/service/impl/RoleManagementServiceImpl.java
Labels: enhancement, ignore-for-release

#504 Update structure of notification messages and notify with internal notifications
  src/main/java/com/czertainly/core/enums/RecipientTypeEnum.java
  src/main/java/com/czertainly/core/messaging/listeners/EventListener.java
  src/main/java/com/czertainly/core/messaging/listeners/NotificationListener.java
  src/main/java/com/czertainly/core/messaging/model/NotificationMessage.java
  src/main/java/com/czertainly/core/messaging/model/NotificationRecipient.java
  src/main/java/com/czertainly/core/messaging/producers/NotificationProducer.java
  src/main/java/com/czertainly/core/service/impl/CertificateServiceImpl.java
  src/main/java/com/czertainly/core/tasks/SchedulerJobProcessor.java
Labels: enhancement, ignore-for-release

#506 Implement listing of user approvals
  src/main/java/com/czertainly/core/api/web/ApprovalControllerImpl.java
  src/main/java/com/czertainly/core/api/web/CertificateControllerImpl.java
  src/main/java/com/czertainly/core/service/ApprovalService.java
  src/main/java/com/czertainly/core/service/impl/ApprovalServiceImpl.java
Labels: enhancement, ignore-for-release

#508 Implement management of notification instances
  src/main/java/com/czertainly/core/api/web/NotificationInstanceControllerImpl.java
  src/main/java/com/czertainly/core/config/ApplicationConfig.java
  src/main/java/com/czertainly/core/dao/entity/NotificationInstanceMappedAttributes.java
  src/main/java/com/czertainly/core/dao/entity/NotificationInstanceReference.java
  src/main/java/com/czertainly/core/dao/repository/NotificationInstanceReferenceRepository.java
  src/main/java/com/czertainly/core/model/auth/Resource.java
  src/main/java/com/czertainly/core/service/NotificationInstanceService.java
  src/main/java/com/czertainly/core/service/impl/NotificationInstanceServiceImpl.java
  src/main/resources/db/migration/V202307211000__notification_instance.sql
Labels: new-feature

#509 Orchestration of approval flow and its integration to certificate actions
  src/main/java/com/czertainly/core/api/web/NotificationInstanceControllerImpl.java
  src/main/java/com/czertainly/core/api/web/RAProfileManagementControllerImpl.java
  src/main/java/com/czertainly/core/dao/entity/Approval.java
  src/main/java/com/czertainly/core/dao/entity/ApprovalProfileRelation.java
  src/main/java/com/czertainly/core/dao/entity/ScheduledJob.java
  src/main/java/com/czertainly/core/dao/repository/ApprovalProfileRelationRepository.java
  src/main/java/com/czertainly/core/dao/repository/ApprovalRepository.java
  src/main/java/com/czertainly/core/dao/repository/ApprovalStepRepository.java
  src/main/java/com/czertainly/core/messaging/configuration/RabbitMQConfiguration.java
  src/main/java/com/czertainly/core/messaging/configuration/RabbitMQConstants.java
  src/main/java/com/czertainly/core/messaging/listeners/ActionListener.java
  src/main/java/com/czertainly/core/messaging/listeners/NotificationListener.java
  src/main/java/com/czertainly/core/messaging/model/ActionMessage.java
  src/main/java/com/czertainly/core/messaging/model/NotificationMessage.java
  src/main/java/com/czertainly/core/messaging/producers/ActionProducer.java
  src/main/java/com/czertainly/core/messaging/producers/NotificationProducer.java
  src/main/java/com/czertainly/core/model/auth/Resource.java
  src/main/java/com/czertainly/core/model/auth/ResourceAction.java
  src/main/java/com/czertainly/core/service/ApprovalService.java
  src/main/java/com/czertainly/core/service/RaProfileService.java
  src/main/java/com/czertainly/core/service/acme/impl/ExtendedAcmeHelperService.java
  src/main/java/com/czertainly/core/service/impl/ApprovalProfileServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/ApprovalServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/CertificateServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/NotificationInstanceServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/RaProfileServiceImpl.java
  src/main/java/com/czertainly/core/service/v2/ClientOperationService.java
  src/main/java/com/czertainly/core/service/v2/impl/ClientOperationServiceImpl.java
  src/main/java/com/czertainly/core/tasks/SchedulerJobProcessor.java
  src/main/resources/db/migration/V202307210955__approval_data.sql
  src/test/java/com/czertainly/core/service/ApprovalServiceTest.java
  src/test/java/com/czertainly/core/service/ClientOperationServiceV2Test.java
  src/test/java/com/czertainly/core/service/RaProfileServiceTest.java
  src/test/java/com/czertainly/core/util/BaseSpringBootTest.java
Labels: new-feature

#516 Fix certificate status change notification data
  src/main/java/com/czertainly/core/messaging/model/NotificationMessage.java
  src/main/java/com/czertainly/core/messaging/producers/NotificationProducer.java
  src/main/java/com/czertainly/core/service/impl/CertificateServiceImpl.java
Labels: bug, ignore-for-release

#515 Add notification provider function group and endpoints
  src/main/resources/db/migration/V202307311300__notification_provider.sql
Labels: enhancement
