Repository CZERTAINLY/CZERTAINLY-Core, pull requests merged in 2023-08, with the labels that each got.

#517 Make /v1 endpoint optional for the notification provider
  src/main/resources/db/migration/V202307311300__notification_provider.sql
Labels: bug, ignore-for-release

#519 Add access control for approvals and approval profiles
  src/main/java/com/czertainly/core/api/web/ApprovalProfileControllerImpl.java
  src/main/java/com/czertainly/core/dao/entity/ApprovalProfile.java
  src/main/java/com/czertainly/core/dao/entity/ApprovalProfileVersion.java
  src/main/java/com/czertainly/core/dao/entity/ApprovalStep.java
  src/main/java/com/czertainly/core/dao/repository/ApprovalRecipientRepository.java
  src/main/java/com/czertainly/core/service/ApprovalProfileService.java
  src/main/java/com/czertainly/core/service/impl/ApprovalProfileServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/ApprovalServiceImpl.java
  src/test/java/com/czertainly/core/service/ApprovalProfileServiceTest.java
  src/test/java/com/czertainly/core/service/ApprovalServiceTest.java
Labels: enhancement, ignore-for-release

#520 Split certificate create (submit request) and issue operation
  src/main/java/com/czertainly/core/api/v2/client/ClientOperationControllerImpl.java
  src/main/java/com/czertainly/core/api/web/CertificateControllerImpl.java
  src/main/java/com/czertainly/core/dao/entity/Approval.java
  src/main/java/com/czertainly/core/dao/entity/CertificateRequest.java
  src/main/java/com/czertainly/core/messaging/listeners/ActionListener.java
  src/main/java/com/czertainly/core/service/CertificateService.java
  src/main/java/com/czertainly/core/service/impl/ApprovalServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/CertificateServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/LocationServiceImpl.java
  src/main/java/com/czertainly/core/service/scep/impl/ScepServiceImpl.java
  src/main/java/com/czertainly/core/service/v2/ClientOperationService.java
  src/main/java/com/czertainly/core/service/v2/impl/ClientOperationServiceImpl.java
  src/main/java/com/czertainly/core/util/AuthHelper.java
  src/test/java/com/czertainly/core/service/ClientOperationServiceV2Test.java
Labels: enhancement, ignore-for-release

#522 Add migration to update ACME and SCEP role certificate permissions
  src/main/java/com/czertainly/core/service/impl/RoleManagementServiceImpl.java
  src/main/java/com/czertainly/core/util/DatabaseMigration.java
  src/main/java/db/migration/V202308050825__UpdateAcmeScepRolesPermissions.java
  src/test/java/com/czertainly/core/util/DatabaseMigrationTest.java
Labels: enhancement

#523 Add action listener error handling and notify action result
  src/main/java/com/czertainly/core/dao/entity/ApprovalProfileVersion.java
  src/main/java/com/czertainly/core/messaging/listeners/ActionListener.java
  src/main/java/com/czertainly/core/messaging/listeners/NotificationListener.java
  src/main/java/com/czertainly/core/messaging/listeners/SchedulerListener.java
  src/main/java/com/czertainly/core/messaging/model/NotificationMessage.java
  src/main/java/com/czertainly/core/messaging/model/NotificationRecipient.java
  src/main/java/com/czertainly/core/messaging/producers/NotificationProducer.java
  src/main/java/com/czertainly/core/service/impl/ApprovalServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/CertificateServiceImpl.java
  src/main/java/com/czertainly/core/service/v2/impl/ClientOperationServiceImpl.java
  src/main/resources/application.properties
Labels: enhancement, ignore-for-release

#525 Add automatic check for approvals expiration
  src/main/java/com/czertainly/core/api/web/CertificateControllerImpl.java
  src/main/java/com/czertainly/core/config/ApprovalExpirationFilter.java
  src/main/java/com/czertainly/core/config/ProtocolValidationFilter.java
  src/main/java/com/czertainly/core/config/WebAppConfig.java
  src/main/java/com/czertainly/core/dao/entity/Approval.java
  src/main/java/com/czertainly/core/dao/repository/ApprovalRepository.java
  src/main/java/com/czertainly/core/service/ApprovalService.java
  src/main/java/com/czertainly/core/service/impl/ApprovalServiceImpl.java
  src/main/java/com/czertainly/core/tasks/UpdateCertificateStatusTask.java
  src/main/resources/db/migration/V202308060622__approval_expiry_date.sql
Labels: enhancement

#528 Check changes of edited approval profile before creating new version
  src/main/java/com/czertainly/core/dao/entity/ApprovalProfileVersion.java
  src/main/java/com/czertainly/core/service/impl/ApprovalProfileServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/ApprovalServiceImpl.java
  src/test/java/com/czertainly/core/service/ApprovalProfileServiceTest.java
  src/test/java/com/czertainly/core/service/ApprovalServiceTest.java
Labels: enhancement, ignore-for-release

#529 Integrate mapped attributes of notification instance and send it to notification provider
  src/main/java/com/czertainly/core/api/web/CustomAttributeControllerImpl.java
  src/main/java/com/czertainly/core/dao/entity/NotificationInstanceReference.java
  src/main/java/com/czertainly/core/dao/repository/AttributeDefinitionRepository.java
  src/main/java/com/czertainly/core/dao/repository/NotificationInstanceMappedAttributeRepository.java
  src/main/java/com/czertainly/core/dao/repository/SecurityFilterRepository.java
  src/main/java/com/czertainly/core/dao/repository/SecurityFilterRepositoryImpl.java
  src/main/java/com/czertainly/core/messaging/listeners/NotificationListener.java
  src/main/java/com/czertainly/core/service/AttributeService.java
  src/main/java/com/czertainly/core/service/impl/AttributeServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/NotificationInstanceServiceImpl.java
  src/main/java/com/czertainly/core/tasks/UpdateCertificateStatusTask.java
  src/main/java/com/czertainly/core/util/converter/AttributeContentTypeConverter.java
  src/test/java/com/czertainly/core/service/CustomAttributeServiceTest.java
Labels: enhancement, ignore-for-release

#530 Add custom attribute label to notification instance mapping attribute
  src/main/java/com/czertainly/core/dao/entity/NotificationInstanceMappedAttributes.java
  src/main/java/com/czertainly/core/messaging/listeners/NotificationListener.java
  src/main/java/com/czertainly/core/messaging/producers/NotificationProducer.java
Labels: enhancement, ignore-for-release

#532 Update CertificateRevocationReason enum handling
  src/main/java/com/czertainly/core/service/acme/impl/ExtendedAcmeHelperService.java
  src/main/java/com/czertainly/core/service/v2/impl/ClientOperationServiceImpl.java
  src/main/java/com/czertainly/core/tasks/UpdateIntuneRevocationRequestsTask.java
  src/test/java/com/czertainly/core/service/AcmeServiceTest.java
  src/test/java/com/czertainly/core/service/acme/impl/ExtendedAcmeHelperServiceTest.java
Labels: enhancement, ignore-for-release

#533 Add checks for approval process before issuing New certificate
  src/main/java/com/czertainly/core/messaging/listeners/ActionListener.java
  src/main/java/com/czertainly/core/messaging/model/ActionMessage.java
  src/main/java/com/czertainly/core/service/v2/impl/ClientOperationServiceImpl.java
Labels: bug, ignore-for-release

#534 Fix notification instance mapped attributes DTO creation
  src/main/java/com/czertainly/core/dao/entity/NotificationInstanceReference.java
  src/main/java/com/czertainly/core/service/impl/NotificationInstanceServiceImpl.java
Labels: bug, ignore-for-release

#535 Add certificate approval events to certificate history
  src/main/java/com/czertainly/core/messaging/listeners/EventListener.java
  src/main/java/com/czertainly/core/messaging/model/EventMessage.java
  src/main/java/com/czertainly/core/messaging/model/NotificationMessage.java
  src/main/java/com/czertainly/core/messaging/model/enums/EventTypeEnum.java
  src/main/java/com/czertainly/core/messaging/model/enums/ResourceTypeEnum.java
  src/main/java/com/czertainly/core/messaging/model/enums/ServiceEnum.java
  src/main/java/com/czertainly/core/messaging/producers/EventProducer.java
  src/main/java/com/czertainly/core/service/CertificateEventHistoryService.java
  src/main/java/com/czertainly/core/service/impl/ApprovalServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/CertificateEventHistoryServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/CertificateServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/DiscoveryServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/LocationServiceImpl.java
  src/main/java/com/czertainly/core/service/v2/impl/ClientOperationServiceImpl.java
Labels: enhancement, ignore-for-release

#536 Update notifications settings when used notification instance is deleted
  src/main/java/com/czertainly/core/service/impl/NotificationInstanceServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/SettingServiceImpl.java
Labels: ignore-for-release

#538 Resolve SonarQube issues
  src/main/java/com/czertainly/core/api/ExceptionHandlingAdvice.java
  src/main/java/com/czertainly/core/config/CachedBodyServletOutputStream.java
  src/main/java/com/czertainly/core/dao/entity/AttributeContent.java
  src/main/java/com/czertainly/core/intune/scepvalidation/IntuneScepServiceClient.java
  src/main/java/com/czertainly/core/messaging/producers/NotificationProducer.java
  src/main/java/com/czertainly/core/security/authz/ExternalMethodAuthorizationVoter.java
  src/main/java/com/czertainly/core/service/RaProfileService.java
  src/main/java/com/czertainly/core/service/impl/ApprovalProfileServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/CertificateServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/ComplianceProfileServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/ConnectorServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/RaProfileServiceImpl.java
  src/main/java/com/czertainly/core/service/v2/impl/ClientOperationServiceImpl.java
  src/main/java/com/czertainly/core/tasks/DiscoveryCertificateTask.java
  src/main/java/com/czertainly/core/tasks/SchedulerJobProcessor.java
  src/main/java/com/czertainly/core/util/CertificateUtil.java
  src/main/java/com/czertainly/core/util/DatabaseMigration.java
  src/main/java/com/czertainly/core/util/KeySizeUtil.java
  src/main/java/com/czertainly/core/util/converter/Sql2PredicateConverter.java
  src/test/java/com/czertainly/core/service/ConnectorServiceComplexTest.java
  src/test/java/com/czertainly/core/service/ConnectorServiceTest.java
Labels: bug, ignore-for-release

#539 Update issue and renew certificate in location operations to work in async issuing process
  pom.xml
  src/main/java/com/czertainly/core/dao/entity/Location.java
  src/main/java/com/czertainly/core/dao/entity/RaProfile.java
  src/main/java/com/czertainly/core/service/LocationService.java
  src/main/java/com/czertainly/core/service/impl/CertificateServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/LocationServiceImpl.java
  src/main/java/com/czertainly/core/service/v2/impl/ClientOperationServiceImpl.java
  src/test/java/com/czertainly/core/service/ConnectorRegistrationServiceTest.java
Labels: enhancement, ignore-for-release

#540 Add manual transactions handling in certificate operations to store submitted certificate
  src/main/java/com/czertainly/core/api/v2/client/ClientOperationControllerImpl.java
  src/main/java/com/czertainly/core/service/impl/LocationServiceImpl.java
  src/main/java/com/czertainly/core/service/scep/impl/ScepServiceImpl.java
  src/main/java/com/czertainly/core/service/v2/ClientOperationService.java
  src/main/java/com/czertainly/core/service/v2/impl/ClientOperationServiceImpl.java
Labels: enhancement, ignore-for-release

#544 Fix SCEP service issue check if certificate was already issued
  src/main/java/com/czertainly/core/service/scep/impl/ScepServiceImpl.java
Labels: bug, ignore-for-release

#547 Handle SCEP CertPoll message properly
  src/main/java/com/czertainly/core/service/scep/impl/ScepServiceImpl.java
  src/main/java/com/czertainly/core/service/scep/message/ScepRequest.java
Labels: bug, ignore-for-release

#549 Remove rejected certificate from locations
  src/main/java/com/czertainly/core/dao/entity/Certificate.java
  src/main/java/com/czertainly/core/service/LocationService.java
  src/main/java/com/czertainly/core/service/impl/LocationServiceImpl.java
  src/main/java/com/czertainly/core/service/v2/impl/ClientOperationServiceImpl.java
Labels: enhancement, ignore-for-release

#550 Send internal notifications when bulk delete certificate fails and discovery completes
  src/main/java/com/czertainly/core/messaging/listeners/ActionListener.java
  src/main/java/com/czertainly/core/service/SearchService.java
  src/main/java/com/czertainly/core/service/impl/CertificateServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/DiscoveryServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/SearchServiceImpl.java
Labels: enhancement

#551 Add owner UUID to CertificateDTO
  src/main/java/com/czertainly/core/dao/entity/Certificate.java
Labels: enhancement, ignore-for-release
