Repository CZERTAINLY/CZERTAINLY-Core, pull requests merged in 2023-10, with the labels that each got.

#573 Refactor certificate validation and add new validation checks
  src/main/java/com/czertainly/core/api/web/CertificateControllerImpl.java
  src/main/java/com/czertainly/core/dao/entity/Certificate.java
  src/main/java/com/czertainly/core/messaging/producers/NotificationProducer.java
  src/main/java/com/czertainly/core/service/CertValidationService.java
  src/main/java/com/czertainly/core/service/CertificateService.java
  src/main/java/com/czertainly/core/service/acme/impl/ExtendedAcmeHelperService.java
  src/main/java/com/czertainly/core/service/impl/CertValidationServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/CertificateServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/ClientOperationServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/ComplianceServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/DiscoveryServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/ScepProfileServiceImpl.java
  src/main/java/com/czertainly/core/service/scep/impl/ScepServiceImpl.java
  src/main/java/com/czertainly/core/service/v2/impl/ClientOperationServiceImpl.java
  src/main/java/com/czertainly/core/util/CertificateUtil.java
  src/main/java/com/czertainly/core/util/CrlUtil.java
  src/main/java/com/czertainly/core/util/MetaDefinitions.java
  src/main/java/com/czertainly/core/util/OcspUtil.java
  src/main/java/com/czertainly/core/validation/certificate/ICertificateValidator.java
  src/main/java/com/czertainly/core/validation/certificate/X509CertificateValidator.java
  src/test/java/com/czertainly/core/service/CertValidationServiceTest.java
  src/test/java/com/czertainly/core/service/CertificateServiceTest.java
Labels: enhancement

#574 Change certificate validation result response
  src/main/java/com/czertainly/core/api/web/CertificateControllerImpl.java
  src/main/java/com/czertainly/core/service/CertificateService.java
  src/main/java/com/czertainly/core/service/impl/CertificateServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/ClientOperationServiceImpl.java
  src/main/java/com/czertainly/core/util/MetaDefinitions.java
  src/main/java/com/czertainly/core/validation/certificate/X509CertificateValidator.java
  src/test/java/com/czertainly/core/service/CertValidationServiceTest.java
Labels: ignore-for-release

#575 Fix slow performance of search filters
  src/main/java/com/czertainly/core/dao/entity/Certificate.java
  src/main/java/com/czertainly/core/dao/repository/AttributeContentRepository.java
  src/main/java/com/czertainly/core/dao/repository/SecurityFilterRepositoryImpl.java
  src/main/java/com/czertainly/core/model/SearchFieldObject.java
  src/main/java/com/czertainly/core/service/AttributeService.java
  src/main/java/com/czertainly/core/service/impl/AttributeServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/CertificateServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/CryptographicKeyServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/DiscoveryServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/EntityInstanceServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/LocationServiceImpl.java
  src/main/java/com/czertainly/core/util/converter/Sql2PredicateConverter.java
Labels: bug

#582 Add unit tests to check correct certificate chain construction
  src/test/java/com/czertainly/core/service/CertValidationServiceTest.java
  src/test/java/com/czertainly/core/service/CertificateValidationTest.java
Labels: enhancement, ignore-for-release

#587 Replace certificate status with certificate state and validation status
  src/main/java/com/czertainly/core/api/v2/client/ClientOperationControllerImpl.java
  src/main/java/com/czertainly/core/dao/entity/Certificate.java
  src/main/java/com/czertainly/core/dao/entity/Location.java
  src/main/java/com/czertainly/core/dao/repository/CertificateRepository.java
  src/main/java/com/czertainly/core/enums/SearchFieldNameEnum.java
  src/main/java/com/czertainly/core/messaging/listeners/ActionListener.java
  src/main/java/com/czertainly/core/messaging/listeners/EventListener.java
  src/main/java/com/czertainly/core/messaging/listeners/NotificationListener.java
  src/main/java/com/czertainly/core/messaging/producers/EventProducer.java
  src/main/java/com/czertainly/core/messaging/producers/NotificationProducer.java
  src/main/java/com/czertainly/core/service/CertificateService.java
  src/main/java/com/czertainly/core/service/LocationService.java
  src/main/java/com/czertainly/core/service/acme/impl/ExtendedAcmeHelperService.java
  src/main/java/com/czertainly/core/service/impl/ApprovalServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/CertificateServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/ClientOperationServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/ComplianceProfileServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/ComplianceServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/DiscoveryServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/LocationServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/NotificationServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/UserManagementServiceImpl.java
  src/main/java/com/czertainly/core/service/scep/impl/ScepServiceImpl.java
  src/main/java/com/czertainly/core/service/v2/ClientOperationService.java
  src/main/java/com/czertainly/core/service/v2/impl/ClientOperationServiceImpl.java
  src/main/java/com/czertainly/core/tasks/UpdateIntuneRevocationRequestsTask.java
  src/main/java/com/czertainly/core/util/CertificateUtil.java
  src/main/java/com/czertainly/core/util/CrlUtil.java
  src/main/java/com/czertainly/core/util/OcspUtil.java
  src/main/java/com/czertainly/core/validation/certificate/ICertificateValidator.java
  src/main/java/com/czertainly/core/validation/certificate/X509CertificateValidator.java
  src/main/resources/db/migration/V202310131425__split_certificate_status.sql
  src/test/java/com/czertainly/core/service/CertificateServiceTest.java
  src/test/java/com/czertainly/core/service/CertificateValidationTest.java
  src/test/java/com/czertainly/core/service/ClientOperationServiceV2Test.java
  src/test/java/com/czertainly/core/service/ComplianceServiceTest.java
  src/test/java/com/czertainly/core/service/LocationServiceTest.java
  src/test/java/com/czertainly/core/service/ScepProfileServiceTest.java
  src/test/java/com/czertainly/core/util/converter/Sql2PredicateConverterTest.java
Labels: new-feature
