Repository CZERTAINLY/CZERTAINLY-Core, pull requests merged in 2024-12, with the labels that each got.

#897 Do not set owner when certificate is requested by protocol user
  src/main/java/com/czertainly/core/service/impl/CertificateServiceImpl.java
Labels: bug

#898 Add headers to refresh token request to forward server hostname for internal OAuth2 provider
  src/main/java/com/czertainly/core/auth/oauth2/CzertainlyOAuth2TokenRequestHeadersConverter.java
  src/main/java/com/czertainly/core/auth/oauth2/OAuth2LoginFilter.java
  src/main/java/com/czertainly/core/config/OAuth2Config.java
  src/main/java/com/czertainly/core/config/SecurityConfig.java
  src/main/java/com/czertainly/core/util/Constants.java
  src/test/java/com/czertainly/core/security/oauth2/CzertainlyClientRegistrationRepositoryTest.java
Labels: enhancement, ignore-for-release

#899 Improve discovery process to update information about status and progress
  src/main/java/com/czertainly/core/config/AsyncConfig.java
  src/main/java/com/czertainly/core/event/transaction/DiscoveryFinishedEvent.java
  src/main/java/com/czertainly/core/event/transaction/DiscoveryProgressEvent.java
  src/main/java/com/czertainly/core/messaging/listeners/EventListener.java
  src/main/java/com/czertainly/core/messaging/listeners/ValidationListener.java
  src/main/java/com/czertainly/core/messaging/producers/EventProducer.java
  src/main/java/com/czertainly/core/service/DiscoveryService.java
  src/main/java/com/czertainly/core/service/handler/CertificateHandler.java
  src/main/java/com/czertainly/core/service/impl/DiscoveryServiceImpl.java
  src/main/java/com/czertainly/core/tasks/DiscoveryCertificateTask.java
  src/test/java/com/czertainly/core/service/SchedulerServiceTest.java
Labels: enhancement

#902 Allow creating OAuth2 Provider for JWT authentication only
  src/main/java/com/czertainly/core/auth/oauth2/CzertainlyClientRegistrationRepository.java
  src/main/java/com/czertainly/core/auth/oauth2/LoginController.java
Labels: enhancement, ignore-for-release

#901 Improve OAuth2 authentication logging and add failures to audit logs
  src/main/java/com/czertainly/core/aop/AuditLogAspect.java
  src/main/java/com/czertainly/core/api/web/AuthControllerImpl.java
  src/main/java/com/czertainly/core/auth/oauth2/CzertainlyAuthenticationSuccessHandler.java
  src/main/java/com/czertainly/core/auth/oauth2/CzertainlyJwtAuthenticationConverter.java
  src/main/java/com/czertainly/core/auth/oauth2/CzertainlyJwtDecoder.java
  src/main/java/com/czertainly/core/auth/oauth2/CzertainlyLogoutSuccessHandler.java
  src/main/java/com/czertainly/core/auth/oauth2/CzertainlyOAuth2FailureHandler.java
  src/main/java/com/czertainly/core/auth/oauth2/CzertainlyOAuth2TokenRequestHeadersConverter.java
  src/main/java/com/czertainly/core/auth/oauth2/LoginController.java
  src/main/java/com/czertainly/core/auth/oauth2/OAuth2LoginFilter.java
  src/main/java/com/czertainly/core/config/SecurityConfig.java
  src/main/java/com/czertainly/core/logging/LoggerWrapper.java
  src/main/java/com/czertainly/core/logging/LoggingHelper.java
  src/main/java/com/czertainly/core/security/authn/CzertainlyAuthenticationFilter.java
  src/main/java/com/czertainly/core/security/authn/CzertainlyAuthenticationProvider.java
  src/main/java/com/czertainly/core/security/authn/client/CzertainlyAuthenticationClient.java
  src/main/java/com/czertainly/core/service/AuditLogService.java
  src/main/java/com/czertainly/core/service/impl/AuditLogServiceImpl.java
  src/main/java/com/czertainly/core/util/AuthHelper.java
  src/main/java/com/czertainly/core/util/OAuth2Constants.java
  src/test/java/com/czertainly/core/security/authn/client/CzertainlyAuthenticationClientTest.java
Labels: enhancement, ignore-for-release

#903 Enhance authentication log and audit log messages with consistent info and debug data
  src/main/java/com/czertainly/core/aop/AuditLogAspect.java
  src/main/java/com/czertainly/core/api/ExceptionHandlingAdvice.java
  src/main/java/com/czertainly/core/auth/oauth2/CzertainlyAuthenticationSuccessHandler.java
  src/main/java/com/czertainly/core/auth/oauth2/CzertainlyJwtAuthenticationConverter.java
  src/main/java/com/czertainly/core/auth/oauth2/CzertainlyJwtDecoder.java
  src/main/java/com/czertainly/core/auth/oauth2/CzertainlyLogoutSuccessHandler.java
  src/main/java/com/czertainly/core/auth/oauth2/CzertainlyOAuth2FailureHandler.java
  src/main/java/com/czertainly/core/auth/oauth2/LoginController.java
  src/main/java/com/czertainly/core/auth/oauth2/OAuth2LoginFilter.java
  src/main/java/com/czertainly/core/logging/LoggerWrapper.java
  src/main/java/com/czertainly/core/logging/LoggingHelper.java
  src/main/java/com/czertainly/core/model/auth/AuthenticationRequestDto.java
  src/main/java/com/czertainly/core/security/authn/CzertainlyAuthenticationFilter.java
  src/main/java/com/czertainly/core/security/authn/client/CzertainlyAuthenticationClient.java
  src/main/java/com/czertainly/core/security/authz/ExternalFilterAuthorizationVoter.java
  src/main/java/com/czertainly/core/security/authz/ExternalMethodAuthorizationVoter.java
  src/main/java/com/czertainly/core/service/AuditLogService.java
  src/main/java/com/czertainly/core/service/impl/AuditLogServiceImpl.java
  src/main/java/com/czertainly/core/util/AuthHelper.java
  src/main/java/com/czertainly/core/util/SearchHelper.java
  src/test/java/com/czertainly/core/security/authz/ExternalFilterAuthorizationVoterTest.java
  src/test/java/com/czertainly/core/security/oauth2/JwtDecoderTest.java
Labels: enhancement, ignore-for-release

#906 Add missing error logs for authentication failed cases
  src/main/java/com/czertainly/core/auth/oauth2/CzertainlyJwtDecoder.java
  src/main/java/com/czertainly/core/security/authn/CzertainlyAuthenticationFilter.java
  src/main/java/com/czertainly/core/security/authn/client/CzertainlyAuthenticationClient.java
  src/main/java/com/czertainly/core/util/AuthHelper.java
Labels: bug, ignore-for-release

#907 Do not create session when user does not exist
  .gitignore
  src/main/java/com/czertainly/core/auth/oauth2/OAuth2LoginFilter.java
Labels: bug, ignore-for-release

#908 Updates for release 2.14.0
  pom.xml
Labels: ignore-for-release
