Repository CZERTAINLY/CZERTAINLY-Core, pull requests merged in 2024-03, with the labels that each got.

#661 Fix transaction in ACME finalizeOrder
  src/main/java/com/czertainly/core/service/acme/impl/ExtendedAcmeHelperService.java
Labels: bug

#662 Initial support for OpenTelemetry SDK
  README.md
  pom.xml
  src/main/java/com/czertainly/core/config/SpanEventsAppender.java
  src/main/resources/application.properties
  src/main/resources/logback-spring.xml
Labels: new-feature

#664 Refactor ACME service
  src/main/java/com/czertainly/core/api/acme/AcmeControllerImpl.java
  src/main/java/com/czertainly/core/api/acme/AcmeRaProfileControllerImpl.java
  src/main/java/com/czertainly/core/config/ProtocolValidationFilter.java
  src/main/java/com/czertainly/core/dao/entity/RaProfile.java
  src/main/java/com/czertainly/core/dao/entity/acme/AcmeAccount.java
  src/main/java/com/czertainly/core/dao/entity/acme/AcmeAuthorization.java
  src/main/java/com/czertainly/core/dao/entity/acme/AcmeChallenge.java
  src/main/java/com/czertainly/core/dao/entity/acme/AcmeOrder.java
  src/main/java/com/czertainly/core/dao/entity/acme/AcmeProfile.java
  src/main/java/com/czertainly/core/dao/repository/AcmeProfileRepository.java
  src/main/java/com/czertainly/core/service/acme/AcmeConstants.java
  src/main/java/com/czertainly/core/service/acme/AcmeRaProfileService.java
  src/main/java/com/czertainly/core/service/acme/AcmeService.java
  src/main/java/com/czertainly/core/service/acme/impl/AcmeRaProfileServiceImpl.java
  src/main/java/com/czertainly/core/service/acme/impl/AcmeServiceImpl.java
  src/main/java/com/czertainly/core/service/acme/impl/ExtendedAcmeHelperService.java
  src/main/java/com/czertainly/core/service/acme/message/AcmeJwsRequest.java
  src/main/java/com/czertainly/core/service/impl/AcmeAccountServiceImpl.java
  src/main/java/com/czertainly/core/util/AcmeRandomGeneratorAndValidator.java
  src/main/java/com/czertainly/core/util/CertificateUtil.java
  src/main/java/com/czertainly/core/util/CsrUtil.java
  src/test/java/com/czertainly/core/AcmeUtilTest.java
  src/test/java/com/czertainly/core/service/AcmeRaProfileServiceTest.java
  src/test/java/com/czertainly/core/service/AcmeServiceTest.java
Labels: enhancement, refactoring

#659 Implement management of rules and their evaluation check
  pom.xml
  src/main/java/com/czertainly/core/api/web/RuleControllerImpl.java
  src/main/java/com/czertainly/core/dao/entity/Rule.java
  src/main/java/com/czertainly/core/dao/entity/RuleAction.java
  src/main/java/com/czertainly/core/dao/entity/RuleActionGroup.java
  src/main/java/com/czertainly/core/dao/entity/RuleCondition.java
  src/main/java/com/czertainly/core/dao/entity/RuleConditionGroup.java
  src/main/java/com/czertainly/core/dao/entity/RuleTrigger.java
  src/main/java/com/czertainly/core/dao/repository/RuleActionGroupRepository.java
  src/main/java/com/czertainly/core/dao/repository/RuleActionRepository.java
  src/main/java/com/czertainly/core/dao/repository/RuleConditionGroupRepository.java
  src/main/java/com/czertainly/core/dao/repository/RuleConditionRepository.java
  src/main/java/com/czertainly/core/dao/repository/RuleRepository.java
  src/main/java/com/czertainly/core/dao/repository/RuleTriggerRepository.java
  src/main/java/com/czertainly/core/enums/ResourceToClass.java
  src/main/java/com/czertainly/core/enums/SearchFieldTypeEnum.java
  src/main/java/com/czertainly/core/evaluator/IRuleEvaluator.java
  src/main/java/com/czertainly/core/evaluator/RuleEvaluator.java
  src/main/java/com/czertainly/core/service/RuleService.java
  src/main/java/com/czertainly/core/service/SearchService.java
  src/main/java/com/czertainly/core/service/impl/AttributeServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/CertificateServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/CryptographicKeyServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/DiscoveryServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/EntityInstanceServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/LocationServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/RuleServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/SearchServiceImpl.java
  src/main/java/com/czertainly/core/util/converter/Sql2PredicateConverter.java
  src/main/resources/db/migration/V202402161122__rules.sql
  src/test/java/com/czertainly/core/evaluator/RuleEvaluatorTest.java
  src/test/java/com/czertainly/core/search/DiscoveryHistorySearchTest.java
  src/test/java/com/czertainly/core/search/EntityInstanceSearchTest.java
  src/test/java/com/czertainly/core/search/LocationsSearchTest.java
  src/test/java/com/czertainly/core/search/SearchFilterRequestDtoDummy.java
  src/test/java/com/czertainly/core/service/RuleServiceTest.java
  src/test/java/com/czertainly/core/util/converter/Sql2PredicateConverterTest.java
Labels: new-feature

#671 Fix name of DB migration file to satisfy Flyway naming convention
  src/main/resources/db/migration/V202403110900__remove_request_notnull.sql
Labels: bug, ignore-for-release

#672 Add filtering on data attributes
  src/main/java/com/czertainly/core/attribute/engine/AttributeEngine.java
  src/main/java/com/czertainly/core/util/converter/Sql2PredicateConverter.java
Labels: new-feature

#674 Remove duplicate response metadata content items from same connector metadata
  src/main/java/com/czertainly/core/attribute/engine/AttributeEngine.java
Labels: bug, ignore-for-release

#675 Add replace content property to metadata attribute definition to replace content for object instead of appending
  src/main/java/com/czertainly/core/attribute/engine/AttributeEngine.java
  src/main/java/com/czertainly/core/dao/entity/AttributeDefinition.java
  src/test/java/com/czertainly/core/attribute/AttributeEngineTest.java
Labels: new-feature

#676 Rename metadata attribute property replaceContent to overwrite
  src/main/java/com/czertainly/core/attribute/engine/AttributeEngine.java
  src/test/java/com/czertainly/core/attribute/AttributeEngineTest.java
Labels: ignore-for-release
