Repository CZERTAINLY/CZERTAINLY-Core, pull requests merged in 2024-04, with the labels that each got.

#677 Update OTEL dependencies
  pom.xml
Labels: dependencies

#682 Extend rule evaluator to perform defined rule actions
  src/main/java/com/czertainly/core/api/ExceptionHandlingAdvice.java
  src/main/java/com/czertainly/core/attribute/engine/AttributeEngine.java
  src/main/java/com/czertainly/core/enums/SearchFieldNameEnum.java
  src/main/java/com/czertainly/core/evaluator/CertificateRuleEvaluator.java
  src/main/java/com/czertainly/core/evaluator/IRuleEvaluator.java
  src/main/java/com/czertainly/core/evaluator/RuleEvaluator.java
  src/main/java/com/czertainly/core/service/CertificateService.java
  src/main/java/com/czertainly/core/service/impl/CertificateServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/ResourceServiceImpl.java
  src/test/java/com/czertainly/core/evaluator/RuleEvaluatorTest.java
Labels: new-feature, ignore-for-release

#684 Add endpoints to list filter fields usable in rule conditions and rule actions
  src/main/java/com/czertainly/core/api/web/ResourceControllerImpl.java
  src/main/java/com/czertainly/core/enums/SearchFieldNameEnum.java
  src/main/java/com/czertainly/core/service/ResourceService.java
  src/main/java/com/czertainly/core/service/impl/ResourceServiceImpl.java
  src/main/java/com/czertainly/core/util/converter/Sql2PredicateConverter.java
Labels: new-feature, ignore-for-release

#688 Allow object access level permissions for custom attributes
  src/main/java/com/czertainly/core/api/ExceptionHandlingAdvice.java
  src/main/java/com/czertainly/core/api/web/CustomAttributeControllerImpl.java
  src/main/java/com/czertainly/core/attribute/engine/AttributeEngine.java
  src/main/java/com/czertainly/core/config/ProtocolValidationFilter.java
  src/main/java/com/czertainly/core/dao/entity/AttributeDefinition.java
  src/main/java/com/czertainly/core/dao/repository/AttributeContent2ObjectRepository.java
  src/main/java/com/czertainly/core/messaging/listeners/ActionListener.java
  src/main/java/com/czertainly/core/model/auth/ResourceAction.java
  src/main/java/com/czertainly/core/security/authz/SecurityResourceFilter.java
  src/main/java/com/czertainly/core/service/AttributeService.java
  src/main/java/com/czertainly/core/service/impl/AttributeServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/ResourceServiceImpl.java
  src/main/java/com/czertainly/core/tasks/DiscoveryCertificateTask.java
  src/main/java/com/czertainly/core/tasks/UpdateIntuneRevocationRequestsTask.java
  src/main/java/com/czertainly/core/util/AuthHelper.java
  src/test/java/com/czertainly/core/evaluator/RuleEvaluatorTest.java
  src/test/java/com/czertainly/core/service/CustomAttributeServiceTest.java
  src/test/resources/application.properties
Labels: enhancement

#698 Remove empty attribute content items and add validation to prevent storing them
  src/main/java/com/czertainly/core/attribute/engine/AttributeEngine.java
  src/main/resources/db/migration/V202404181130__remove_empty_attribute_content_items.sql
Labels: bug

#701 Update validation when creating rules and triggers
  src/main/java/com/czertainly/core/api/web/RuleControllerImpl.java
  src/main/java/com/czertainly/core/dao/entity/RuleActionGroup.java
  src/main/java/com/czertainly/core/dao/entity/RuleConditionGroup.java
  src/main/java/com/czertainly/core/service/RuleService.java
  src/main/java/com/czertainly/core/service/impl/RuleServiceImpl.java
  src/test/java/com/czertainly/core/service/RuleServiceTest.java
Labels: ignore-for-release, refactoring

#704 Add support for CRMF format of certificate request
  src/main/java/com/czertainly/core/api/ExceptionHandlingAdvice.java
  src/main/java/com/czertainly/core/api/web/CertificateControllerImpl.java
  src/main/java/com/czertainly/core/dao/entity/Certificate.java
  src/main/java/com/czertainly/core/dao/entity/CertificateRequestEntity.java
  src/main/java/com/czertainly/core/dao/repository/CertificateRequestRepository.java
  src/main/java/com/czertainly/core/model/request/CertificateRequest.java
  src/main/java/com/czertainly/core/model/request/CrmfCertificateRequest.java
  src/main/java/com/czertainly/core/model/request/Pkcs10CertificateRequest.java
  src/main/java/com/czertainly/core/service/CertificateService.java
  src/main/java/com/czertainly/core/service/acme/impl/AcmeServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/CertificateServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/CryptographicOperationServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/LocationServiceImpl.java
  src/main/java/com/czertainly/core/service/scep/impl/ScepServiceImpl.java
  src/main/java/com/czertainly/core/service/v2/ClientOperationService.java
  src/main/java/com/czertainly/core/service/v2/impl/ClientOperationServiceImpl.java
  src/main/java/com/czertainly/core/util/CertificateRequestUtils.java
  src/main/java/com/czertainly/core/util/CertificateUtil.java
  src/main/java/com/czertainly/core/util/DatabaseMigration.java
  src/main/java/db/migration/V202306141503__CertificateRequest.java
  src/main/java/db/migration/V202311071500__IssuerAndSubjectDnMigration.java
  src/main/resources/db/migration/V202404261700__alter_signature_algorithm_column.sql
  src/test/java/com/czertainly/core/service/ClientOperationServiceV2Test.java
  src/test/java/com/czertainly/core/util/DatabaseMigrationTest.java
Labels: new-feature
