Repository CZERTAINLY/CZERTAINLY-Core, pull requests merged in 2024-09, with the labels that each got.

#841 Fix rules evaluation of triggers with no rules
  src/main/java/com/czertainly/core/evaluator/RuleEvaluator.java
Labels: bug

#842 Load triggers separately in each thread of discovery certificate processing
  src/main/java/com/czertainly/core/service/handler/CertificateHandler.java
  src/main/java/com/czertainly/core/service/impl/DiscoveryServiceImpl.java
Labels: bug, ignore-for-release

#843 Update dependencies minor versions
  .github/workflows/build.yml
  .github/workflows/publish_docker_3key.yaml
  .github/workflows/publish_docker_czertainly.yaml
  .github/workflows/publish_harbor_3key.yaml
  Dockerfile
  Dockerfile-pre
  pom.xml
  src/test/java/com/czertainly/core/service/CertificateValidationTest.java
Labels: dependencies

#846 Fix SonarQube issues in Duplicate certificates migration
  src/main/java/com/czertainly/core/util/DatabaseMigration.java
  src/main/java/db/migration/V202408231055__DuplicateCertificates.java
Labels: bug, ignore-for-release

#847 Update metadata definitions for discovered certificates before their processing
  src/main/java/com/czertainly/core/attribute/engine/AttributeEngine.java
  src/main/java/com/czertainly/core/service/handler/CertificateHandler.java
  src/main/java/com/czertainly/core/service/impl/DiscoveryServiceImpl.java
Labels: bug, ignore-for-release

#849 Updates for release 2.13.0
  README.md
  pom.xml
Labels: ignore-for-release

#853 Fix removing of certificates with null fingerprint in duplicate certificates migration
  src/main/java/com/czertainly/core/util/DatabaseMigration.java
  src/main/java/db/migration/V202408231055__DuplicateCertificates.java
  src/main/resources/application.properties
Labels: bug, ignore-for-release

#854 Release 2.13.0 fix migration
  src/main/java/com/czertainly/core/util/DatabaseMigration.java
  src/main/java/db/migration/V202408231055__DuplicateCertificates.java
  src/main/resources/application.properties
Labels: ignore-for-release

#856 Clean up code related to filtering
  pom.xml
  src/main/java/com/czertainly/core/api/ExceptionHandlingAdvice.java
  src/main/java/com/czertainly/core/api/web/CertificateControllerImpl.java
  src/main/java/com/czertainly/core/dao/repository/SecurityFilterRepositoryImpl.java
  src/main/java/com/czertainly/core/enums/SearchFieldNameEnum.java
  src/main/java/com/czertainly/core/evaluator/CertificateRuleEvaluator.java
  src/main/java/com/czertainly/core/evaluator/RuleEvaluator.java
  src/main/java/com/czertainly/core/service/CertificateEventHistoryService.java
  src/main/java/com/czertainly/core/service/CertificateService.java
  src/main/java/com/czertainly/core/service/SearchService.java
  src/main/java/com/czertainly/core/service/impl/AuditLogServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/CertificateEventHistoryServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/CertificateServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/CryptographicKeyServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/DiscoveryServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/EntityInstanceServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/LocationServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/ResourceServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/SchedulerServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/SearchServiceImpl.java
  src/main/java/com/czertainly/core/util/FilterPredicatesBuilder.java
  src/main/java/com/czertainly/core/util/SearchHelper.java
  src/main/java/com/czertainly/core/util/converter/Sql2PredicateConverter.java
  src/test/java/com/czertainly/core/evaluator/RuleEvaluatorTest.java
  src/test/java/com/czertainly/core/search/DiscoveryHistorySearchTest.java
  src/test/java/com/czertainly/core/search/EntityInstanceSearchTest.java
  src/test/java/com/czertainly/core/search/LocationsSearchTest.java
  src/test/java/com/czertainly/core/service/CertificateServiceTest.java
  src/test/java/com/czertainly/core/util/FilterPredicatesBuilderTest.java
  src/test/java/com/czertainly/core/util/converter/Sql2PredicateConverterTest.java
Labels: ignore-for-release, refactoring

#857 Fix filtering on attributes of non string content types
  src/main/java/com/czertainly/core/util/FilterPredicatesBuilder.java
Labels: bug

#858 Update build action to update snapshots
  .github/workflows/build.yml
  prebuild_image_script
Labels: ignore-for-release

#860 Add Subject type property to certificate and add filter for it
  src/main/java/com/czertainly/core/dao/entity/Certificate.java
  src/main/java/com/czertainly/core/enums/FilterField.java
  src/main/java/com/czertainly/core/service/impl/CertificateServiceImpl.java
  src/main/java/com/czertainly/core/util/CertificateUtil.java
  src/main/java/com/czertainly/core/validation/certificate/X509CertificateValidator.java
  src/main/resources/db/migration/V202409121200__add_certificate_subject_type.sql
  src/test/java/com/czertainly/core/util/FilterPredicatesBuilderTest.java
Labels: enhancement
