Repository CZERTAINLY/CZERTAINLY-Core, pull requests merged in 2024-01, with the labels that each got.

#626 Implement retrieving certificates of authority belonging to RA profile
  src/main/java/com/czertainly/core/api/web/RAProfileManagementControllerImpl.java
  src/main/java/com/czertainly/core/dao/entity/RaProfile.java
  src/main/java/com/czertainly/core/service/RaProfileService.java
  src/main/java/com/czertainly/core/service/impl/CertificateServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/RaProfileServiceImpl.java
  src/main/resources/db/migration/V202312141140__authority_certifcat_uuid.sql
  src/test/java/com/czertainly/core/service/RaProfileServiceTest.java
Labels: new-feature

#631 Prevent infinite loop when iterating through discovered certificates
  src/main/java/com/czertainly/core/service/impl/DiscoveryServiceImpl.java
Labels: bug

#632 Fix handling of not implemented retrieval of CA certificates when creating/updating RA profile
  hooks/build
  src/main/java/com/czertainly/core/api/web/RAProfileManagementControllerImpl.java
  src/main/java/com/czertainly/core/service/RaProfileService.java
  src/main/java/com/czertainly/core/service/impl/RaProfileServiceImpl.java
Labels: bug, ignore-for-release

#634 Allow removing certificate Owner, Group and RA profile
  src/main/java/com/czertainly/core/service/impl/CertificateServiceImpl.java
Labels: enhancement

#635 Fix callback when attribute with callback is part of group attributes
  src/main/java/com/czertainly/core/service/impl/CallbackServiceImpl.java
Labels: bug

#636 Fix validation when adding read only custom attribute to resource
  src/main/java/com/czertainly/core/service/impl/AttributeServiceImpl.java
Labels: bug

#638 Optimize certificate revocation check by processing and storing CA CRLs
  src/main/java/com/czertainly/core/dao/entity/Crl.java
  src/main/java/com/czertainly/core/dao/entity/CrlEntry.java
  src/main/java/com/czertainly/core/dao/entity/CrlEntryId.java
  src/main/java/com/czertainly/core/dao/repository/CertificateRepository.java
  src/main/java/com/czertainly/core/dao/repository/CrlEntryRepository.java
  src/main/java/com/czertainly/core/dao/repository/CrlRepository.java
  src/main/java/com/czertainly/core/service/CrlService.java
  src/main/java/com/czertainly/core/service/impl/CrlServiceImpl.java
  src/main/java/com/czertainly/core/util/CrlUtil.java
  src/main/java/com/czertainly/core/validation/certificate/X509CertificateValidator.java
  src/main/resources/db/migration/V202401171122__ca_crl_management.sql
  src/test/java/com/czertainly/core/service/CertificateValidationTest.java
Labels: new-feature

#640 Fix bulk removal of certificate owner
  src/main/java/com/czertainly/core/service/impl/CertificateServiceImpl.java
Labels: bug, ignore-for-release
