Repository CZERTAINLY/CZERTAINLY-Core, pull requests merged in 2024-06, with the labels that each got.

#757 Support list property in attribute filter fields to allow choosing from content items
  src/main/java/com/czertainly/core/attribute/engine/AttributeEngine.java
  src/main/java/com/czertainly/core/dao/entity/AttributeDefinition.java
  src/main/java/com/czertainly/core/dao/repository/AttributeContent2ObjectRepository.java
  src/main/java/com/czertainly/core/dao/repository/AttributeDefinitionRepository.java
  src/main/java/com/czertainly/core/model/SearchFieldObject.java
  src/main/java/com/czertainly/core/service/impl/DiscoveryServiceImpl.java
  src/main/java/com/czertainly/core/util/SearchHelper.java
  src/main/java/com/czertainly/core/util/converter/Sql2PredicateConverter.java
Labels: enhancement

#758 Include update of NULL attribute UUIDs
  src/main/java/com/czertainly/core/util/DatabaseMigration.java
  src/main/java/db/migration/V202402171510__UpdateAndOptimizeAttributesModelMigration.java
Labels: bug, ignore-for-release

#759 Make bulk delete certificates operation transactional per certificate
  src/main/java/com/czertainly/core/service/impl/CertificateServiceImpl.java
  src/test/java/com/czertainly/core/service/CertificateServiceTest.java
Labels: bug

#765 Fix signature algorithm protection for CMP response
  src/main/java/com/czertainly/core/service/cmp/configurations/variants/CmpConfigurationContext.java
  src/main/java/com/czertainly/core/service/cmp/message/protection/impl/SingatureBaseProtectionStrategy.java
  src/main/java/com/czertainly/core/service/cmp/message/validator/impl/ProtectionSignatureValidator.java
  src/main/java/com/czertainly/core/service/cmp/message/validator/impl/ProtectionValidator.java
Labels: bug

#766 Fix digest calculation in CMP certConf handler
  src/main/java/com/czertainly/core/service/cmp/message/handler/CertConfirmMessageHandler.java
  src/test/java/com/czertainly/core/service/cmp/message/handler/CertConfirmMessageHandlerITest.java
Labels: bug, ignore-for-release

#770 Add CMP profile protection methods to its mapping to detail DTO
  src/main/java/com/czertainly/core/dao/entity/cmp/CmpProfile.java
Labels: bug, ignore-for-release

#769 Fix CMP error handling and improvements
  src/main/java/com/czertainly/core/service/cmp/configurations/ConfigurationContext.java
  src/main/java/com/czertainly/core/service/cmp/configurations/variants/Mobile3gppProfileContext.java
  src/main/java/com/czertainly/core/service/cmp/impl/CmpServiceImpl.java
  src/main/java/com/czertainly/core/service/cmp/message/CertificateKeyService.java
  src/main/java/com/czertainly/core/service/cmp/message/CertificateKeyServiceImpl.java
  src/main/java/com/czertainly/core/service/cmp/message/CmpTransactionService.java
  src/main/java/com/czertainly/core/service/cmp/message/PkiMessageDumper.java
  src/main/java/com/czertainly/core/service/cmp/message/builder/HeaderTemplate.java
  src/main/java/com/czertainly/core/service/cmp/message/builder/PkiMessageBuilder.java
  src/main/java/com/czertainly/core/service/cmp/message/handler/CrmfIrCrMessageHandler.java
  src/main/java/com/czertainly/core/service/cmp/message/handler/CrmfKurMessageHandler.java
  src/main/java/com/czertainly/core/service/cmp/message/handler/CrmfMessageHandler.java
  src/main/java/com/czertainly/core/service/cmp/message/handler/MessageHandler.java
  src/main/java/com/czertainly/core/service/cmp/message/handler/PollFeature.java
  src/main/java/com/czertainly/core/service/cmp/message/handler/RevocationMessageHandler.java
  src/main/java/com/czertainly/core/service/cmp/message/protection/ProtectionStrategy.java
  src/main/java/com/czertainly/core/service/cmp/message/protection/impl/PasswordBasedMacProtectionStrategy.java
  src/main/java/com/czertainly/core/service/cmp/message/validator/BiValidator.java
  src/main/java/com/czertainly/core/service/cmp/message/validator/Validator.java
  src/main/java/com/czertainly/core/service/cmp/message/validator/impl/BaseValidator.java
  src/main/java/com/czertainly/core/service/cmp/message/validator/impl/BodyCertConfValidator.java
  src/main/java/com/czertainly/core/service/cmp/message/validator/impl/BodyCertReqResValidator.java
  src/main/java/com/czertainly/core/service/cmp/message/validator/impl/BodyErrorMessageValidator.java
  src/main/java/com/czertainly/core/service/cmp/message/validator/impl/BodyRevocationValidator.java
  src/main/java/com/czertainly/core/service/cmp/message/validator/impl/BodyValidator.java
  src/main/java/com/czertainly/core/service/cmp/message/validator/impl/HeaderValidator.java
  src/main/java/com/czertainly/core/service/cmp/message/validator/impl/POPSigningKeyCertTemplateValidator.java
  src/main/java/com/czertainly/core/service/cmp/message/validator/impl/POPSigningKeyPoposkInputValidator.java
  src/main/java/com/czertainly/core/service/cmp/message/validator/impl/POPValidator.java
  src/main/java/com/czertainly/core/service/cmp/message/validator/impl/ProtectionMacValidator.java
  src/main/java/com/czertainly/core/service/cmp/message/validator/impl/ProtectionPBMac1Validator.java
  src/main/java/com/czertainly/core/service/impl/ResourceServiceImpl.java
  src/main/resources/application.properties
  src/test/resources/application.properties
Labels: ignore-for-release
