Repository CZERTAINLY/CZERTAINLY-Core, pull requests merged in 2024-11, with the labels that each got.

#876 Fix bulk removal of certificate owner
  src/main/java/com/czertainly/core/api/web/CertificateControllerImpl.java
  src/main/java/com/czertainly/core/service/CertificateService.java
  src/main/java/com/czertainly/core/service/impl/CertificateServiceImpl.java
Labels: bug

#880 Fix ACME finding an account URL given a key
  src/main/java/com/czertainly/core/service/acme/impl/AcmeServiceImpl.java
  src/test/java/com/czertainly/core/service/AcmeServiceTest.java
Labels: bug

#885 Fix audit logs search filters not providing values for enum fields
  src/main/java/com/czertainly/core/service/impl/AuditLogServiceImpl.java
  src/main/java/com/czertainly/core/util/SearchHelper.java
Labels: bug, ignore-for-release

#889 Add validation to prevent issuing certificate with disabled RA profile
  src/main/java/com/czertainly/core/service/v2/impl/ClientOperationServiceImpl.java
  src/test/java/com/czertainly/core/service/ClientOperationServiceV2Test.java
Labels: bug

#890 Set empty common name string when common name is missing in certificate request
  src/main/java/com/czertainly/core/dao/entity/Certificate.java
  src/main/java/com/czertainly/core/dao/entity/CertificateContent.java
  src/main/java/com/czertainly/core/dao/entity/CertificateProtocolAssociation.java
  src/main/java/com/czertainly/core/dao/entity/CertificateRequestEntity.java
Labels: bug

#891 Add filter fields allowing filtering by value at specified JSON path
  src/main/java/com/czertainly/core/enums/FilterField.java
  src/main/java/com/czertainly/core/service/impl/ResourceServiceImpl.java
  src/main/java/com/czertainly/core/util/FilterPredicatesBuilder.java
Labels: enhancement

#893 Use SettingsCache in NotificationListener to retrieve notifications settings
  src/main/java/com/czertainly/core/messaging/listeners/NotificationListener.java
Labels: bug, ignore-for-release

#894 Split OAuth2Provider settings DTOs to update and get DTO
  src/main/java/com/czertainly/core/api/web/SettingControllerImpl.java
  src/main/java/com/czertainly/core/auth/oauth2/CzertainlyClientRegistrationRepository.java
  src/main/java/com/czertainly/core/auth/oauth2/LoginController.java
  src/main/java/com/czertainly/core/auth/oauth2/OAuth2LoginFilter.java
  src/main/java/com/czertainly/core/config/SecurityConfig.java
  src/main/java/com/czertainly/core/security/authn/client/CzertainlyAuthenticationClient.java
  src/main/java/com/czertainly/core/service/SettingService.java
  src/main/java/com/czertainly/core/service/impl/SettingServiceImpl.java
  src/test/java/com/czertainly/core/security/oauth2/CzertainlyClientRegistrationRepositoryTest.java
  src/test/java/com/czertainly/core/security/oauth2/JwtDecoderTest.java
Labels: enhancement, ignore-for-release

#895 Seed missing resources in localhost user migration
  src/main/java/com/czertainly/core/util/DatabaseAuthMigration.java
  src/main/java/com/czertainly/core/util/DatabaseMigration.java
  src/main/java/db/migration/V202411141900__CreateLocalhostUserAndPermissions.java
Labels: bug, ignore-for-release
