Repository CZERTAINLY/CZERTAINLY-Core, pull requests merged in 2024-07, with the labels that each got.

#779 Update mapping trigger to detail DTO
  src/main/java/com/czertainly/core/dao/entity/workflows/Trigger.java
Labels: ignore-for-release

#781 Improve performance of audit log purge
  src/main/java/com/czertainly/core/service/impl/AuditLogServiceImpl.java
  src/main/java/com/czertainly/core/util/converter/Sql2PredicateConverter.java
Labels: enhancement

#776 Link protocol information and certificate that was issued and managed through the protocol
  src/main/java/com/czertainly/core/api/v2/client/ClientOperationControllerImpl.java
  src/main/java/com/czertainly/core/api/web/CertificateControllerImpl.java
  src/main/java/com/czertainly/core/dao/entity/Certificate.java
  src/main/java/com/czertainly/core/dao/entity/CertificateProtocolAssociation.java
  src/main/java/com/czertainly/core/dao/repository/CertificateProtocolAssociationRepository.java
  src/main/java/com/czertainly/core/model/auth/CertificateProtocolInfo.java
  src/main/java/com/czertainly/core/service/CertificateService.java
  src/main/java/com/czertainly/core/service/acme/impl/AcmeServiceImpl.java
  src/main/java/com/czertainly/core/service/cmp/message/handler/CrmfIrCrMessageHandler.java
  src/main/java/com/czertainly/core/service/impl/AcmeProfileServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/CertificateServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/LocationServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/RaProfileServiceImpl.java
  src/main/java/com/czertainly/core/service/scep/impl/ScepServiceImpl.java
  src/main/java/com/czertainly/core/service/v2/ClientOperationService.java
  src/main/java/com/czertainly/core/service/v2/impl/ClientOperationServiceImpl.java
  src/main/resources/db/migration/V202406181200__create_protocol_certificate_association.sql
  src/test/java/com/czertainly/core/service/ClientOperationServiceV2Test.java
Labels: bug, enhancement

#791 Update OpenTelemetry dependencies and tracing
  pom.xml
  src/main/java/com/czertainly/core/aop/TracingAspect.java
Labels: enhancement, dependencies

#788 Implement editing of CRON expression of scheduled job
  src/main/java/com/czertainly/core/api/web/SchedulerControllerImpl.java
  src/main/java/com/czertainly/core/service/SchedulerService.java
  src/main/java/com/czertainly/core/service/impl/SchedulerServiceImpl.java
Labels: enhancement

#800 Calculate certificate statistics parallely to improve dashboard response time
  pom.xml
  src/main/java/com/czertainly/core/service/impl/CertificateServiceImpl.java
Labels: enhancement

#801 Remove join fetch associations in certificates and keys inventory to avoid in memory pagination
  src/main/java/com/czertainly/core/service/impl/CertificateServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/CryptographicKeyServiceImpl.java
Labels: bug, enhancement

#797 Fix processing of discovery in transaction
  src/main/java/com/czertainly/core/event/transaction/DiscoveryFinishedEvent.java
  src/main/java/com/czertainly/core/service/impl/CertificateServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/DiscoveryServiceImpl.java
Labels: bug

#808 Prevent using file system when downloading certificate from AIA URL
  src/main/java/com/czertainly/core/service/impl/CertificateServiceImpl.java
Labels: bug
