Repository CZERTAINLY/CZERTAINLY-Core, pull requests merged in 2024-08, with the labels that each got.

#810 Add foreign key cascade for CRL CA certificate
  src/main/resources/db/migration/V202408011622__ca_crl_foreign_key_constraint.sql
Labels: enhancement

#815 Handle discovered certificates in parallel batches in separate transaction with reported progress
  pom.xml
  src/main/java/com/czertainly/core/Application.java
  src/main/java/com/czertainly/core/config/AsyncConfig.java
  src/main/java/com/czertainly/core/dao/entity/DiscoveryCertificate.java
  src/main/java/com/czertainly/core/dao/repository/CertificateContentRepository.java
  src/main/java/com/czertainly/core/dao/repository/CertificateRepository.java
  src/main/java/com/czertainly/core/dao/repository/DiscoveryCertificateRepository.java
  src/main/java/com/czertainly/core/event/transaction/DiscoveryProgressEvent.java
  src/main/java/com/czertainly/core/service/CertificateService.java
  src/main/java/com/czertainly/core/service/acme/impl/AcmeServiceImpl.java
  src/main/java/com/czertainly/core/service/handler/DiscoveryCertificateHandler.java
  src/main/java/com/czertainly/core/service/impl/CertificateEventHistoryServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/CertificateServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/CryptographicKeyEventHistoryServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/DiscoveryServiceImpl.java
  src/main/java/com/czertainly/core/util/CertificateUtil.java
  src/main/resources/db/migration/V202408061000__add_processed_flag_to_discovery_certificate.sql
Labels: enhancement

#816 Update default value for maximum pool size for DB connections
  src/main/resources/application.properties
Labels: enhancement

#817 Fix toString() method of SecuredUuid to handle null UUID value
  src/main/java/com/czertainly/core/security/authz/SecuredUUID.java
Labels: bug

#820 Handle bulk validation of certificates in separate queue
  src/main/java/com/czertainly/core/dao/entity/Certificate.java
  src/main/java/com/czertainly/core/dao/repository/CertificateRepository.java
  src/main/java/com/czertainly/core/event/transaction/CertificateValidationEvent.java
  src/main/java/com/czertainly/core/messaging/configuration/RabbitMQConfiguration.java
  src/main/java/com/czertainly/core/messaging/configuration/RabbitMQConstants.java
  src/main/java/com/czertainly/core/messaging/listeners/ValidationListener.java
  src/main/java/com/czertainly/core/messaging/model/ValidationMessage.java
  src/main/java/com/czertainly/core/messaging/producers/ValidationProducer.java
  src/main/java/com/czertainly/core/service/handler/CertificateHandler.java
  src/main/java/com/czertainly/core/service/impl/CertificateServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/DiscoveryServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/LocationServiceImpl.java
  src/main/java/com/czertainly/core/validation/certificate/X509CertificateValidator.java
Labels: enhancement

#821 Fix filtering of objects by access control based on owner association
  src/main/java/com/czertainly/core/dao/repository/SecurityFilterRepositoryImpl.java
Labels: bug

#822 Fix mismatch between Total Certificates Discovered and content of List of Certificates
  src/main/java/com/czertainly/core/service/impl/DiscoveryServiceImpl.java
Labels: bug

#824 Add processed flag and processed error properties to DiscoveryCertificateDto
  src/main/java/com/czertainly/core/dao/entity/DiscoveryCertificate.java
Labels: enhancement, ignore-for-release

#828 Fix DB connection pool starvation in discovery process
  src/main/java/com/czertainly/core/messaging/listeners/EventListener.java
  src/main/java/com/czertainly/core/service/handler/CertificateHandler.java
  src/main/java/com/czertainly/core/service/impl/DiscoveryServiceImpl.java
Labels: bug, ignore-for-release

#835 Correct logging level in DuplicateCertificates Java migration
  src/main/java/com/czertainly/core/util/DatabaseMigration.java
  src/main/java/db/migration/V202408231055__DuplicateCertificates.java
Labels: bug, ignore-for-release

#836 Handle validation of issued certificate after process from separate queue
  src/main/java/com/czertainly/core/service/handler/CertificateHandler.java
  src/main/java/com/czertainly/core/service/impl/CertificateServiceImpl.java
Labels: enhancement

#837 Fix credential listing in callback throwing 404 instead of empty list
  src/main/java/com/czertainly/core/service/CoreCallbackService.java
  src/main/java/com/czertainly/core/service/CredentialService.java
  src/main/java/com/czertainly/core/service/impl/CoreCallbackServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/CredentialServiceImpl.java
  src/test/java/com/czertainly/core/service/CoreCallbackServiceTest.java
Labels: bug

#840 Fix and refactor inventory items filtering
  src/main/java/com/czertainly/core/attribute/engine/AttributeEngine.java
  src/main/java/com/czertainly/core/dao/repository/SecurityFilterRepository.java
  src/main/java/com/czertainly/core/dao/repository/SecurityFilterRepositoryImpl.java
  src/main/java/com/czertainly/core/enums/FilterField.java
  src/main/java/com/czertainly/core/enums/ResourceToClass.java
  src/main/java/com/czertainly/core/enums/SearchFieldNameEnum.java
  src/main/java/com/czertainly/core/enums/SearchFieldTypeEnum.java
  src/main/java/com/czertainly/core/model/SearchFieldObject.java
  src/main/java/com/czertainly/core/service/impl/ApprovalServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/AttributeServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/CertificateServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/CredentialServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/CryptographicKeyServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/DiscoveryServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/EntityInstanceServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/LocationServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/RaProfileServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/SchedulerServiceImpl.java
  src/main/java/com/czertainly/core/util/FilterPredicatesBuilder.java
  src/main/java/com/czertainly/core/util/SearchHelper.java
  src/test/java/com/czertainly/core/evaluator/RuleEvaluatorTest.java
  src/test/java/com/czertainly/core/search/DiscoveryHistorySearchTest.java
  src/test/java/com/czertainly/core/search/EntityInstanceSearchTest.java
  src/test/java/com/czertainly/core/search/LocationsSearchTest.java
  src/test/java/com/czertainly/core/util/FilterPredicatesBuilderTest.java
  src/test/java/com/czertainly/core/util/converter/Sql2PredicateConverterTest.java
Labels: bug, refactoring

#838 Fix checksum and attributes in duplicate certificates migration
  src/main/java/com/czertainly/core/dao/repository/CrlEntryRepository.java
  src/main/java/com/czertainly/core/service/CrlService.java
  src/main/java/com/czertainly/core/service/impl/CrlServiceImpl.java
  src/main/java/com/czertainly/core/util/DatabaseMigration.java
  src/main/java/db/migration/V202408231055__DuplicateCertificates.java
Labels: bug, ignore-for-release

#839 Add info endpoint to provide information about CZERTAINLY application
  src/main/java/com/czertainly/core/api/DatabaseInfoContributor.java
  src/main/resources/application.properties
Labels: enhancement
