Repository CZERTAINLY/CZERTAINLY-Core, pull requests merged in 2024-05, with the labels that each got.

#708 Fix retrieving data attributes by name and UUID together
  src/main/java/com/czertainly/core/attribute/engine/AttributeEngine.java
  src/main/java/com/czertainly/core/dao/repository/AttributeDefinitionRepository.java
  src/test/java/com/czertainly/core/service/ClientOperationServiceV1Test.java
  src/test/java/com/czertainly/core/service/ClientOperationServiceV2Test.java
  src/test/java/com/czertainly/core/service/LocationServiceTest.java
Labels: bug, ignore-for-release

#709 Fix creating and updating of triggers
  src/main/java/com/czertainly/core/service/impl/RuleServiceImpl.java
Labels: bug, ignore-for-release

#711 Add resource listing and update event listing response
  src/main/java/com/czertainly/core/api/web/AuthControllerImpl.java
  src/main/java/com/czertainly/core/api/web/ResourceControllerImpl.java
  src/main/java/com/czertainly/core/messaging/listeners/EventListener.java
  src/main/java/com/czertainly/core/messaging/producers/EventProducer.java
  src/main/java/com/czertainly/core/security/authn/client/ResourceApiClient.java
  src/main/java/com/czertainly/core/service/AuthService.java
  src/main/java/com/czertainly/core/service/ResourceService.java
  src/main/java/com/czertainly/core/service/impl/AuthServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/DiscoveryServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/ResourceServiceImpl.java
Labels: enhancement

#716 Fix performing set field trigger action for custom attributes and unsetting of certificate property
  src/main/java/com/czertainly/core/attribute/engine/AttributeEngine.java
  src/main/java/com/czertainly/core/dao/entity/RuleAction.java
  src/main/java/com/czertainly/core/dao/entity/RuleTrigger.java
  src/main/java/com/czertainly/core/dao/repository/AttributeContent2ObjectRepository.java
  src/main/java/com/czertainly/core/enums/SearchFieldNameEnum.java
  src/main/java/com/czertainly/core/evaluator/CertificateRuleEvaluator.java
  src/main/java/com/czertainly/core/evaluator/RuleEvaluator.java
  src/main/java/com/czertainly/core/service/impl/CertificateServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/CryptographicKeyServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/DiscoveryServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/EntityInstanceServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/LocationServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/ResourceServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/RuleServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/UserManagementServiceImpl.java
  src/test/java/com/czertainly/core/evaluator/RuleEvaluatorTest.java
Labels: bug, ignore-for-release

#717 Add associated triggers to discovery detail
  src/main/java/com/czertainly/core/dao/entity/DiscoveryHistory.java
  src/main/java/com/czertainly/core/dao/entity/RuleTrigger2Object.java
  src/main/java/com/czertainly/core/dao/repository/Object2TriggerRepository.java
  src/main/java/com/czertainly/core/service/impl/DiscoveryServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/RuleServiceImpl.java
Labels: enhancement, ignore-for-release

#718 Allow assigning multiple groups to certificate, keys and users
  src/main/java/com/czertainly/core/attribute/engine/AttributeEngine.java
  src/main/java/com/czertainly/core/dao/entity/AssociationType.java
  src/main/java/com/czertainly/core/dao/entity/Certificate.java
  src/main/java/com/czertainly/core/dao/entity/CryptographicKey.java
  src/main/java/com/czertainly/core/dao/entity/CryptographicKeyItem.java
  src/main/java/com/czertainly/core/dao/entity/GroupAssociation.java
  src/main/java/com/czertainly/core/dao/entity/OwnerAssociation.java
  src/main/java/com/czertainly/core/dao/entity/ResourceObjectAssociation.java
  src/main/java/com/czertainly/core/dao/repository/CertificateRepository.java
  src/main/java/com/czertainly/core/dao/repository/GroupAssociationRepository.java
  src/main/java/com/czertainly/core/dao/repository/OwnerAssociationRepository.java
  src/main/java/com/czertainly/core/dao/repository/SecurityFilterRepositoryImpl.java
  src/main/java/com/czertainly/core/enums/SearchFieldNameEnum.java
  src/main/java/com/czertainly/core/evaluator/CertificateRuleEvaluator.java
  src/main/java/com/czertainly/core/evaluator/RuleEvaluator.java
  src/main/java/com/czertainly/core/messaging/model/NotificationRecipient.java
  src/main/java/com/czertainly/core/messaging/producers/NotificationProducer.java
  src/main/java/com/czertainly/core/service/CertificateService.java
  src/main/java/com/czertainly/core/service/ResourceObjectAssociationService.java
  src/main/java/com/czertainly/core/service/impl/ApprovalServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/CertificateServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/CryptographicKeyServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/GroupServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/NotificationServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/ResourceObjectAssociationServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/ResourceServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/UserManagementServiceImpl.java
  src/main/java/com/czertainly/core/service/v2/impl/ClientOperationServiceImpl.java
  src/main/java/com/czertainly/core/util/DatabaseAuthMigration.java
  src/main/java/com/czertainly/core/util/DatabaseMigration.java
  src/main/java/com/czertainly/core/util/converter/Sql2PredicateConverter.java
  src/main/java/db/migration/V202404120915__AssignObjectsOwnerAndMultipleGroupsMigration.java
  src/test/java/com/czertainly/core/evaluator/RuleEvaluatorTest.java
  src/test/java/com/czertainly/core/service/CertificateServiceTest.java
Labels: enhancement

#722 Fix delete of discovery that has certificate referenced in other discoveries
  src/main/java/com/czertainly/core/service/impl/DiscoveryServiceImpl.java
Labels: bug

#723 Fix filtering when filter condition does not have entered value
  src/main/java/com/czertainly/core/util/converter/Sql2PredicateConverter.java
Labels: bug

#725 Fix unit tests to run in multiple environments
  src/test/java/com/czertainly/core/evaluator/RuleEvaluatorTest.java
  src/test/resources/application.properties
Labels: enhancement, ignore-for-release

#726 Allow objects access based on groups membership and owner
  src/main/java/com/czertainly/core/api/web/CryptographicKeyControllerImpl.java
  src/main/java/com/czertainly/core/dao/entity/OwnerAssociation.java
  src/main/java/com/czertainly/core/dao/repository/OwnerAssociationRepository.java
  src/main/java/com/czertainly/core/dao/repository/SecurityFilterRepositoryImpl.java
  src/main/java/com/czertainly/core/security/authz/ExternalMethodAuthorizationVoter.java
  src/main/java/com/czertainly/core/security/authz/ObjectFilterAspect.java
  src/main/java/com/czertainly/core/security/authz/SecurityFilter.java
  src/main/java/com/czertainly/core/security/authz/SecurityResourceFilter.java
  src/main/java/com/czertainly/core/service/CryptographicKeyService.java
  src/main/java/com/czertainly/core/service/RaProfileService.java
  src/main/java/com/czertainly/core/service/impl/CertificateServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/CryptographicKeyServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/GroupServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/RaProfileServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/TokenProfileServiceImpl.java
  src/main/java/com/czertainly/core/util/AuthHelper.java
  src/main/java/com/czertainly/core/util/converter/Sql2PredicateConverter.java
  src/test/java/com/czertainly/core/service/CryptographicKeyServiceTest.java
Labels: new-feature

#727 Fix lazy loading of certificate content
  src/main/java/com/czertainly/core/dao/repository/CertificateRepository.java
  src/main/java/com/czertainly/core/service/v2/impl/ClientOperationServiceImpl.java
Labels: bug

#728 Fix client operations certificate request handling
  src/main/java/com/czertainly/core/api/ExceptionHandlingAdvice.java
  src/main/java/com/czertainly/core/api/v2/client/ClientOperationControllerImpl.java
  src/main/java/com/czertainly/core/model/request/CrmfCertificateRequest.java
  src/main/java/com/czertainly/core/model/request/Pkcs10CertificateRequest.java
  src/main/java/com/czertainly/core/service/impl/LocationServiceImpl.java
  src/main/java/com/czertainly/core/service/scep/impl/ScepServiceImpl.java
  src/main/java/com/czertainly/core/service/v2/ClientOperationService.java
  src/main/java/com/czertainly/core/service/v2/impl/ClientOperationServiceImpl.java
  src/main/java/com/czertainly/core/util/CertificateRequestUtils.java
Labels: bug, ignore-for-release

#731 Improve discovery process logging
  src/main/java/com/czertainly/core/service/impl/DiscoveryServiceImpl.java
Labels: enhancement, ignore-for-release

#732 Fix SCEP context URL in RA Profile
  src/main/java/com/czertainly/core/dao/entity/RaProfile.java
Labels: bug

#733 Fix fetching certificate relations in transaction of scheduled certificate validation
  src/main/java/com/czertainly/core/dao/repository/CertificateRepository.java
  src/main/java/com/czertainly/core/service/impl/CertificateServiceImpl.java
Labels: bug, ignore-for-release

#729 Add trigger history to store details and results of trigger evaluations
  src/main/java/com/czertainly/core/api/web/RuleControllerImpl.java
  src/main/java/com/czertainly/core/dao/entity/RuleTriggerHistory.java
  src/main/java/com/czertainly/core/dao/entity/RuleTriggerHistoryRecord.java
  src/main/java/com/czertainly/core/dao/repository/DiscoveryRepository.java
  src/main/java/com/czertainly/core/dao/repository/RuleTriggerHistoryRecordRepository.java
  src/main/java/com/czertainly/core/dao/repository/RuleTriggerHistoryRepository.java
  src/main/java/com/czertainly/core/evaluator/IRuleEvaluator.java
  src/main/java/com/czertainly/core/evaluator/RuleEvaluator.java
  src/main/java/com/czertainly/core/service/RuleService.java
  src/main/java/com/czertainly/core/service/impl/DiscoveryServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/RuleServiceImpl.java
  src/main/resources/db/migration/V202405161019__rule_trigger_history.sql
  src/test/java/com/czertainly/core/evaluator/RuleEvaluatorTest.java
Labels: enhancement, ignore-for-release

#734 Fix certificate chain validation check to include check for CA flag when certificate is self-signed
  src/main/java/com/czertainly/core/messaging/listeners/EventListener.java
  src/main/java/com/czertainly/core/service/impl/CertificateServiceImpl.java
  src/main/java/com/czertainly/core/util/CertificateUtil.java
  src/main/java/com/czertainly/core/validation/certificate/X509CertificateValidator.java
  src/main/resources/db/migration/V202405221400__add_trusted_self_signed_certificates.sql
Labels: bug

#735 Add record for unmatched condition and add reference object to each trigger history
  src/main/java/com/czertainly/core/evaluator/RuleEvaluator.java
  src/main/java/com/czertainly/core/service/impl/DiscoveryServiceImpl.java
Labels: enhancement, ignore-for-release

#737 Fix wrong datetime in certificate history by changing timestamp property to include time zone
  src/main/java/com/czertainly/core/dao/entity/Audited.java
  src/main/java/com/czertainly/core/dao/entity/CertificateEventHistory.java
  src/main/java/com/czertainly/core/dao/entity/CertificateLocation.java
  src/main/java/com/czertainly/core/service/impl/AuditLogServiceImpl.java
  src/test/java/com/czertainly/core/search/EntityInstanceSearchTest.java
  src/test/java/com/czertainly/core/search/LocationsSearchTest.java
  src/test/java/com/czertainly/core/util/UriParamsBuilderTest.java
Labels: bug

#738 Add access control annotations to workflows services
  src/main/java/com/czertainly/core/model/auth/Resource.java
  src/main/java/com/czertainly/core/service/impl/ActionServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/RuleServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/TriggerServiceImpl.java
Labels: enhancement, ignore-for-release

#739 Get trigger history summary for trigger association object
  src/main/java/com/czertainly/core/api/web/TriggerControllerImpl.java
  src/main/java/com/czertainly/core/dao/entity/workflows/TriggerHistory.java
  src/main/java/com/czertainly/core/dao/entity/workflows/TriggerHistoryRecord.java
  src/main/java/com/czertainly/core/dao/repository/workflows/TriggerHistoryRepository.java
  src/main/java/com/czertainly/core/evaluator/RuleEvaluator.java
  src/main/java/com/czertainly/core/service/TriggerService.java
  src/main/java/com/czertainly/core/service/impl/ActionServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/DiscoveryServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/TriggerServiceImpl.java
Labels: enhancement, ignore-for-release

#740 Deleting discovery should delete associated triggers and their history
  src/main/java/com/czertainly/core/dao/repository/workflows/TriggerHistoryRepository.java
  src/main/java/com/czertainly/core/service/TriggerService.java
  src/main/java/com/czertainly/core/service/impl/DiscoveryServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/TriggerServiceImpl.java
Labels: bug, ignore-for-release

#745 Refactor and fix loading discovery trigger associations in async context
  src/main/java/com/czertainly/core/api/web/DiscoveryControllerImpl.java
  src/main/java/com/czertainly/core/dao/repository/workflows/TriggerHistoryRepository.java
  src/main/java/com/czertainly/core/service/DiscoveryService.java
  src/main/java/com/czertainly/core/service/impl/DiscoveryServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/TriggerServiceImpl.java
  src/main/java/com/czertainly/core/tasks/DiscoveryCertificateTask.java
  src/test/java/com/czertainly/core/service/DiscoveryServiceTest.java
  src/test/java/com/czertainly/core/service/RuleServiceTest.java
Labels: bug, ignore-for-release

#746 Fix missing object UUID in ignore trigger evaluated certificates history
  src/main/java/com/czertainly/core/service/impl/DiscoveryServiceImpl.java
Labels: bug, ignore-for-release

#747 Fix issuing certificate when using existing key
  src/main/java/com/czertainly/core/messaging/listeners/ActionListener.java
  src/main/java/com/czertainly/core/service/v2/impl/ClientOperationServiceImpl.java
Labels: bug, ignore-for-release

#744 Add support for certificates with LDAP protocol
  src/main/java/com/czertainly/core/service/impl/CertificateServiceImpl.java
  src/main/java/com/czertainly/core/util/CertificateUtil.java
  src/main/java/com/czertainly/core/util/CrlUtil.java
Labels: enhancement

#752 Fix sending notification of discovery finished after processing completes
  src/main/java/com/czertainly/core/messaging/listeners/EventListener.java
  src/main/java/com/czertainly/core/service/DiscoveryService.java
  src/main/java/com/czertainly/core/service/impl/DiscoveryServiceImpl.java
Labels: bug, ignore-for-release

#753 Fix updating definitions of custom attributes and global metadata
  src/main/java/com/czertainly/core/service/impl/AttributeServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/ResourceServiceImpl.java
Labels: bug

#756 Prevent deleting actions, rules, executions and conditions when associated with other object
  src/main/java/com/czertainly/core/dao/entity/workflows/Action.java
  src/main/java/com/czertainly/core/dao/entity/workflows/Condition.java
  src/main/java/com/czertainly/core/dao/entity/workflows/Execution.java
  src/main/java/com/czertainly/core/dao/entity/workflows/Rule.java
  src/main/java/com/czertainly/core/dao/repository/workflows/ActionRepository.java
  src/main/java/com/czertainly/core/dao/repository/workflows/ConditionRepository.java
  src/main/java/com/czertainly/core/dao/repository/workflows/ExecutionRepository.java
  src/main/java/com/czertainly/core/dao/repository/workflows/RuleRepository.java
  src/main/java/com/czertainly/core/service/impl/ActionServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/CertificateServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/RuleServiceImpl.java
Labels: ignore-for-release
