Repository CZERTAINLY/CZERTAINLY-Core, pull requests merged in 2024-02, with the labels that each got.

#642 Fix missing status attribute when updating entity
  src/main/java/com/czertainly/core/service/impl/ClientOperationServiceImpl.java
Labels: bug

#643 Create already enabled key by specifying enabled property in request
  src/main/java/com/czertainly/core/service/impl/CryptographicKeyServiceImpl.java
Labels: enhancement

#644 Fix sending internal and external notifications for group recipient
  src/main/java/com/czertainly/core/messaging/listeners/NotificationListener.java
  src/main/java/com/czertainly/core/messaging/producers/NotificationProducer.java
  src/main/java/com/czertainly/core/service/impl/NotificationServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/RoleManagementServiceImpl.java
Labels: bug

#645 Fix SonarQube bugs
  src/main/java/com/czertainly/core/service/impl/CrlServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/NotificationServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/RaProfileServiceImpl.java
  src/main/java/com/czertainly/core/validation/certificate/X509CertificateValidator.java
Labels: bug

#648 Update release version to 2.11.0
  .github/workflows/build.yml
  .github/workflows/codeql.yml
  README.md
  hooks/build
  pom.xml
  settings.xml
  src/main/java/com/czertainly/core/api/ExceptionHandlingAdvice.java
  src/main/java/com/czertainly/core/api/web/CertificateControllerImpl.java
  src/main/java/com/czertainly/core/api/web/RAProfileManagementControllerImpl.java
  src/main/java/com/czertainly/core/dao/entity/Certificate.java
  src/main/java/com/czertainly/core/dao/entity/Crl.java
  src/main/java/com/czertainly/core/dao/entity/CrlEntry.java
  src/main/java/com/czertainly/core/dao/entity/CrlEntryId.java
  src/main/java/com/czertainly/core/dao/entity/RaProfile.java
  src/main/java/com/czertainly/core/dao/repository/CertificateRepository.java
  src/main/java/com/czertainly/core/dao/repository/CrlEntryRepository.java
  src/main/java/com/czertainly/core/dao/repository/CrlRepository.java
  src/main/java/com/czertainly/core/enums/SearchFieldNameEnum.java
  src/main/java/com/czertainly/core/messaging/listeners/NotificationListener.java
  src/main/java/com/czertainly/core/messaging/producers/NotificationProducer.java
  src/main/java/com/czertainly/core/service/CertificateService.java
  src/main/java/com/czertainly/core/service/CrlService.java
  src/main/java/com/czertainly/core/service/RaProfileService.java
  src/main/java/com/czertainly/core/service/impl/AttributeServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/CallbackServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/CertificateServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/ClientOperationServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/CrlServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/CryptographicKeyServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/DiscoveryServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/NotificationServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/RaProfileServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/RoleManagementServiceImpl.java
  src/main/java/com/czertainly/core/service/v2/impl/ClientOperationServiceImpl.java
  src/main/java/com/czertainly/core/tasks/DiscoveryCertificateTask.java
  src/main/java/com/czertainly/core/util/CertificateUtil.java
  src/main/java/com/czertainly/core/util/CrlUtil.java
  src/main/java/com/czertainly/core/util/converter/CertificateFormatEncodingConverter.java
  src/main/java/com/czertainly/core/validation/certificate/X509CertificateValidator.java
  src/main/resources/db/migration/V202311131230__trusted_ca_mark.sql
  src/main/resources/db/migration/V202312141140__authority_certifcat_uuid.sql
  src/main/resources/db/migration/V202401171122__ca_crl_management.sql
  src/test/java/com/czertainly/core/service/CertificateServiceTest.java
  src/test/java/com/czertainly/core/service/CertificateValidationTest.java
  src/test/java/com/czertainly/core/service/ClientOperationServiceV2Test.java
  src/test/java/com/czertainly/core/service/RaProfileServiceTest.java
Labels: ignore-for-release

#646 Update release version to 2.11.0
  README.md
  pom.xml
Labels: ignore-for-release

#649 Fix validation when setting content of custom attributes not associated with subject resource
  src/main/java/com/czertainly/core/service/impl/AttributeServiceImpl.java
Labels: bug

#650 Fix storing content of custom attributes when creating new user
  src/main/java/com/czertainly/core/service/impl/UserManagementServiceImpl.java
Labels: bug

#651 Implement bulk operations on internal notifications
  pom.xml
  src/main/java/com/czertainly/core/api/web/NotificationControllerImpl.java
  src/main/java/com/czertainly/core/service/NotificationService.java
  src/main/java/com/czertainly/core/service/impl/NotificationServiceImpl.java
Labels: enhancement
