Repository CZERTAINLY/CZERTAINLY-Core, pull requests merged in 2025-09, with the labels that each got.

#1131 Do not allow self association and fix pending relation for revoked successor certificate
  src/main/java/com/czertainly/core/service/impl/CertificateServiceImpl.java
  src/test/java/com/czertainly/core/service/CertificateServiceTest.java
Labels: bug, ignore-for-release

#1142 Do not allow association of certificates with different subject types
  src/main/java/com/czertainly/core/service/impl/CertificateServiceImpl.java
  src/test/java/com/czertainly/core/service/CertificateServiceTest.java
Labels: enhancement, ignore-for-release

#1141 Fix custom RDN OIDs translation when OID is updated
  src/main/java/com/czertainly/core/service/impl/CertificateServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/CrlServiceImpl.java
  src/main/java/com/czertainly/core/service/v2/impl/ClientOperationServiceImpl.java
  src/main/java/com/czertainly/core/tasks/UpdateIntuneRevocationRequestsTask.java
  src/main/java/com/czertainly/core/util/CertificateUtil.java
  src/test/java/com/czertainly/core/util/CzertainlyX500NameStyleTest.java
Labels: bug, ignore-for-release

#1145 Add timestamp to AuditLogDto and AuditLogExportDto
  src/main/java/com/czertainly/core/dao/entity/AuditLog.java
  src/main/java/com/czertainly/core/logging/AuditLogExportDto.java
  src/main/java/com/czertainly/core/service/impl/AuditLogServiceImpl.java
Labels: enhancement, ignore-for-release

#1148 Fix certificate statistic for users with restricted permissions
  src/main/java/com/czertainly/core/service/impl/CertificateServiceImpl.java
Labels: bug

#1147 Log actor name for Login operation
  src/main/java/com/czertainly/core/auth/oauth2/CzertainlyAuthenticationSuccessHandler.java
Labels: bug, ignore-for-release

#1146 Handle all exceptions when evaluating triggers in event handler
  src/main/java/com/czertainly/core/evaluator/TriggerEvaluator.java
  src/main/java/com/czertainly/core/events/EventHandler.java
  src/main/java/com/czertainly/core/events/handlers/CertificateDiscoveredEventHandler.java
Labels: bug

#1152 Improve validation for attribute content data
  src/main/java/com/czertainly/core/attribute/engine/AttributeEngine.java
  src/test/java/com/czertainly/core/attribute/AttributeEngineTest.java
Labels: enhancement
