Repository CZERTAINLY/CZERTAINLY-Core, pull requests merged in 2025-07, with the labels that each got.

#1085 Fix OCSP and CRL connection timeout
  src/main/java/com/czertainly/core/service/impl/CrlServiceImpl.java
  src/main/java/com/czertainly/core/util/CrlUtil.java
  src/main/java/com/czertainly/core/util/OcspUtil.java
  src/main/java/com/czertainly/core/validation/certificate/X509CertificateValidator.java
  src/main/resources/application.yml
  src/test/java/com/czertainly/core/helpers/CertificateGeneratorHelper.java
  src/test/java/com/czertainly/core/service/CertificateValidationTest.java
Labels: bug, codex

#1087 Fix missing certificate status changed event call when changing from Not Checked status
  src/main/java/com/czertainly/core/service/impl/CertificateServiceImpl.java
Labels: bug

#1089 Fix missing concurrency in ActionListener and make it configurable in all listeners
  src/main/java/com/czertainly/core/messaging/listeners/ActionListener.java
  src/main/java/com/czertainly/core/messaging/listeners/EventListener.java
  src/main/java/com/czertainly/core/messaging/listeners/NotificationListener.java
  src/main/java/com/czertainly/core/messaging/listeners/SchedulerListener.java
  src/main/java/com/czertainly/core/messaging/listeners/ValidationListener.java
  src/main/java/com/czertainly/core/service/v2/impl/ClientOperationServiceImpl.java
  src/main/resources/application.yml
Labels: bug, enhancement

#1092 Allow Expiring certificates in chain validation when issuing certificate with SCEP or CMP protocol
  src/main/java/com/czertainly/core/service/cmp/message/handler/CrmfMessageHandler.java
  src/main/java/com/czertainly/core/service/scep/impl/ScepServiceImpl.java
Labels: bug

#1093 Update release version to 2.15.1
  pom.xml
Labels: ignore-for-release

#1104 Do not load connector attributes if certificate RA Profile is not associated with authority and connector
  src/main/java/com/czertainly/core/dao/repository/CertificateRepository.java
  src/main/java/com/czertainly/core/service/impl/CertificateServiceImpl.java
Labels: bug
