Repository CZERTAINLY/CZERTAINLY-Core, pull requests merged in 2025-03, with the labels that each got.

#987 Fix adding same certificate to inventory from certificate extension in parallel certificate validations
  src/main/java/com/czertainly/core/dao/entity/Certificate.java
  src/main/java/com/czertainly/core/dao/entity/CertificateContent.java
  src/main/java/com/czertainly/core/dao/repository/CertificateContentRepository.java
  src/main/java/com/czertainly/core/dao/repository/CertificateRepository.java
  src/main/java/com/czertainly/core/service/CertificateService.java
  src/main/java/com/czertainly/core/service/impl/CertificateServiceImpl.java
  src/main/resources/db/migration/V202502281641__set_certificate_content_fingerprint_unique.sql
  src/test/java/com/czertainly/core/service/CertificateServiceTest.java
Labels: bug

#990 Add tests for issue and push operations in location
  src/test/java/com/czertainly/core/service/LocationServiceTest.java
Labels: ignore-for-release

#992 Fix adding same CRL in parallel certificate validations
  src/main/java/com/czertainly/core/dao/entity/Crl.java
  src/main/java/com/czertainly/core/dao/repository/CrlEntryRepository.java
  src/main/java/com/czertainly/core/dao/repository/CrlRepository.java
  src/main/java/com/czertainly/core/service/CrlService.java
  src/main/java/com/czertainly/core/service/impl/CertificateServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/CrlServiceImpl.java
Labels: bug

#989 Allow any UTF8 characters in CSR attribute common name
  src/main/java/com/czertainly/core/attribute/CsrAttributes.java
  src/main/java/com/czertainly/core/util/CertificateRequestUtils.java
  src/test/java/com/czertainly/core/util/CertificateRequestUtilsTest.java
Labels: enhancement

#993 Updates for release 2.14.1
  pom.xml
Labels: ignore-for-release

#996 Keep same OAuth2 provider client secret if not included in update request
  pom.xml
  src/main/java/com/czertainly/core/service/impl/SettingServiceImpl.java
  src/test/java/com/czertainly/core/security/oauth2/JwtDecoderTest.java
Labels: enhancement

#999 Fix resuming disabled scheduled job when editing its CRON expression
  src/main/java/com/czertainly/core/service/impl/SchedulerServiceImpl.java
Labels: bug

#995 Configure certificate validation for RA profile and platform
  pom.xml
  src/main/java/com/czertainly/core/api/web/RAProfileManagementControllerImpl.java
  src/main/java/com/czertainly/core/dao/entity/RaProfile.java
  src/main/java/com/czertainly/core/dao/repository/CertificateRepository.java
  src/main/java/com/czertainly/core/service/RaProfileService.java
  src/main/java/com/czertainly/core/service/impl/CertificateServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/RaProfileServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/SettingServiceImpl.java
  src/main/resources/db/migration/V202503061515__add_cert_validation_config_to_ra_profile.sql
  src/test/java/com/czertainly/core/service/RaProfileServiceTest.java
  src/test/java/com/czertainly/core/service/SettingServiceTest.java
  src/test/java/com/czertainly/core/tasks/UpdateCertificateStatusTaskTest.java
  src/test/resources/application.properties
Labels: enhancement

#1000 Optimize processing of CRL and creation of its entries
  src/main/java/com/czertainly/core/dao/entity/Crl.java
  src/main/java/com/czertainly/core/service/CrlService.java
  src/main/java/com/czertainly/core/service/impl/CrlServiceImpl.java
  src/main/java/com/czertainly/core/validation/certificate/X509CertificateValidator.java
  src/test/java/com/czertainly/core/service/CertificateValidationTest.java
Labels: bug

#1005 Refactor Certificate Validation Settings
  src/main/java/com/czertainly/core/api/web/RAProfileManagementControllerImpl.java
  src/main/java/com/czertainly/core/api/web/SettingControllerImpl.java
  src/main/java/com/czertainly/core/dao/entity/RaProfile.java
  src/main/java/com/czertainly/core/dao/repository/CertificateRepository.java
  src/main/java/com/czertainly/core/service/RaProfileService.java
  src/main/java/com/czertainly/core/service/SettingService.java
  src/main/java/com/czertainly/core/service/impl/CertificateServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/RaProfileServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/SettingServiceImpl.java
  src/main/resources/db/migration/V202503211515__change_constraint_in_cert_validation_config_to_ra_profile.sql
  src/test/java/com/czertainly/core/service/RaProfileServiceTest.java
  src/test/java/com/czertainly/core/service/SettingServiceTest.java
  src/test/java/com/czertainly/core/tasks/UpdateCertificateStatusTaskTest.java
Labels: ignore-for-release, refactoring

#1003 Add list of JWK set keys to OAuth2 Provider Settings response
  src/main/java/com/czertainly/core/api/web/SettingControllerImpl.java
  src/main/java/com/czertainly/core/service/SettingService.java
  src/main/java/com/czertainly/core/service/impl/SettingServiceImpl.java
  src/test/java/com/czertainly/core/security/oauth2/JwtDecoderTest.java
  src/test/java/com/czertainly/core/service/SettingServiceTest.java
Labels: enhancement

#1010 Update actions to main branch
  .github/workflows/build.yml
  .github/workflows/build_pr.yml
  .github/workflows/codeql.yml
  .github/workflows/publish_docker_3key.yaml
  .github/workflows/publish_docker_czertainly.yaml
  .github/workflows/publish_harbor_3key.yaml
  .github/workflows/test_docker_image.yaml
Labels: ignore-for-release

#1008 Fix bulk delete of certificates
  src/main/java/com/czertainly/core/service/impl/CertificateServiceImpl.java
  src/test/java/com/czertainly/core/service/CertificateServiceTest.java
Labels: bug

#1011 Add migration to fix duplicate certificate contents
  src/main/java/com/czertainly/core/util/DatabaseMigration.java
  src/main/java/db/migration/V202501281641__DuplicateCertificateContents.java
Labels: bug

#1014 Update certificate expiring check in validation to use expiring threshold configured for certificate
  src/main/java/com/czertainly/core/validation/certificate/X509CertificateValidator.java
  src/test/java/com/czertainly/core/service/CertificateValidationTest.java
Labels: enhancement
