Repository CZERTAINLY/CZERTAINLY-Core, pull requests merged in 2025-02, with the labels that each got.

#938 Update CZERTAINLY Dependencies
  pom.xml
  src/main/java/com/czertainly/core/dao/entity/Certificate.java
  src/main/java/com/czertainly/core/dao/entity/CryptographicKey.java
  src/main/java/com/czertainly/core/dao/entity/OwnerAssociation.java
  src/main/java/com/czertainly/core/dao/entity/ResourceObjectAssociation.java
  src/main/java/com/czertainly/core/dao/entity/UniquelyIdentified.java
  src/main/java/com/czertainly/core/dao/entity/UniquelyIdentifiedAndAudited.java
  src/main/java/com/czertainly/core/dao/entity/scep/ScepProfile.java
  src/main/java/com/czertainly/core/dao/repository/ApprovalProfileRepository.java
  src/main/java/com/czertainly/core/service/handler/CertificateHandler.java
  src/main/java/com/czertainly/core/service/impl/ScepProfileServiceImpl.java
  src/main/java/com/czertainly/core/util/FilterPredicatesBuilder.java
  src/test/java/com/czertainly/core/attribute/AttributeEngineTest.java
  src/test/java/com/czertainly/core/evaluator/RuleEvaluatorTest.java
  src/test/java/com/czertainly/core/service/AcmeServiceTest.java
  src/test/java/com/czertainly/core/service/ApprovalProfileServiceTest.java
  src/test/java/com/czertainly/core/service/ApprovalServiceTest.java
  src/test/java/com/czertainly/core/service/CertificateServiceTest.java
  src/test/java/com/czertainly/core/service/ClientOperationServiceV2Test.java
  src/test/java/com/czertainly/core/service/ConnectorServiceTest.java
  src/test/java/com/czertainly/core/service/CredentialServiceTest.java
  src/test/java/com/czertainly/core/service/CryptographicKeyServiceTest.java
  src/test/java/com/czertainly/core/service/DiscoveryServiceTest.java
  src/test/java/com/czertainly/core/service/LocationServiceTest.java
  src/test/java/com/czertainly/core/service/RaProfileServiceTest.java
  src/test/java/com/czertainly/core/service/ScepProfileServiceTest.java
  src/test/java/com/czertainly/core/service/SchedulerServiceTest.java
  src/test/java/com/czertainly/core/service/cmp/message/handler/RevocationMessageHandlerITest.java
  src/test/java/com/czertainly/core/util/BaseSpringBootTest.java
  src/test/java/com/czertainly/core/util/BaseSpringBootTestNoAuth.java
  src/test/java/com/czertainly/core/util/FilterPredicatesBuilderTest.java
Labels: dependencies

#940 Link public keys with existing certificates in inventory
  src/main/java/com/czertainly/core/api/web/CryptographicKeyControllerImpl.java
  src/main/java/com/czertainly/core/dao/entity/Certificate.java
  src/main/java/com/czertainly/core/dao/entity/CertificateRequestEntity.java
  src/main/java/com/czertainly/core/dao/entity/CryptographicKey.java
  src/main/java/com/czertainly/core/dao/entity/CryptographicKeyItem.java
  src/main/java/com/czertainly/core/dao/entity/OwnerAssociation.java
  src/main/java/com/czertainly/core/dao/repository/CertificateRepository.java
  src/main/java/com/czertainly/core/dao/repository/CryptographicKeyItemRepository.java
  src/main/java/com/czertainly/core/dao/repository/SecurityFilterRepositoryImpl.java
  src/main/java/com/czertainly/core/enums/FilterField.java
  src/main/java/com/czertainly/core/service/CryptographicKeyService.java
  src/main/java/com/czertainly/core/service/PermissionEvaluator.java
  src/main/java/com/czertainly/core/service/handler/CertificateHandler.java
  src/main/java/com/czertainly/core/service/impl/AuthPermissionEvaluationServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/CertificateServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/CryptographicKeyServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/CryptographicOperationServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/DiscoveryServiceImpl.java
  src/main/java/com/czertainly/core/util/CryptographyUtil.java
  src/main/java/com/czertainly/core/util/DatabaseMigration.java
  src/main/java/com/czertainly/core/util/FilterPredicatesBuilder.java
  src/main/java/db/migration/V202501281511__LinkKeysToCertificates.java
  src/test/java/com/czertainly/core/service/CertificateServiceTest.java
  src/test/java/com/czertainly/core/service/CryptographicKeyServiceTest.java
  src/test/java/com/czertainly/core/service/CryptographicOperationServiceTest.java
  src/test/java/com/czertainly/core/service/ScepProfileServiceTest.java
  src/test/java/com/czertainly/core/service/cmp/CmpEntityUtil.java
  src/test/java/com/czertainly/core/service/cmp/message/handler/CertConfirmMessageHandlerITest.java
  src/test/java/com/czertainly/core/service/cmp/message/handler/CrmfMessageHandlerITest.java
  src/test/java/com/czertainly/core/service/cmp/message/handler/KurMessageHandlerITest.java
  src/test/java/com/czertainly/core/service/cmp/message/handler/RevocationMessageHandlerITest.java
  src/test/java/com/czertainly/core/service/scep/CryptographicProviderTest.java
  src/test/java/com/czertainly/core/util/FilterPredicatesBuilderTest.java
Labels: enhancement

#950 Fix rekey operations to compare normalized subject
  src/main/java/com/czertainly/core/service/v2/impl/ClientOperationServiceImpl.java
Labels: bug

#952 Add SonarQube analysis into build process
  .github/workflows/build.yml
  pom.xml
Labels: ignore-for-release

#957 Update actions for Sonar
  .github/workflows/build_pr.yml
  .github/workflows/sonar.yaml
Labels: ignore-for-release

#958 Debug Sonar action
  .github/workflows/sonar.yaml
Labels: ignore-for-release

#959 Debug PR number Sonar
  .github/workflows/build_pr.yml
  .github/workflows/sonar.yaml
Labels: ignore-for-release

#956 Fix validation of JWT token structure when authenticating with token
  .github/workflows/build_pr.yml
  src/main/java/com/czertainly/core/auth/oauth2/CzertainlyJwtDecoder.java
  src/test/java/com/czertainly/core/security/oauth2/JwtDecoderTest.java
Labels: bug

#963 Update Build PR action
  .github/workflows/sonar.yaml
Labels: ignore-for-release

#964 Fix Sonar action
  .github/workflows/sonar.yaml
Labels: ignore-for-release

#966 Fix listing of internal notifications to prevent pagination in memory
  src/main/java/com/czertainly/core/api/ExceptionHandlingAdvice.java
  src/main/java/com/czertainly/core/dao/repository/NotificationRecipientRepository.java
  src/main/java/com/czertainly/core/dao/repository/NotificationRepository.java
  src/main/java/com/czertainly/core/service/impl/NotificationServiceImpl.java
  src/test/java/com/czertainly/core/evaluator/RuleEvaluatorTest.java
  src/test/java/com/czertainly/core/service/NotificationServiceTest.java
Labels: bug

#969 Add scheduled refresh settings cache from DB
  README.md
  src/main/java/com/czertainly/core/service/impl/SettingServiceImpl.java
  src/main/resources/application.properties
Labels: enhancement

#967 Remove enable and disable action from Approval profiles
  src/main/java/com/czertainly/core/api/web/ApprovalProfileControllerImpl.java
  src/main/java/com/czertainly/core/dao/entity/ApprovalProfile.java
  src/main/java/com/czertainly/core/dao/entity/ApprovalProfileVersion.java
  src/main/java/com/czertainly/core/service/ApprovalProfileService.java
  src/main/java/com/czertainly/core/service/impl/ApprovalProfileServiceImpl.java
  src/main/resources/db/migration/V202502171205__remove_enabled_column_in_approval_profile.sql
  src/test/java/com/czertainly/core/service/ApprovalProfileServiceTest.java
Labels: enhancement

#972 Fix assignment of mapped attributes when creating and editing of notification instance
  src/main/java/com/czertainly/core/service/impl/NotificationInstanceServiceImpl.java
Labels: bug

#973 Update keys management service to not use token instance as parameter
  src/main/java/com/czertainly/core/aop/AuditLogAspect.java
  src/main/java/com/czertainly/core/api/web/CryptographicKeyControllerImpl.java
  src/main/java/com/czertainly/core/dao/entity/CryptographicKeyItem.java
  src/main/java/com/czertainly/core/enums/FilterField.java
  src/main/java/com/czertainly/core/service/CryptographicKeyService.java
  src/main/java/com/czertainly/core/service/impl/CryptographicKeyServiceImpl.java
  src/test/java/com/czertainly/core/aop/AuditLogAspectTest.java
  src/test/java/com/czertainly/core/service/CryptographicKeyServiceTest.java
Labels: enhancement, ignore-for-release

#975 Implement compromise and destroy key operation without token instance
  src/main/java/com/czertainly/core/api/web/CryptographicKeyControllerImpl.java
  src/main/java/com/czertainly/core/service/CryptographicKeyService.java
  src/main/java/com/czertainly/core/service/impl/CryptographicKeyServiceImpl.java
  src/test/java/com/czertainly/core/aop/AuditLogAspectTest.java
  src/test/java/com/czertainly/core/service/CryptographicKeyServiceTest.java
Labels: enhancement, ignore-for-release

#978 Fix filtering of cryptographic keys on attributes
  src/main/java/com/czertainly/core/util/FilterPredicatesBuilder.java
Labels: bug

#976 Improve audit log purging performance
  src/main/java/com/czertainly/core/dao/repository/SecurityFilterRepository.java
  src/main/java/com/czertainly/core/dao/repository/SecurityFilterRepositoryImpl.java
  src/main/java/com/czertainly/core/security/authz/SecurityResourceFilter.java
  src/main/java/com/czertainly/core/service/impl/AuditLogServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/CertificateServiceImpl.java
  src/main/java/com/czertainly/core/util/FilterPredicatesBuilder.java
  src/test/java/com/czertainly/core/repository/SecurityFilterRepositoryTest.java
  src/test/java/com/czertainly/core/service/AuditLogServiceTest.java
Labels: enhancement

#979 Fix protocol URI prefix to allow access to protocol endpoints as anonymous user
  src/main/java/com/czertainly/core/config/ProtocolValidationFilter.java
  src/main/java/com/czertainly/core/config/SecurityConfig.java
  src/test/resources/application.properties
Labels: bug, ignore-for-release

#977 Add tests for authentication with OAuth2 Login
  src/main/java/com/czertainly/core/auth/oauth2/CzertainlyClientRegistrationRepository.java
  src/main/java/com/czertainly/core/auth/oauth2/OAuth2LoginFilter.java
  src/main/java/com/czertainly/core/config/SecurityConfig.java
  src/main/resources/db/migration/V202502251441__fix_spring_session_fk.sql
  src/test/java/com/czertainly/core/config/SecurityConfigTest.java
  src/test/java/com/czertainly/core/config/SessionConfig.java
  src/test/java/com/czertainly/core/security/oauth2/OAuth2AuthenticationSuccessHandlerTest.java
  src/test/java/com/czertainly/core/security/oauth2/OAuth2TestUtil.java
  src/test/java/com/czertainly/core/security/oauth2/SecurityConfigTest.java
Labels: enhancement, ignore-for-release

#983 Fix creation of CzertainlyAnonymousToken in authentication filter
  src/main/java/com/czertainly/core/security/authn/CzertainlyAuthenticationFilter.java
Labels: bug, ignore-for-release

#982 Issue attributes are not sent to connector and stored with certificate when issuing certificate
  src/main/java/com/czertainly/core/service/impl/CertificateServiceImpl.java
Labels: bug

#986 Fix deleting certificate by first removing its associations
  src/main/java/com/czertainly/core/service/impl/CertificateServiceImpl.java
Labels: bug
