Repository CZERTAINLY/CZERTAINLY-Core, pull requests merged in 2025-04, with the labels that each got.

#1012 Fix missing RA profile attributes in legacy client operations
  src/main/java/com/czertainly/core/service/impl/ClientOperationServiceImpl.java
Labels: bug

#1015 Fix changing certificate status to expiring when RA Profile validation is null
  src/main/java/com/czertainly/core/validation/certificate/X509CertificateValidator.java
Labels: bug, ignore-for-release

#1016 Add listing permissions to user profile response
  src/main/java/com/czertainly/core/api/web/AuthControllerImpl.java
  src/main/java/com/czertainly/core/service/AuthService.java
  src/main/java/com/czertainly/core/service/impl/AuthServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/SettingServiceImpl.java
  src/test/java/com/czertainly/core/service/AuthServiceTest.java
Labels: enhancement

#1019 Merge Hotfix 2.14.2
  pom.xml
  src/main/java/com/czertainly/core/service/impl/CertificateServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/ClientOperationServiceImpl.java
  src/main/java/com/czertainly/core/util/DatabaseMigration.java
  src/main/java/db/migration/V202501281641__DuplicateCertificateContents.java
  src/test/java/com/czertainly/core/service/CertificateServiceTest.java
Labels: ignore-for-release

#1021 Add protocol filter to certificate inventory
  src/main/java/com/czertainly/core/enums/FilterField.java
  src/main/java/com/czertainly/core/service/impl/CertificateServiceImpl.java
Labels: enhancement

#1018 Fix certificate validation for null validation frequency and expiring threshold in platform settings
  src/main/java/com/czertainly/core/dao/entity/Certificate.java
  src/main/java/com/czertainly/core/dao/repository/CertificateRepository.java
  src/main/java/com/czertainly/core/service/handler/CertificateHandler.java
  src/main/java/com/czertainly/core/service/impl/CertificateServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/SettingServiceImpl.java
  src/main/java/com/czertainly/core/util/CertificateUtil.java
  src/main/java/com/czertainly/core/validation/certificate/X509CertificateValidator.java
  src/test/java/com/czertainly/core/service/CertificateValidationTest.java
  src/test/java/com/czertainly/core/tasks/UpdateCertificateStatusTaskTest.java
Labels: bug, ignore-for-release
