Repository CZERTAINLY/CZERTAINLY-Core, pull requests merged in 2025-06, with the labels that each got.

#1040 Add support for Default recipient type and multiple recipients of same type in notification profile
  src/main/java/com/czertainly/core/dao/entity/notifications/NotificationProfileVersion.java
  src/main/java/com/czertainly/core/events/data/EventDataBuilder.java
  src/main/java/com/czertainly/core/events/handlers/ApprovalClosedEventHandler.java
  src/main/java/com/czertainly/core/events/handlers/ApprovalRequestedEventHandler.java
  src/main/java/com/czertainly/core/events/handlers/CertificateActionPerformedEventHandler.java
  src/main/java/com/czertainly/core/events/handlers/CertificateDiscoveredEventHandler.java
  src/main/java/com/czertainly/core/events/handlers/CertificateStatusChangedEventHandler.java
  src/main/java/com/czertainly/core/events/handlers/DiscoveryFinishedEventHandler.java
  src/main/java/com/czertainly/core/events/handlers/ScheduledJobFinishedEventHandler.java
  src/main/java/com/czertainly/core/messaging/listeners/NotificationListener.java
  src/main/java/com/czertainly/core/service/ResourceObjectAssociationService.java
  src/main/java/com/czertainly/core/service/impl/NotificationProfileServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/ResourceObjectAssociationServiceImpl.java
  src/main/resources/db/migration/V202505261357__notifications_profile_multiple_recipients.sql
  src/test/java/com/czertainly/core/events/EventHandlersTest.java
  src/test/java/com/czertainly/core/service/NotificationProfileServiceTest.java
Labels: enhancement, ignore-for-release

#1044 Add validation to association of triggers to event to match resources
  src/main/java/com/czertainly/core/service/impl/TriggerServiceImpl.java
Labels: bug, ignore-for-release

#1048 Fix validation of rule and action update to check for resource compatibility with already associated triggers
  src/main/java/com/czertainly/core/service/impl/ActionServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/RuleServiceImpl.java
Labels: bug, ignore-for-release

#1057 Add purpose column to attribute content for object to differentiate between different content for same attributes
  src/main/java/com/czertainly/core/attribute/engine/AttributeContentPurpose.java
  src/main/java/com/czertainly/core/attribute/engine/AttributeEngine.java
  src/main/java/com/czertainly/core/attribute/engine/AttributeOperation.java
  src/main/java/com/czertainly/core/attribute/engine/records/ObjectAttributeContentInfo.java
  src/main/java/com/czertainly/core/dao/entity/AttributeContent2Object.java
  src/main/java/com/czertainly/core/dao/repository/AttributeContent2ObjectRepository.java
  src/main/java/com/czertainly/core/service/impl/CertificateServiceImpl.java
  src/main/java/com/czertainly/core/service/v2/impl/ClientOperationServiceImpl.java
  src/main/resources/db/migration/V202506131622__add_purpose_to_attribute_content_2_object.sql
Labels: enhancement, ignore-for-release

#1058 Exclude not issued certificates from Expired statistics
  src/main/java/com/czertainly/core/service/impl/CertificateServiceImpl.java
Labels: bug

#1063 Authenticate as user that set event trigger associations when processing triggers in event handler
  src/main/java/com/czertainly/core/dao/entity/workflows/TriggerAssociation.java
  src/main/java/com/czertainly/core/dao/entity/workflows/TriggerHistory.java
  src/main/java/com/czertainly/core/evaluator/ITriggerEvaluator.java
  src/main/java/com/czertainly/core/evaluator/TriggerEvaluator.java
  src/main/java/com/czertainly/core/events/EventContext.java
  src/main/java/com/czertainly/core/events/EventHandler.java
  src/main/java/com/czertainly/core/events/handlers/CertificateDiscoveredEventHandler.java
  src/main/java/com/czertainly/core/service/TriggerService.java
  src/main/java/com/czertainly/core/service/impl/ResourceServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/TriggerServiceImpl.java
  src/main/java/com/czertainly/core/util/AuthHelper.java
  src/main/resources/db/migration/V202504141012__integrate_events_with_workflows.sql
  src/test/java/com/czertainly/core/events/EventHandlersTest.java
Labels: enhancement, ignore-for-release

#1077 Convert application properties to YAML
  src/main/resources/application.properties
  src/main/resources/application.yml
  src/test/resources/application.properties
  src/test/resources/application.yml
Labels: ignore-for-release
