Repository CZERTAINLY/CZERTAINLY-Core, pull requests merged in 2025-05, with the labels that each got.

#1024 Add event handlers and integrate events with triggers
  src/main/java/com/czertainly/core/api/ExceptionHandlingAdvice.java
  src/main/java/com/czertainly/core/api/web/TriggerControllerImpl.java
  src/main/java/com/czertainly/core/dao/entity/UniquelyIdentified.java
  src/main/java/com/czertainly/core/dao/entity/UniquelyIdentifiedAndAudited.java
  src/main/java/com/czertainly/core/dao/entity/UniquelyIdentifiedObject.java
  src/main/java/com/czertainly/core/dao/entity/workflows/Action.java
  src/main/java/com/czertainly/core/dao/entity/workflows/Condition.java
  src/main/java/com/czertainly/core/dao/entity/workflows/Execution.java
  src/main/java/com/czertainly/core/dao/entity/workflows/Rule.java
  src/main/java/com/czertainly/core/dao/entity/workflows/Trigger.java
  src/main/java/com/czertainly/core/dao/entity/workflows/TriggerAssociation.java
  src/main/java/com/czertainly/core/dao/entity/workflows/TriggerHistory.java
  src/main/java/com/czertainly/core/dao/repository/DiscoveryCertificateRepository.java
  src/main/java/com/czertainly/core/dao/repository/workflows/TriggerAssociationRepository.java
  src/main/java/com/czertainly/core/dao/repository/workflows/TriggerRepository.java
  src/main/java/com/czertainly/core/evaluator/CertificateRuleEvaluator.java
  src/main/java/com/czertainly/core/evaluator/IRuleEvaluator.java
  src/main/java/com/czertainly/core/evaluator/RuleEvaluator.java
  src/main/java/com/czertainly/core/events/EventContext.java
  src/main/java/com/czertainly/core/events/EventHandler.java
  src/main/java/com/czertainly/core/events/IEventHandler.java
  src/main/java/com/czertainly/core/events/data/DiscoveryResult.java
  src/main/java/com/czertainly/core/events/handlers/ApprovalClosedEventHandler.java
  src/main/java/com/czertainly/core/events/handlers/ApprovalRequestedEventHandler.java
  src/main/java/com/czertainly/core/events/handlers/CertificateActionPerformedEventHandler.java
  src/main/java/com/czertainly/core/events/handlers/CertificateDiscoveredEventHandler.java
  src/main/java/com/czertainly/core/events/handlers/CertificateStatusChangedEventHandler.java
  src/main/java/com/czertainly/core/events/handlers/DiscoveryFinishedEventHandler.java
  src/main/java/com/czertainly/core/events/handlers/ScheduledJobFinishedEventHandler.java
  src/main/java/com/czertainly/core/events/transaction/CertificateValidationEvent.java
  src/main/java/com/czertainly/core/events/transaction/ScheduledJobFinishedEvent.java
  src/main/java/com/czertainly/core/events/transaction/TransactionHandler.java
  src/main/java/com/czertainly/core/events/transaction/UpdateCertificateHistoryEvent.java
  src/main/java/com/czertainly/core/messaging/configuration/RabbitMQConstants.java
  src/main/java/com/czertainly/core/messaging/listeners/EventListener.java
  src/main/java/com/czertainly/core/messaging/model/EventMessage.java
  src/main/java/com/czertainly/core/messaging/producers/EventProducer.java
  src/main/java/com/czertainly/core/messaging/producers/NotificationProducer.java
  src/main/java/com/czertainly/core/model/ScheduledTaskResult.java
  src/main/java/com/czertainly/core/service/CertificateEventHistoryService.java
  src/main/java/com/czertainly/core/service/TriggerService.java
  src/main/java/com/czertainly/core/service/handler/CertificateHandler.java
  src/main/java/com/czertainly/core/service/impl/ActionServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/ApprovalServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/CertificateEventHistoryServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/CertificateServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/DiscoveryServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/LocationServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/ResourceServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/RuleServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/SchedulerServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/TriggerServiceImpl.java
  src/main/java/com/czertainly/core/service/v2/impl/ClientOperationServiceImpl.java
  src/main/resources/db/migration/V202504141012__integrate_events_with_workflows.sql
  src/test/java/com/czertainly/core/evaluator/RuleEvaluatorTest.java
  src/test/java/com/czertainly/core/service/RuleServiceTest.java
  src/test/java/com/czertainly/core/service/SchedulerServiceTest.java
  src/test/java/com/czertainly/core/service/TriggerServiceTest.java
Labels: enhancement

#1026 Add notification profiles and its management operations
  src/main/java/com/czertainly/core/api/web/NotificationProfileControllerImpl.java
  src/main/java/com/czertainly/core/dao/entity/NotificationProfile.java
  src/main/java/com/czertainly/core/dao/entity/NotificationProfileVersion.java
  src/main/java/com/czertainly/core/dao/repository/NotificationProfileRepository.java
  src/main/java/com/czertainly/core/dao/repository/NotificationProfileVersionRepository.java
  src/main/java/com/czertainly/core/enums/RecipientTypeEnum.java
  src/main/java/com/czertainly/core/messaging/listeners/NotificationListener.java
  src/main/java/com/czertainly/core/messaging/model/NotificationRecipient.java
  src/main/java/com/czertainly/core/model/auth/Resource.java
  src/main/java/com/czertainly/core/service/NotificationProfileService.java
  src/main/java/com/czertainly/core/service/ResourceObjectAssociationService.java
  src/main/java/com/czertainly/core/service/impl/NotificationProfileServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/ResourceObjectAssociationServiceImpl.java
  src/main/resources/application.properties
  src/main/resources/db/migration/V202504291559__notification_profiles.sql
  src/test/java/com/czertainly/core/service/NotificationProfileServiceTest.java
  src/test/resources/application.properties
Labels: new-feature

#1028 Add missing result message to validation result response DTO
  src/main/java/com/czertainly/core/service/impl/CertificateServiceImpl.java
Labels: bug, ignore-for-release

#1029 Deactivate tokens containing keys with deprecated algorithms
  src/main/java/com/czertainly/core/service/impl/CryptographicKeyServiceImpl.java
  src/main/java/com/czertainly/core/util/DatabaseMigration.java
  src/main/resources/db/migration/V202505121128__deactivate_deprecated_tokens.sql
Labels: ignore-for-release

#1031 Check configuration for new ACME account requests
  src/main/java/com/czertainly/core/service/acme/impl/AcmeServiceImpl.java
  src/test/java/com/czertainly/core/service/AcmeServiceTest.java
Labels: bug

#1034 Change execution item for send notification execution type
  src/main/java/com/czertainly/core/api/web/ActionControllerImpl.java
  src/main/java/com/czertainly/core/dao/entity/workflows/ExecutionItem.java
  src/main/java/com/czertainly/core/dao/repository/workflows/ExecutionRepository.java
  src/main/java/com/czertainly/core/evaluator/TriggerEvaluator.java
  src/main/java/com/czertainly/core/service/ActionService.java
  src/main/java/com/czertainly/core/service/impl/ActionServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/NotificationProfileServiceImpl.java
  src/main/resources/db/migration/V202505071511__notifications_execution.sql
  src/test/java/com/czertainly/core/evaluator/TriggerEvaluatorTest.java
  src/test/java/com/czertainly/core/service/RuleServiceTest.java
  src/test/java/com/czertainly/core/service/TriggerServiceTest.java
Labels: ignore-for-release

#1037 Implement event trigger association on resource object and platform settings
  src/main/java/com/czertainly/core/api/web/SettingControllerImpl.java
  src/main/java/com/czertainly/core/api/web/TriggerControllerImpl.java
  src/main/java/com/czertainly/core/dao/repository/notifications/NotificationProfileVersionRepository.java
  src/main/java/com/czertainly/core/dao/repository/workflows/TriggerAssociationRepository.java
  src/main/java/com/czertainly/core/events/EventHandler.java
  src/main/java/com/czertainly/core/events/handlers/CertificateDiscoveredEventHandler.java
  src/main/java/com/czertainly/core/events/handlers/DiscoveryFinishedEventHandler.java
  src/main/java/com/czertainly/core/service/SettingService.java
  src/main/java/com/czertainly/core/service/TriggerService.java
  src/main/java/com/czertainly/core/service/impl/DiscoveryServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/NotificationInstanceServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/SettingServiceImpl.java
  src/main/java/com/czertainly/core/service/impl/TriggerServiceImpl.java
  src/test/java/com/czertainly/core/events/EventHandlersTest.java
  src/test/java/com/czertainly/core/service/NotificationInstanceServiceTest.java
  src/test/java/com/czertainly/core/service/SettingServiceTest.java
Labels: new-feature

#1036 Fix updating execution items for send notification
  src/main/java/com/czertainly/core/dao/repository/workflows/ExecutionItemRepository.java
  src/main/java/com/czertainly/core/service/impl/ActionServiceImpl.java
Labels: bug, ignore-for-release

#1038 Change types of certificate filter fields Expires At and Valid From to Datetime
  src/main/java/com/czertainly/core/enums/FilterField.java
  src/main/java/com/czertainly/core/util/DatabaseMigration.java
  src/main/java/com/czertainly/core/util/SearchHelper.java
  src/main/java/db/migration/V202505211440__ChangeConditionValueForNotAfterAndNotBefore.java
  src/test/java/com/czertainly/core/evaluator/TriggerEvaluatorTest.java
  src/test/java/com/czertainly/core/util/FilterPredicatesBuilderTest.java
  src/test/java/com/czertainly/core/util/SearchHelperTest.java
Labels: bug, ignore-for-release
